use super::{curio_types::GoldAndGearsCurioId, occurrence_types::GoldAndGearsOccurrenceChoiceId};

/// Typed construction failures before a Gold Activity instance can start.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum GoldAndGearsEntryError {
    InvalidCatalog,
    ParticipantPolicyMismatch,
    UnknownArea(Box<str>),
    GuideArea(Box<str>),
    UnknownPath(Box<str>),
    UnknownDice(Box<str>),
    LockedDice(Box<str>),
    DuplicateUnlockedDice(Box<str>),
    UnknownDiceFace(Box<str>),
    InvalidDiceFaceCount,
    DuplicateDiceFace(Box<str>),
    LockedDiceFace(Box<str>),
    DiceFaceSlotMismatch(Box<str>),
    DiceFaceDiceMismatch(Box<str>),
    DiceFaceRarityMismatch(Box<str>),
    InvalidDiceLoadoutRuntime,
    InvalidDiceRuntime,
    MissingDiceResult,
    DiceFaceNotInLoadout(Box<str>),
    NoDiceRerolls,
    NoDiceCheats,
    InvalidDicePlane,
    InvalidDicePassiveEvent,
    InvalidDiceFaceRuntime,
    DiceFaceNotRolled,
    InvalidDiceFaceTarget,
    NoLegalDiceFaceTarget,
    InvalidKnowledgeRuntime,
    InvalidKnowledgeTarget,
    UnknownNeuralNode(Box<str>),
    DuplicateNeuralNode(Box<str>),
    MissingNeuralPrerequisite {
        node: Box<str>,
        prerequisite: Box<str>,
    },
    InvalidNeuralRuntime,
    NeuralAlreadyAcquired(Box<str>),
    InsufficientNeuralCurrency {
        required: u32,
        available: u32,
    },
    UnknownCompletedArea(Box<str>),
    DuplicateCompletedArea(Box<str>),
    InvalidConundrumLevel,
    ConundrumDifficultyMismatch,
    MissingConundrumPrerequisite,
    InvalidConundrumRuntime,
    InvalidStatsConundrumModifier,
    InvalidAuxiliaryConundrumRule,
    AuxiliaryConundrumRuleAlreadyApplied,
    AuxiliaryConundrumStateMismatch,
    UnknownTrailblazeBonus(Box<str>),
    LockedTrailblazeBonus(Box<str>),
    InvalidProgressionRuntime,
    MissingProfileEntryRule,
    InvalidProfileEntryRule,
    ProfileEntryRuleAlreadyApplied,
    ProfileEntryStateMismatch,
    InvalidProgressionState,
    InvalidResonanceSelection,
    InvalidBlessingCounts,
    InvalidExtrapolationBoundary,
    UnknownExtrapolationPath(Box<str>),
    InvalidSharedContentRuntime,
    InvalidBlessingInventory,
    UnknownBlessing(u32),
    InvalidCurioRuntime,
    InvalidCurioInventory,
    InvalidCurioOffer,
    UnknownCurio(GoldAndGearsCurioId),
    CurioHasNoCharges(GoldAndGearsCurioId),
    InvalidCurioCharge(GoldAndGearsCurioId),
    InvalidCurioLifecycle(GoldAndGearsCurioId),
    CurioCannotBeRepaired(GoldAndGearsCurioId),
    InvalidCurioRepairProgress(GoldAndGearsCurioId),
    InvalidCurioReplacement,
    InvalidOccurrenceRuntime,
    UnknownOccurrenceChoice(GoldAndGearsOccurrenceChoiceId),
    OccurrenceChoiceIsNotRandom(GoldAndGearsOccurrenceChoiceId),
    InvalidOccurrenceCandidates,
    InvalidOccurrenceSelection(GoldAndGearsOccurrenceChoiceId),
    InvalidServiceRuntime,
    UnknownService(Box<str>),
    InvalidServiceOffer,
    ServiceStockExhausted,
    InvalidAdventureRuntime,
    UnknownAdventure(u32),
    InvalidAdventureOutcome,
    MissingCognitionRange,
    InvalidActivityState,
    InvalidPlaneCount,
    MissingPlane(Box<str>),
    MissingChessboard(Box<str>),
    InvalidTopology,
    InvalidMapRuntime,
    UnknownChessboard(Box<str>),
    UnknownDomain(Box<str>),
    UnknownBeacon(Box<str>),
    MissingMapEvent,
    MapCapacityExceeded,
    InvalidCognitionRuntime,
    InvalidCognitionDelta,
    InvalidCognitionState,
    InvalidPlaneLayer,
    InvalidPlaneTransition,
    UnknownBossChoice(Box<str>),
}

impl core::fmt::Display for GoldAndGearsEntryError {
    fn fmt(&self, formatter: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(formatter, "Gold and Gears entry rejected: {self:?}")
    }
}

impl std::error::Error for GoldAndGearsEntryError {}
