// This file was generated by Sora. Do not edit manually.

#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum DuCurioElationPolicy {
    ActionResolvedOriginalPartyRefresh = 0,
}

impl super::runtime::SoraDecode for DuCurioElationPolicy {
    fn decode(reader: &mut super::runtime::SoraReader<'_>) -> Result<Self, super::runtime::SoraReadError> {
        match reader.read_var_u32()? {
            0 => Ok(Self::ActionResolvedOriginalPartyRefresh),
            value => Err(super::runtime::SoraReadError::new(format!("invalid enum id {} for DuCurioElationPolicy", value))),
        }
    }
}
