// This file was generated by Sora. Do not edit manually.
use super::SoraMap;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct DuDecisionOccurrences {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "stable_key")]
    pub stable_key: String,
    #[serde(rename = "reference_occurrence")]
    pub reference_occurrence: String,
    #[serde(rename = "reference_variant")]
    pub reference_variant: String,
    #[serde(rename = "policy_id")]
    pub policy_id: i32,
    #[serde(rename = "source_ids")]
    pub source_ids: Vec<i32>,
}

impl super::runtime::SoraDecode for DuDecisionOccurrences {
    fn decode(reader: &mut super::runtime::SoraReader<'_>) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            stable_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            reference_occurrence: <String as super::runtime::SoraDecode>::decode(reader)?,
            reference_variant: <String as super::runtime::SoraDecode>::decode(reader)?,
            policy_id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            source_ids: { let len = reader.read_var_u32()? as usize; let mut values = Vec::with_capacity(len); for _ in 0..len { values.push(<i32 as super::runtime::SoraDecode>::decode(reader)?); } values },
        })
    }
}

impl DuDecisionOccurrences {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct DuDecisionOccurrencesTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, DuDecisionOccurrences>,
    by_stable_key: SoraMap<String, i32>,
}

impl DuDecisionOccurrencesTable {
    pub const NAME: &'static str = "DuDecisionOccurrences";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "DuDecisionOccurrences",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[
            super::SoraIndexInfo {
                name: "by_stable_key",
                unique: true,
                fields: &["stable_key"],
            },
        ],
    };

    pub(super) fn from_rows(rows: Vec<DuDecisionOccurrences>) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        let by_stable_key = super::build_unique_map_index(
            rows.iter(),
            |row| row.stable_key.clone(),
            |row| row.id,
        );
        let rows = super::decode_map_table(rows, |row| row.id);
        Ok(Self {
            keys,
            rows,
            by_stable_key,
        })
    }

    pub fn get(&self, key: &i32) -> Option<&DuDecisionOccurrences> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &DuDecisionOccurrences> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
    pub fn get_by_stable_key(&self, stable_key: &str) -> Option<&DuDecisionOccurrences> {
        self.by_stable_key.get(stable_key).and_then(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for DuDecisionOccurrencesTable {
    type Target = SoraMap<i32, DuDecisionOccurrences>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for DuDecisionOccurrencesTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for DuDecisionOccurrencesTable {
    type Key = i32;
    type Row = DuDecisionOccurrences;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
