// This file was generated by Sora. Do not edit manually.
use super::du_domain_deck_policy::DuDomainDeckPolicy;
use super::SoraMap;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct DuDomainDecks {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "stable_key")]
    pub stable_key: String,
    #[serde(rename = "style_source")]
    pub style_source: String,
    #[serde(rename = "policy")]
    pub policy: DuDomainDeckPolicy,
    #[serde(rename = "card_count")]
    pub card_count: i32,
    #[serde(rename = "policy_note")]
    pub policy_note: String,
    #[serde(rename = "replacement_condition")]
    pub replacement_condition: String,
    #[serde(rename = "source_locator")]
    pub source_locator: String,
    #[serde(rename = "source_ids")]
    pub source_ids: Vec<i32>,
}

impl super::runtime::SoraDecode for DuDomainDecks {
    fn decode(reader: &mut super::runtime::SoraReader<'_>) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            stable_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            style_source: <String as super::runtime::SoraDecode>::decode(reader)?,
            policy: <DuDomainDeckPolicy as super::runtime::SoraDecode>::decode(reader)?,
            card_count: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            policy_note: <String as super::runtime::SoraDecode>::decode(reader)?,
            replacement_condition: <String as super::runtime::SoraDecode>::decode(reader)?,
            source_locator: <String as super::runtime::SoraDecode>::decode(reader)?,
            source_ids: { let len = reader.read_var_u32()? as usize; let mut values = Vec::with_capacity(len); for _ in 0..len { values.push(<i32 as super::runtime::SoraDecode>::decode(reader)?); } values },
        })
    }
}

impl DuDomainDecks {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct DuDomainDecksTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, DuDomainDecks>,
    by_stable_key: SoraMap<String, i32>,
}

impl DuDomainDecksTable {
    pub const NAME: &'static str = "DuDomainDecks";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "DuDomainDecks",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[
            super::SoraIndexInfo {
                name: "by_stable_key",
                unique: true,
                fields: &["stable_key"],
            },
        ],
    };

    pub(super) fn from_rows(rows: Vec<DuDomainDecks>) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        let by_stable_key = super::build_unique_map_index(
            rows.iter(),
            |row| row.stable_key.clone(),
            |row| row.id,
        );
        let rows = super::decode_map_table(rows, |row| row.id);
        Ok(Self {
            keys,
            rows,
            by_stable_key,
        })
    }

    pub fn get(&self, key: &i32) -> Option<&DuDomainDecks> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &DuDomainDecks> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
    pub fn get_by_stable_key(&self, stable_key: &str) -> Option<&DuDomainDecks> {
        self.by_stable_key.get(stable_key).and_then(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for DuDomainDecksTable {
    type Target = SoraMap<i32, DuDomainDecks>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for DuDomainDecksTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for DuDomainDecksTable {
    type Key = i32;
    type Row = DuDomainDecks;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
