// This file was generated by Sora. Do not edit manually.
use super::du_decision_evidence::DuDecisionEvidence;
use super::SoraMap;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct DuDecisionSources {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "stable_key")]
    pub stable_key: String,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "revision")]
    pub revision: String,
    #[serde(rename = "game_version")]
    pub game_version: String,
    #[serde(rename = "access_date")]
    pub access_date: String,
    #[serde(rename = "locator")]
    pub locator: String,
    #[serde(rename = "sha256")]
    pub sha256: String,
    #[serde(rename = "quality")]
    pub quality: DuDecisionEvidence,
    #[serde(rename = "note")]
    pub note: String,
}

impl super::runtime::SoraDecode for DuDecisionSources {
    fn decode(reader: &mut super::runtime::SoraReader<'_>) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            stable_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            url: <String as super::runtime::SoraDecode>::decode(reader)?,
            revision: <String as super::runtime::SoraDecode>::decode(reader)?,
            game_version: <String as super::runtime::SoraDecode>::decode(reader)?,
            access_date: <String as super::runtime::SoraDecode>::decode(reader)?,
            locator: <String as super::runtime::SoraDecode>::decode(reader)?,
            sha256: <String as super::runtime::SoraDecode>::decode(reader)?,
            quality: <DuDecisionEvidence as super::runtime::SoraDecode>::decode(reader)?,
            note: <String as super::runtime::SoraDecode>::decode(reader)?,
        })
    }
}

impl DuDecisionSources {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct DuDecisionSourcesTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, DuDecisionSources>,
    by_stable_key: SoraMap<String, i32>,
}

impl DuDecisionSourcesTable {
    pub const NAME: &'static str = "DuDecisionSources";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "DuDecisionSources",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[
            super::SoraIndexInfo {
                name: "by_stable_key",
                unique: true,
                fields: &["stable_key"],
            },
        ],
    };

    pub(super) fn from_rows(rows: Vec<DuDecisionSources>) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        let by_stable_key = super::build_unique_map_index(
            rows.iter(),
            |row| row.stable_key.clone(),
            |row| row.id,
        );
        let rows = super::decode_map_table(rows, |row| row.id);
        Ok(Self {
            keys,
            rows,
            by_stable_key,
        })
    }

    pub fn get(&self, key: &i32) -> Option<&DuDecisionSources> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &DuDecisionSources> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
    pub fn get_by_stable_key(&self, stable_key: &str) -> Option<&DuDecisionSources> {
        self.by_stable_key.get(stable_key).and_then(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for DuDecisionSourcesTable {
    type Target = SoraMap<i32, DuDecisionSources>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for DuDecisionSourcesTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for DuDecisionSourcesTable {
    type Key = i32;
    type Row = DuDecisionSources;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
