// This file was generated by Sora. Do not edit manually.
use super::du_evolution_option_kind::DuEvolutionOptionKind;
use super::SoraMap;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct DuEvolutionOptions {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "stable_key")]
    pub stable_key: String,
    #[serde(rename = "event_id")]
    pub event_id: i32,
    #[serde(rename = "ordinal")]
    pub ordinal: i32,
    #[serde(rename = "kind")]
    pub kind: DuEvolutionOptionKind,
    #[serde(rename = "name_en")]
    pub name_en: String,
    #[serde(rename = "name_zh_cn")]
    pub name_zh_cn: String,
    #[serde(rename = "fragment_cost")]
    pub fragment_cost: i32,
    #[serde(rename = "fragment_grant")]
    pub fragment_grant: i32,
    #[serde(rename = "curio_count")]
    pub curio_count: i32,
    #[serde(rename = "minimum_rarity")]
    pub minimum_rarity: i32,
    #[serde(rename = "maximum_rarity")]
    pub maximum_rarity: i32,
    #[serde(rename = "success_numerator")]
    pub success_numerator: i32,
    #[serde(rename = "success_denominator")]
    pub success_denominator: i32,
    #[serde(rename = "source_ids")]
    pub source_ids: Vec<i32>,
}

impl super::runtime::SoraDecode for DuEvolutionOptions {
    fn decode(reader: &mut super::runtime::SoraReader<'_>) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            stable_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            event_id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            ordinal: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            kind: <DuEvolutionOptionKind as super::runtime::SoraDecode>::decode(reader)?,
            name_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            fragment_cost: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            fragment_grant: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            curio_count: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            minimum_rarity: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            maximum_rarity: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            success_numerator: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            success_denominator: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            source_ids: { let len = reader.read_var_u32()? as usize; let mut values = Vec::with_capacity(len); for _ in 0..len { values.push(<i32 as super::runtime::SoraDecode>::decode(reader)?); } values },
        })
    }
}

impl DuEvolutionOptions {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct DuEvolutionOptionsTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, DuEvolutionOptions>,
    by_stable_key: SoraMap<String, i32>,
}

impl DuEvolutionOptionsTable {
    pub const NAME: &'static str = "DuEvolutionOptions";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "DuEvolutionOptions",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[
            super::SoraIndexInfo {
                name: "by_stable_key",
                unique: true,
                fields: &["stable_key"],
            },
        ],
    };

    pub(super) fn from_rows(rows: Vec<DuEvolutionOptions>) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        let by_stable_key = super::build_unique_map_index(
            rows.iter(),
            |row| row.stable_key.clone(),
            |row| row.id,
        );
        let rows = super::decode_map_table(rows, |row| row.id);
        Ok(Self {
            keys,
            rows,
            by_stable_key,
        })
    }

    pub fn get(&self, key: &i32) -> Option<&DuEvolutionOptions> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &DuEvolutionOptions> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
    pub fn get_by_stable_key(&self, stable_key: &str) -> Option<&DuEvolutionOptions> {
        self.by_stable_key.get(stable_key).and_then(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for DuEvolutionOptionsTable {
    type Target = SoraMap<i32, DuEvolutionOptions>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for DuEvolutionOptionsTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for DuEvolutionOptionsTable {
    type Key = i32;
    type Row = DuEvolutionOptions;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
