// This file was generated by Sora. Do not edit manually.

#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum DuEvolutionOptionKind {
    Evolve = 0,
    RandomCurios = 1,
    ChanceEvolution = 2,
    Sacrifice = 3,
}

impl super::runtime::SoraDecode for DuEvolutionOptionKind {
    fn decode(reader: &mut super::runtime::SoraReader<'_>) -> Result<Self, super::runtime::SoraReadError> {
        match reader.read_var_u32()? {
            0 => Ok(Self::Evolve),
            1 => Ok(Self::RandomCurios),
            2 => Ok(Self::ChanceEvolution),
            3 => Ok(Self::Sacrifice),
            value => Err(super::runtime::SoraReadError::new(format!("invalid enum id {} for DuEvolutionOptionKind", value))),
        }
    }
}
