// This file was generated by Sora. Do not edit manually.
use super::du_curio_footstep_policy::DuCurioFootstepPolicy;
use super::SoraMap;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct DuWeightedCurioFootsteps {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "stable_key")]
    pub stable_key: String,
    #[serde(rename = "weighted_curio_key")]
    pub weighted_curio_key: String,
    #[serde(rename = "maze_buff_id")]
    pub maze_buff_id: String,
    #[serde(rename = "character_paths")]
    pub character_paths: Vec<String>,
    #[serde(rename = "loss_parameter")]
    pub loss_parameter: i32,
    #[serde(rename = "loss_fraction")]
    pub loss_fraction: String,
    #[serde(rename = "damage_parameter")]
    pub damage_parameter: i32,
    #[serde(rename = "damage_per_stack")]
    pub damage_per_stack: String,
    #[serde(rename = "cap_parameter")]
    pub cap_parameter: i32,
    #[serde(rename = "maximum_stacks")]
    pub maximum_stacks: i32,
    #[serde(rename = "policy")]
    pub policy: DuCurioFootstepPolicy,
    #[serde(rename = "summary_en")]
    pub summary_en: String,
    #[serde(rename = "summary_zh_cn")]
    pub summary_zh_cn: String,
    #[serde(rename = "hp_policy_note")]
    pub hp_policy_note: String,
    #[serde(rename = "hp_replacement_condition")]
    pub hp_replacement_condition: String,
    #[serde(rename = "skill_policy_note")]
    pub skill_policy_note: String,
    #[serde(rename = "skill_replacement_condition")]
    pub skill_replacement_condition: String,
    #[serde(rename = "source_ids")]
    pub source_ids: Vec<i32>,
}

impl super::runtime::SoraDecode for DuWeightedCurioFootsteps {
    fn decode(reader: &mut super::runtime::SoraReader<'_>) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            stable_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            weighted_curio_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            maze_buff_id: <String as super::runtime::SoraDecode>::decode(reader)?,
            character_paths: { let len = reader.read_var_u32()? as usize; let mut values = Vec::with_capacity(len); for _ in 0..len { values.push(<String as super::runtime::SoraDecode>::decode(reader)?); } values },
            loss_parameter: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            loss_fraction: <String as super::runtime::SoraDecode>::decode(reader)?,
            damage_parameter: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            damage_per_stack: <String as super::runtime::SoraDecode>::decode(reader)?,
            cap_parameter: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            maximum_stacks: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            policy: <DuCurioFootstepPolicy as super::runtime::SoraDecode>::decode(reader)?,
            summary_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            hp_policy_note: <String as super::runtime::SoraDecode>::decode(reader)?,
            hp_replacement_condition: <String as super::runtime::SoraDecode>::decode(reader)?,
            skill_policy_note: <String as super::runtime::SoraDecode>::decode(reader)?,
            skill_replacement_condition: <String as super::runtime::SoraDecode>::decode(reader)?,
            source_ids: { let len = reader.read_var_u32()? as usize; let mut values = Vec::with_capacity(len); for _ in 0..len { values.push(<i32 as super::runtime::SoraDecode>::decode(reader)?); } values },
        })
    }
}

impl DuWeightedCurioFootsteps {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct DuWeightedCurioFootstepsTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, DuWeightedCurioFootsteps>,
    by_stable_key: SoraMap<String, i32>,
}

impl DuWeightedCurioFootstepsTable {
    pub const NAME: &'static str = "DuWeightedCurioFootsteps";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "DuWeightedCurioFootsteps",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[
            super::SoraIndexInfo {
                name: "by_stable_key",
                unique: true,
                fields: &["stable_key"],
            },
        ],
    };

    pub(super) fn from_rows(rows: Vec<DuWeightedCurioFootsteps>) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        let by_stable_key = super::build_unique_map_index(
            rows.iter(),
            |row| row.stable_key.clone(),
            |row| row.id,
        );
        let rows = super::decode_map_table(rows, |row| row.id);
        Ok(Self {
            keys,
            rows,
            by_stable_key,
        })
    }

    pub fn get(&self, key: &i32) -> Option<&DuWeightedCurioFootsteps> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &DuWeightedCurioFootsteps> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
    pub fn get_by_stable_key(&self, stable_key: &str) -> Option<&DuWeightedCurioFootsteps> {
        self.by_stable_key.get(stable_key).and_then(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for DuWeightedCurioFootstepsTable {
    type Target = SoraMap<i32, DuWeightedCurioFootsteps>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for DuWeightedCurioFootstepsTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for DuWeightedCurioFootstepsTable {
    type Key = i32;
    type Row = DuWeightedCurioFootsteps;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
