// This file was generated by Sora. Do not edit manually.
use super::SoraMap;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct DuWeightedCurioDeflagrationLevels {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "stable_key")]
    pub stable_key: String,
    #[serde(rename = "weighted_curio_key")]
    pub weighted_curio_key: String,
    #[serde(rename = "hard_level_group")]
    pub hard_level_group: i32,
    #[serde(rename = "unit_level")]
    pub unit_level: i32,
    #[serde(rename = "hp_ratio")]
    pub hp_ratio: String,
    #[serde(rename = "source_ids")]
    pub source_ids: Vec<i32>,
}

impl super::runtime::SoraDecode for DuWeightedCurioDeflagrationLevels {
    fn decode(reader: &mut super::runtime::SoraReader<'_>) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            stable_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            weighted_curio_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            hard_level_group: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            unit_level: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            hp_ratio: <String as super::runtime::SoraDecode>::decode(reader)?,
            source_ids: { let len = reader.read_var_u32()? as usize; let mut values = Vec::with_capacity(len); for _ in 0..len { values.push(<i32 as super::runtime::SoraDecode>::decode(reader)?); } values },
        })
    }
}

impl DuWeightedCurioDeflagrationLevels {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct DuWeightedCurioDeflagrationLevelsTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, DuWeightedCurioDeflagrationLevels>,
    by_stable_key: SoraMap<String, i32>,
}

impl DuWeightedCurioDeflagrationLevelsTable {
    pub const NAME: &'static str = "DuWeightedCurioDeflagrationLevels";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "DuWeightedCurioDeflagrationLevels",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[
            super::SoraIndexInfo {
                name: "by_stable_key",
                unique: true,
                fields: &["stable_key"],
            },
        ],
    };

    pub(super) fn from_rows(rows: Vec<DuWeightedCurioDeflagrationLevels>) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        let by_stable_key = super::build_unique_map_index(
            rows.iter(),
            |row| row.stable_key.clone(),
            |row| row.id,
        );
        let rows = super::decode_map_table(rows, |row| row.id);
        Ok(Self {
            keys,
            rows,
            by_stable_key,
        })
    }

    pub fn get(&self, key: &i32) -> Option<&DuWeightedCurioDeflagrationLevels> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &DuWeightedCurioDeflagrationLevels> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
    pub fn get_by_stable_key(&self, stable_key: &str) -> Option<&DuWeightedCurioDeflagrationLevels> {
        self.by_stable_key.get(stable_key).and_then(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for DuWeightedCurioDeflagrationLevelsTable {
    type Target = SoraMap<i32, DuWeightedCurioDeflagrationLevels>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for DuWeightedCurioDeflagrationLevelsTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for DuWeightedCurioDeflagrationLevelsTable {
    type Key = i32;
    type Row = DuWeightedCurioDeflagrationLevels;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
