// This file was generated by Sora. Do not edit manually.

#![allow(dead_code)]

pub mod runtime;
pub mod du_curio_domain_grant_policy;
pub mod du_curio_battle_reaction_policy;
pub mod du_curio_battle_stat;
pub mod du_curio_battle_stat_policy;
pub mod du_curio_domain_expiry_policy;
pub mod du_decision_evidence;
pub mod du_decision_binding;
pub mod du_decision_sampling;
pub mod du_decision_exhaustion;
pub mod du_decision_reward_kind;
pub mod du_curio_acquisition_kind;
pub mod du_curio_acquisition_policy;
pub mod du_curio_fragment_gain_policy;
pub mod du_battle_blessing_policy;
pub mod du_curio_battle_weight_policy;
pub mod du_equation_grant_policy;
pub mod du_initial_equation_policy;
pub mod du_initial_equation_category;
pub mod du_battle_route_policy;
pub mod du_encounter_pool_policy;
pub mod du_curio_battle_grant_policy;
pub mod du_curio_evolution_policy;
pub mod du_evolution_event_policy;
pub mod du_evolution_option_kind;
pub mod du_battle_reward_domain;
pub mod du_victory_blessing_policy;
pub mod du_domain_choice_policy;
pub mod du_battle_fragment_policy;
pub mod du_tawot_service_policy;
pub mod du_expansion_reward_policy;
pub mod du_domain_slot_kind;
pub mod du_decision_sources;
pub mod du_decision_policies;
pub mod du_decision_occurrences;
pub mod du_decision_choices;
pub mod du_decision_outcomes;
pub mod du_curio_acquisitions;
pub mod du_curio_fragment_gains;
pub mod du_battle_blessings;
pub mod du_curio_battle_weights;
pub mod du_equation_grants;
pub mod du_initial_equations;
pub mod du_battle_routes;
pub mod du_encounter_pools;
pub mod du_curio_battle_grants;
pub mod du_curio_evolutions;
pub mod du_evolution_events;
pub mod du_evolution_options;
pub mod du_curio_victory_blessings;
pub mod du_domain_choices;
pub mod du_battle_fragments;
pub mod du_curio_domain_expiries;
pub mod du_curio_battle_stats;
pub mod du_curio_battle_reactions;
pub mod du_tawot_services;
pub mod du_curio_domain_grants;
pub mod du_equation_expansion_rewards;
pub mod du_domain_layout;
pub type SoraMap<K, V> = std::collections::HashMap<K, V>;

pub const SCHEMA_FINGERPRINT: &str = "82306a311516b0f5";

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SoraTableShape {
    List,
    Keyed,
    Singleton,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SoraKeyInfo {
    pub name: &'static str,
    pub ty: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SoraIndexInfo {
    pub name: &'static str,
    pub unique: bool,
    pub fields: &'static [&'static str],
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SoraTableInfo {
    pub name: &'static str,
    pub row_type: &'static str,
    pub shape: SoraTableShape,
    pub primary_key: Option<SoraKeyInfo>,
    pub indexes: &'static [SoraIndexInfo],
}

pub trait ErasedSoraTable: std::any::Any + Send + Sync {
    fn info(&self) -> &'static SoraTableInfo;
    fn len(&self) -> usize;

    fn is_empty(&self) -> bool {
        self.len() == 0
    }
}

pub trait SoraKeyedTable: ErasedSoraTable {
    type Key: std::cmp::Eq + std::hash::Hash + 'static;
    type Row: 'static;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row>;
    fn keys(&self) -> &[Self::Key];
}

pub trait SoraListTable: ErasedSoraTable {
    type Row: 'static;

    fn as_slice(&self) -> &[Self::Row];
}

pub trait SoraSingleTable: ErasedSoraTable {
    type Row: 'static;

    fn get(&self) -> &Self::Row;
}

pub struct SoraConfig {
    tables: SoraMap<&'static str, Box<dyn ErasedSoraTable>>,
}

impl std::fmt::Debug for SoraConfig {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let mut tables = self.tables.keys().copied().collect::<Vec<_>>();
        tables.sort_unstable();
        f.debug_struct("SoraConfig").field("tables", &tables).finish()
    }
}

impl SoraConfig {
    pub fn from_source(source: &impl runtime::SoraTableSource) -> Result<Self, runtime::SoraReadError> {
        let schema_fingerprint = source.schema_fingerprint()?;
        if schema_fingerprint != SCHEMA_FINGERPRINT {
            return Err(runtime::SoraReadError::new(format!(
                "schema fingerprint mismatch: generated code expects {}, bundle contains {}",
                SCHEMA_FINGERPRINT,
                schema_fingerprint
            )));
        }
        let mut tables: SoraMap<&'static str, Box<dyn ErasedSoraTable>> =
            sora_map_with_capacity(27);
        tables.insert(du_decision_sources::DuDecisionSourcesTable::NAME, Box::new(du_decision_sources::DuDecisionSourcesTable::from_rows(source.decode_table::<du_decision_sources::DuDecisionSources>(du_decision_sources::DuDecisionSourcesTable::NAME)?)?));
        tables.insert(du_decision_policies::DuDecisionPoliciesTable::NAME, Box::new(du_decision_policies::DuDecisionPoliciesTable::from_rows(source.decode_table::<du_decision_policies::DuDecisionPolicies>(du_decision_policies::DuDecisionPoliciesTable::NAME)?)?));
        tables.insert(du_decision_occurrences::DuDecisionOccurrencesTable::NAME, Box::new(du_decision_occurrences::DuDecisionOccurrencesTable::from_rows(source.decode_table::<du_decision_occurrences::DuDecisionOccurrences>(du_decision_occurrences::DuDecisionOccurrencesTable::NAME)?)?));
        tables.insert(du_decision_choices::DuDecisionChoicesTable::NAME, Box::new(du_decision_choices::DuDecisionChoicesTable::from_rows(source.decode_table::<du_decision_choices::DuDecisionChoices>(du_decision_choices::DuDecisionChoicesTable::NAME)?)?));
        tables.insert(du_decision_outcomes::DuDecisionOutcomesTable::NAME, Box::new(du_decision_outcomes::DuDecisionOutcomesTable::from_rows(source.decode_table::<du_decision_outcomes::DuDecisionOutcomes>(du_decision_outcomes::DuDecisionOutcomesTable::NAME)?)?));
        tables.insert(du_curio_acquisitions::DuCurioAcquisitionsTable::NAME, Box::new(du_curio_acquisitions::DuCurioAcquisitionsTable::from_rows(source.decode_table::<du_curio_acquisitions::DuCurioAcquisitions>(du_curio_acquisitions::DuCurioAcquisitionsTable::NAME)?)?));
        tables.insert(du_curio_fragment_gains::DuCurioFragmentGainsTable::NAME, Box::new(du_curio_fragment_gains::DuCurioFragmentGainsTable::from_rows(source.decode_table::<du_curio_fragment_gains::DuCurioFragmentGains>(du_curio_fragment_gains::DuCurioFragmentGainsTable::NAME)?)?));
        tables.insert(du_battle_blessings::DuBattleBlessingsTable::NAME, Box::new(du_battle_blessings::DuBattleBlessingsTable::from_rows(source.decode_table::<du_battle_blessings::DuBattleBlessings>(du_battle_blessings::DuBattleBlessingsTable::NAME)?)?));
        tables.insert(du_curio_battle_weights::DuCurioBattleWeightsTable::NAME, Box::new(du_curio_battle_weights::DuCurioBattleWeightsTable::from_rows(source.decode_table::<du_curio_battle_weights::DuCurioBattleWeights>(du_curio_battle_weights::DuCurioBattleWeightsTable::NAME)?)?));
        tables.insert(du_equation_grants::DuEquationGrantsTable::NAME, Box::new(du_equation_grants::DuEquationGrantsTable::from_rows(source.decode_table::<du_equation_grants::DuEquationGrants>(du_equation_grants::DuEquationGrantsTable::NAME)?)?));
        tables.insert(du_initial_equations::DuInitialEquationsTable::NAME, Box::new(du_initial_equations::DuInitialEquationsTable::from_rows(source.decode_table::<du_initial_equations::DuInitialEquations>(du_initial_equations::DuInitialEquationsTable::NAME)?)?));
        tables.insert(du_battle_routes::DuBattleRoutesTable::NAME, Box::new(du_battle_routes::DuBattleRoutesTable::from_rows(source.decode_table::<du_battle_routes::DuBattleRoutes>(du_battle_routes::DuBattleRoutesTable::NAME)?)?));
        tables.insert(du_encounter_pools::DuEncounterPoolsTable::NAME, Box::new(du_encounter_pools::DuEncounterPoolsTable::from_rows(source.decode_table::<du_encounter_pools::DuEncounterPools>(du_encounter_pools::DuEncounterPoolsTable::NAME)?)?));
        tables.insert(du_curio_battle_grants::DuCurioBattleGrantsTable::NAME, Box::new(du_curio_battle_grants::DuCurioBattleGrantsTable::from_rows(source.decode_table::<du_curio_battle_grants::DuCurioBattleGrants>(du_curio_battle_grants::DuCurioBattleGrantsTable::NAME)?)?));
        tables.insert(du_curio_evolutions::DuCurioEvolutionsTable::NAME, Box::new(du_curio_evolutions::DuCurioEvolutionsTable::from_rows(source.decode_table::<du_curio_evolutions::DuCurioEvolutions>(du_curio_evolutions::DuCurioEvolutionsTable::NAME)?)?));
        tables.insert(du_evolution_events::DuEvolutionEventsTable::NAME, Box::new(du_evolution_events::DuEvolutionEventsTable::from_rows(source.decode_table::<du_evolution_events::DuEvolutionEvents>(du_evolution_events::DuEvolutionEventsTable::NAME)?)?));
        tables.insert(du_evolution_options::DuEvolutionOptionsTable::NAME, Box::new(du_evolution_options::DuEvolutionOptionsTable::from_rows(source.decode_table::<du_evolution_options::DuEvolutionOptions>(du_evolution_options::DuEvolutionOptionsTable::NAME)?)?));
        tables.insert(du_curio_victory_blessings::DuCurioVictoryBlessingsTable::NAME, Box::new(du_curio_victory_blessings::DuCurioVictoryBlessingsTable::from_rows(source.decode_table::<du_curio_victory_blessings::DuCurioVictoryBlessings>(du_curio_victory_blessings::DuCurioVictoryBlessingsTable::NAME)?)?));
        tables.insert(du_domain_choices::DuDomainChoicesTable::NAME, Box::new(du_domain_choices::DuDomainChoicesTable::from_rows(source.decode_table::<du_domain_choices::DuDomainChoices>(du_domain_choices::DuDomainChoicesTable::NAME)?)?));
        tables.insert(du_battle_fragments::DuBattleFragmentsTable::NAME, Box::new(du_battle_fragments::DuBattleFragmentsTable::from_rows(source.decode_table::<du_battle_fragments::DuBattleFragments>(du_battle_fragments::DuBattleFragmentsTable::NAME)?)?));
        tables.insert(du_curio_domain_expiries::DuCurioDomainExpiriesTable::NAME, Box::new(du_curio_domain_expiries::DuCurioDomainExpiriesTable::from_rows(source.decode_table::<du_curio_domain_expiries::DuCurioDomainExpiries>(du_curio_domain_expiries::DuCurioDomainExpiriesTable::NAME)?)?));
        tables.insert(du_curio_battle_stats::DuCurioBattleStatsTable::NAME, Box::new(du_curio_battle_stats::DuCurioBattleStatsTable::from_rows(source.decode_table::<du_curio_battle_stats::DuCurioBattleStats>(du_curio_battle_stats::DuCurioBattleStatsTable::NAME)?)?));
        tables.insert(du_curio_battle_reactions::DuCurioBattleReactionsTable::NAME, Box::new(du_curio_battle_reactions::DuCurioBattleReactionsTable::from_rows(source.decode_table::<du_curio_battle_reactions::DuCurioBattleReactions>(du_curio_battle_reactions::DuCurioBattleReactionsTable::NAME)?)?));
        tables.insert(du_tawot_services::DuTawotServicesTable::NAME, Box::new(du_tawot_services::DuTawotServicesTable::from_rows(source.decode_table::<du_tawot_services::DuTawotServices>(du_tawot_services::DuTawotServicesTable::NAME)?)?));
        tables.insert(du_curio_domain_grants::DuCurioDomainGrantsTable::NAME, Box::new(du_curio_domain_grants::DuCurioDomainGrantsTable::from_rows(source.decode_table::<du_curio_domain_grants::DuCurioDomainGrants>(du_curio_domain_grants::DuCurioDomainGrantsTable::NAME)?)?));
        tables.insert(du_equation_expansion_rewards::DuEquationExpansionRewardsTable::NAME, Box::new(du_equation_expansion_rewards::DuEquationExpansionRewardsTable::from_rows(source.decode_table::<du_equation_expansion_rewards::DuEquationExpansionRewards>(du_equation_expansion_rewards::DuEquationExpansionRewardsTable::NAME)?)?));
        tables.insert(du_domain_layout::DuDomainLayoutTable::NAME, Box::new(du_domain_layout::DuDomainLayoutTable::from_rows(source.decode_table::<du_domain_layout::DuDomainLayout>(du_domain_layout::DuDomainLayoutTable::NAME)?)?));
        Ok(Self { tables })
    }

    fn table<T: ErasedSoraTable + 'static>(&self, name: &'static str) -> &T {
        self.tables
            .get(name)
            .and_then(|table| {
                let table: &dyn std::any::Any = table.as_ref();
                table.downcast_ref::<T>()
            })
            .unwrap_or_else(|| {
                panic!(
                    "generated SoraConfig is missing table `{}` or has an unexpected table type",
                    name
                )
            })
    }

    pub fn tables(&self) -> impl Iterator<Item = &dyn ErasedSoraTable> {
        self.tables.values().map(Box::as_ref)
    }

    pub fn du_decision_sources(&self) -> &du_decision_sources::DuDecisionSourcesTable {
        self.table(du_decision_sources::DuDecisionSourcesTable::NAME)
    }

    pub fn du_decision_policies(&self) -> &du_decision_policies::DuDecisionPoliciesTable {
        self.table(du_decision_policies::DuDecisionPoliciesTable::NAME)
    }

    pub fn du_decision_occurrences(&self) -> &du_decision_occurrences::DuDecisionOccurrencesTable {
        self.table(du_decision_occurrences::DuDecisionOccurrencesTable::NAME)
    }

    pub fn du_decision_choices(&self) -> &du_decision_choices::DuDecisionChoicesTable {
        self.table(du_decision_choices::DuDecisionChoicesTable::NAME)
    }

    pub fn du_decision_outcomes(&self) -> &du_decision_outcomes::DuDecisionOutcomesTable {
        self.table(du_decision_outcomes::DuDecisionOutcomesTable::NAME)
    }

    pub fn du_curio_acquisitions(&self) -> &du_curio_acquisitions::DuCurioAcquisitionsTable {
        self.table(du_curio_acquisitions::DuCurioAcquisitionsTable::NAME)
    }

    pub fn du_curio_fragment_gains(&self) -> &du_curio_fragment_gains::DuCurioFragmentGainsTable {
        self.table(du_curio_fragment_gains::DuCurioFragmentGainsTable::NAME)
    }

    pub fn du_battle_blessings(&self) -> &du_battle_blessings::DuBattleBlessingsTable {
        self.table(du_battle_blessings::DuBattleBlessingsTable::NAME)
    }

    pub fn du_curio_battle_weights(&self) -> &du_curio_battle_weights::DuCurioBattleWeightsTable {
        self.table(du_curio_battle_weights::DuCurioBattleWeightsTable::NAME)
    }

    pub fn du_equation_grants(&self) -> &du_equation_grants::DuEquationGrantsTable {
        self.table(du_equation_grants::DuEquationGrantsTable::NAME)
    }

    pub fn du_initial_equations(&self) -> &du_initial_equations::DuInitialEquationsTable {
        self.table(du_initial_equations::DuInitialEquationsTable::NAME)
    }

    pub fn du_battle_routes(&self) -> &du_battle_routes::DuBattleRoutesTable {
        self.table(du_battle_routes::DuBattleRoutesTable::NAME)
    }

    pub fn du_encounter_pools(&self) -> &du_encounter_pools::DuEncounterPoolsTable {
        self.table(du_encounter_pools::DuEncounterPoolsTable::NAME)
    }

    pub fn du_curio_battle_grants(&self) -> &du_curio_battle_grants::DuCurioBattleGrantsTable {
        self.table(du_curio_battle_grants::DuCurioBattleGrantsTable::NAME)
    }

    pub fn du_curio_evolutions(&self) -> &du_curio_evolutions::DuCurioEvolutionsTable {
        self.table(du_curio_evolutions::DuCurioEvolutionsTable::NAME)
    }

    pub fn du_evolution_events(&self) -> &du_evolution_events::DuEvolutionEventsTable {
        self.table(du_evolution_events::DuEvolutionEventsTable::NAME)
    }

    pub fn du_evolution_options(&self) -> &du_evolution_options::DuEvolutionOptionsTable {
        self.table(du_evolution_options::DuEvolutionOptionsTable::NAME)
    }

    pub fn du_curio_victory_blessings(&self) -> &du_curio_victory_blessings::DuCurioVictoryBlessingsTable {
        self.table(du_curio_victory_blessings::DuCurioVictoryBlessingsTable::NAME)
    }

    pub fn du_domain_choices(&self) -> &du_domain_choices::DuDomainChoicesTable {
        self.table(du_domain_choices::DuDomainChoicesTable::NAME)
    }

    pub fn du_battle_fragments(&self) -> &du_battle_fragments::DuBattleFragmentsTable {
        self.table(du_battle_fragments::DuBattleFragmentsTable::NAME)
    }

    pub fn du_curio_domain_expiries(&self) -> &du_curio_domain_expiries::DuCurioDomainExpiriesTable {
        self.table(du_curio_domain_expiries::DuCurioDomainExpiriesTable::NAME)
    }

    pub fn du_curio_battle_stats(&self) -> &du_curio_battle_stats::DuCurioBattleStatsTable {
        self.table(du_curio_battle_stats::DuCurioBattleStatsTable::NAME)
    }

    pub fn du_curio_battle_reactions(&self) -> &du_curio_battle_reactions::DuCurioBattleReactionsTable {
        self.table(du_curio_battle_reactions::DuCurioBattleReactionsTable::NAME)
    }

    pub fn du_tawot_services(&self) -> &du_tawot_services::DuTawotServicesTable {
        self.table(du_tawot_services::DuTawotServicesTable::NAME)
    }

    pub fn du_curio_domain_grants(&self) -> &du_curio_domain_grants::DuCurioDomainGrantsTable {
        self.table(du_curio_domain_grants::DuCurioDomainGrantsTable::NAME)
    }

    pub fn du_equation_expansion_rewards(&self) -> &du_equation_expansion_rewards::DuEquationExpansionRewardsTable {
        self.table(du_equation_expansion_rewards::DuEquationExpansionRewardsTable::NAME)
    }

    pub fn du_domain_layout(&self) -> &du_domain_layout::DuDomainLayoutTable {
        self.table(du_domain_layout::DuDomainLayoutTable::NAME)
    }
}

fn sora_map_with_capacity<K, V>(capacity: usize) -> SoraMap<K, V>
where
    K: std::cmp::Eq + std::hash::Hash,
{
    SoraMap::with_capacity(capacity)
}

fn decode_map_table<K, V>(rows: Vec<V>, key: impl Fn(&V) -> K) -> SoraMap<K, V>
where
    K: std::cmp::Eq + std::hash::Hash,
{
    rows.into_iter().map(|row| (key(&row), row)).collect()
}

fn build_unique_list_index<'a, K, V: 'a>(
    rows: impl Iterator<Item = &'a V>,
    key: impl Fn(&V) -> K,
) -> SoraMap<K, usize>
where
    K: std::cmp::Eq + std::hash::Hash,
{
    let mut index = sora_map_with_capacity(rows.size_hint().0);
    for (position, row) in rows.enumerate() {
        index.insert(key(row), position);
    }
    index
}

fn build_unique_map_index<'a, K, P, V: 'a>(
    rows: impl Iterator<Item = &'a V>,
    key: impl Fn(&V) -> K,
    primary_key: impl Fn(&V) -> P,
) -> SoraMap<K, P>
where
    K: std::cmp::Eq + std::hash::Hash,
    P: std::cmp::Eq + std::hash::Hash,
{
    let mut index = sora_map_with_capacity(rows.size_hint().0);
    for row in rows {
        index.insert(key(row), primary_key(row));
    }
    index
}
