// This file was generated by Sora. Do not edit manually.

#![allow(dead_code)]

pub mod canonical_decimal_fixture;
pub mod confidence;
pub mod config_manifest;
pub mod content_evidence_binding;
pub mod content_identity;
pub mod content_kind;
pub mod coverage_state;
pub mod evidence_kind;
pub mod evidence_record;
pub mod fact_quality;
pub mod mechanism_quality;
pub mod release_state;
pub mod runtime;
pub mod source_category;
pub mod source_record;
pub type SoraMap<K, V> = std::collections::HashMap<K, V>;

pub const SCHEMA_FINGERPRINT: &str = "69f55e0b5cfaaaed";

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SoraTableShape {
    List,
    Keyed,
    Singleton,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SoraKeyInfo {
    pub name: &'static str,
    pub ty: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SoraIndexInfo {
    pub name: &'static str,
    pub unique: bool,
    pub fields: &'static [&'static str],
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SoraTableInfo {
    pub name: &'static str,
    pub row_type: &'static str,
    pub shape: SoraTableShape,
    pub primary_key: Option<SoraKeyInfo>,
    pub indexes: &'static [SoraIndexInfo],
}

pub trait ErasedSoraTable: std::any::Any + Send + Sync {
    fn info(&self) -> &'static SoraTableInfo;
    fn len(&self) -> usize;

    fn is_empty(&self) -> bool {
        self.len() == 0
    }
}

pub trait SoraKeyedTable: ErasedSoraTable {
    type Key: std::cmp::Eq + std::hash::Hash + 'static;
    type Row: 'static;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row>;
    fn keys(&self) -> &[Self::Key];
}

pub trait SoraListTable: ErasedSoraTable {
    type Row: 'static;

    fn as_slice(&self) -> &[Self::Row];
}

pub trait SoraSingleTable: ErasedSoraTable {
    type Row: 'static;

    fn get(&self) -> &Self::Row;
}

pub struct SoraConfig {
    tables: SoraMap<&'static str, Box<dyn ErasedSoraTable>>,
}

impl std::fmt::Debug for SoraConfig {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let mut tables = self.tables.keys().copied().collect::<Vec<_>>();
        tables.sort_unstable();
        f.debug_struct("SoraConfig")
            .field("tables", &tables)
            .finish()
    }
}

impl SoraConfig {
    pub fn from_source(
        source: &impl runtime::SoraTableSource,
    ) -> Result<Self, runtime::SoraReadError> {
        let schema_fingerprint = source.schema_fingerprint()?;
        if schema_fingerprint != SCHEMA_FINGERPRINT {
            return Err(runtime::SoraReadError::new(format!(
                "schema fingerprint mismatch: generated code expects {}, bundle contains {}",
                SCHEMA_FINGERPRINT, schema_fingerprint
            )));
        }
        let mut tables: SoraMap<&'static str, Box<dyn ErasedSoraTable>> = sora_map_with_capacity(6);
        tables.insert(
            source_record::SourceRecordTable::NAME,
            Box::new(source_record::SourceRecordTable::from_rows(
                source.decode_table::<source_record::SourceRecord>(
                    source_record::SourceRecordTable::NAME,
                )?,
            )?),
        );
        tables.insert(
            evidence_record::EvidenceRecordTable::NAME,
            Box::new(evidence_record::EvidenceRecordTable::from_rows(
                source.decode_table::<evidence_record::EvidenceRecord>(
                    evidence_record::EvidenceRecordTable::NAME,
                )?,
            )?),
        );
        tables.insert(
            content_identity::ContentIdentityTable::NAME,
            Box::new(content_identity::ContentIdentityTable::from_rows(
                source.decode_table::<content_identity::ContentIdentity>(
                    content_identity::ContentIdentityTable::NAME,
                )?,
            )?),
        );
        tables.insert(
            content_evidence_binding::ContentEvidenceBindingTable::NAME,
            Box::new(
                content_evidence_binding::ContentEvidenceBindingTable::from_rows(
                    source.decode_table::<content_evidence_binding::ContentEvidenceBinding>(
                        content_evidence_binding::ContentEvidenceBindingTable::NAME,
                    )?,
                )?,
            ),
        );
        tables.insert(
            config_manifest::ConfigManifestTable::NAME,
            Box::new(config_manifest::ConfigManifestTable::from_rows(
                source.decode_table::<config_manifest::ConfigManifest>(
                    config_manifest::ConfigManifestTable::NAME,
                )?,
            )?),
        );
        tables.insert(
            canonical_decimal_fixture::CanonicalDecimalFixtureTable::NAME,
            Box::new(
                canonical_decimal_fixture::CanonicalDecimalFixtureTable::from_rows(
                    source.decode_table::<canonical_decimal_fixture::CanonicalDecimalFixture>(
                        canonical_decimal_fixture::CanonicalDecimalFixtureTable::NAME,
                    )?,
                )?,
            ),
        );
        Ok(Self { tables })
    }

    fn table<T: ErasedSoraTable + 'static>(&self, name: &'static str) -> &T {
        self.tables
            .get(name)
            .and_then(|table| {
                let table: &dyn std::any::Any = table.as_ref();
                table.downcast_ref::<T>()
            })
            .unwrap_or_else(|| {
                panic!(
                    "generated SoraConfig is missing table `{}` or has an unexpected table type",
                    name
                )
            })
    }

    pub fn tables(&self) -> impl Iterator<Item = &dyn ErasedSoraTable> {
        self.tables.values().map(Box::as_ref)
    }

    pub fn source_record(&self) -> &source_record::SourceRecordTable {
        self.table(source_record::SourceRecordTable::NAME)
    }

    pub fn evidence_record(&self) -> &evidence_record::EvidenceRecordTable {
        self.table(evidence_record::EvidenceRecordTable::NAME)
    }

    pub fn content_identity(&self) -> &content_identity::ContentIdentityTable {
        self.table(content_identity::ContentIdentityTable::NAME)
    }

    pub fn content_evidence_binding(
        &self,
    ) -> &content_evidence_binding::ContentEvidenceBindingTable {
        self.table(content_evidence_binding::ContentEvidenceBindingTable::NAME)
    }

    pub fn config_manifest(&self) -> &config_manifest::ConfigManifestTable {
        self.table(config_manifest::ConfigManifestTable::NAME)
    }

    pub fn canonical_decimal_fixture(
        &self,
    ) -> &canonical_decimal_fixture::CanonicalDecimalFixtureTable {
        self.table(canonical_decimal_fixture::CanonicalDecimalFixtureTable::NAME)
    }
}

fn sora_map_with_capacity<K, V>(capacity: usize) -> SoraMap<K, V>
where
    K: std::cmp::Eq + std::hash::Hash,
{
    SoraMap::with_capacity(capacity)
}

fn decode_map_table<K, V>(rows: Vec<V>, key: impl Fn(&V) -> K) -> SoraMap<K, V>
where
    K: std::cmp::Eq + std::hash::Hash,
{
    rows.into_iter().map(|row| (key(&row), row)).collect()
}

fn build_unique_list_index<'a, K, V: 'a>(
    rows: impl Iterator<Item = &'a V>,
    key: impl Fn(&V) -> K,
) -> SoraMap<K, usize>
where
    K: std::cmp::Eq + std::hash::Hash,
{
    let mut index = sora_map_with_capacity(rows.size_hint().0);
    for (position, row) in rows.enumerate() {
        index.insert(key(row), position);
    }
    index
}

fn build_unique_map_index<'a, K, P, V: 'a>(
    rows: impl Iterator<Item = &'a V>,
    key: impl Fn(&V) -> K,
    primary_key: impl Fn(&V) -> P,
) -> SoraMap<K, P>
where
    K: std::cmp::Eq + std::hash::Hash,
    P: std::cmp::Eq + std::hash::Hash,
{
    let mut index = sora_map_with_capacity(rows.size_hint().0);
    for row in rows {
        index.insert(key(row), primary_key(row));
    }
    index
}

fn decode_singleton_table<T>(mut rows: Vec<T>, name: &str) -> Result<T, runtime::SoraReadError> {
    if rows.len() != 1 {
        return Err(runtime::SoraReadError::new(format!(
            "expected singleton table `{}` to contain exactly 1 row, got {}",
            name,
            rows.len()
        )));
    }

    Ok(rows.remove(0))
}
