// This file was generated by Sora. Do not edit manually.
use super::du_coverage_state::DuCoverageState;
use super::du_evidence_quality::DuEvidenceQuality;
use super::du_ownership::DuOwnership;
use super::SoraMap;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct DivergentUniverseModules {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "stable_key")]
    pub stable_key: String,
    #[serde(rename = "schema_revision")]
    pub schema_revision: String,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "name_en")]
    pub name_en: String,
    #[serde(rename = "name_zh_cn")]
    pub name_zh_cn: String,
    #[serde(rename = "summary_en")]
    pub summary_en: String,
    #[serde(rename = "summary_zh_cn")]
    pub summary_zh_cn: String,
    #[serde(rename = "ownership")]
    pub ownership: DUOwnership,
    #[serde(rename = "coverage_state")]
    pub coverage_state: DUCoverageState,
    #[serde(rename = "evidence_quality")]
    pub evidence_quality: DUEvidenceQuality,
    #[serde(rename = "source_refs")]
    pub source_refs: Option<Vec<i32>>,
    #[serde(rename = "tags")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "source_id")]
    pub source_id: Option<String>,
    #[serde(rename = "sub_mode")]
    pub sub_mode: Option<String>,
    #[serde(rename = "tourn_mode")]
    pub tourn_mode: Option<String>,
    #[serde(rename = "main_tourn_id")]
    pub main_tourn_id: Option<String>,
    #[serde(rename = "sub_tourn_id")]
    pub sub_tourn_id: Option<String>,
    #[serde(rename = "payload_json")]
    pub payload_json: String,
}

impl super::runtime::SoraDecode for DivergentUniverseModules {
    fn decode(reader: &mut super::runtime::SoraReader<'_>) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            stable_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            schema_revision: <String as super::runtime::SoraDecode>::decode(reader)?,
            kind: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            ownership: <DUOwnership as super::runtime::SoraDecode>::decode(reader)?,
            coverage_state: <DUCoverageState as super::runtime::SoraDecode>::decode(reader)?,
            evidence_quality: <DUEvidenceQuality as super::runtime::SoraDecode>::decode(reader)?,
            source_refs: <Option<Vec<i32>> as super::runtime::SoraDecode>::decode(reader)?,
            tags: <Option<Vec<String>> as super::runtime::SoraDecode>::decode(reader)?,
            source_id: <Option<String> as super::runtime::SoraDecode>::decode(reader)?,
            sub_mode: <Option<String> as super::runtime::SoraDecode>::decode(reader)?,
            tourn_mode: <Option<String> as super::runtime::SoraDecode>::decode(reader)?,
            main_tourn_id: <Option<String> as super::runtime::SoraDecode>::decode(reader)?,
            sub_tourn_id: <Option<String> as super::runtime::SoraDecode>::decode(reader)?,
            payload_json: <String as super::runtime::SoraDecode>::decode(reader)?,
        })
    }
}

impl DivergentUniverseModules {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct DivergentUniverseModulesTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, DivergentUniverseModules>,
    by_stable_key: SoraMap<String, i32>,
}

impl DivergentUniverseModulesTable {
    pub const NAME: &'static str = "DivergentUniverseModules";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "DivergentUniverseModules",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[
            super::SoraIndexInfo {
                name: "by_stable_key",
                unique: true,
                fields: &["stable_key"],
            },
        ],
    };

    pub(super) fn from_rows(rows: Vec<DivergentUniverseModules>) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        let by_stable_key = super::build_unique_map_index(
            rows.iter(),
            |row| row.stable_key.clone(),
            |row| row.id,
        );
        let rows = super::decode_map_table(rows, |row| row.id);
        Ok(Self {
            keys,
            rows,
            by_stable_key,
        })
    }

    pub fn get(&self, key: &i32) -> Option<&DivergentUniverseModules> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &DivergentUniverseModules> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
    pub fn get_by_stable_key(&self, stable_key: &str) -> Option<&DivergentUniverseModules> {
        self.by_stable_key.get(stable_key).and_then(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for DivergentUniverseModulesTable {
    type Target = SoraMap<i32, DivergentUniverseModules>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for DivergentUniverseModulesTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for DivergentUniverseModulesTable {
    type Key = i32;
    type Row = DivergentUniverseModules;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
