// This file was generated by Sora. Do not edit manually.
use super::du_coverage_state::DuCoverageState;
use super::du_evidence_quality::DuEvidenceQuality;
use super::du_ownership::DuOwnership;
use super::SoraMap;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct DivergentUniverseEquationRecipes {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "stable_key")]
    pub stable_key: String,
    #[serde(rename = "schema_revision")]
    pub schema_revision: String,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "name_en")]
    pub name_en: String,
    #[serde(rename = "name_zh_cn")]
    pub name_zh_cn: String,
    #[serde(rename = "summary_en")]
    pub summary_en: String,
    #[serde(rename = "summary_zh_cn")]
    pub summary_zh_cn: String,
    #[serde(rename = "ownership")]
    pub ownership: DuOwnership,
    #[serde(rename = "coverage_state")]
    pub coverage_state: DuCoverageState,
    #[serde(rename = "evidence_quality")]
    pub evidence_quality: DuEvidenceQuality,
    #[serde(rename = "source_refs")]
    pub source_refs: Option<Vec<i32>>,
    #[serde(rename = "tags")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "source_id")]
    pub source_id: Option<String>,
    #[serde(rename = "equation_id")]
    pub equation_id: Option<i32>,
    #[serde(rename = "main_path_count")]
    pub main_path_count: Option<String>,
    #[serde(rename = "sub_path_count")]
    pub sub_path_count: Option<String>,
    #[serde(rename = "required_blessing_states")]
    pub required_blessing_states: Option<String>,
    #[serde(rename = "payload_json")]
    pub payload_json: String,
}

impl super::runtime::SoraDecode for DivergentUniverseEquationRecipes {
    fn decode(reader: &mut super::runtime::SoraReader<'_>) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            stable_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            schema_revision: <String as super::runtime::SoraDecode>::decode(reader)?,
            kind: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            ownership: <DuOwnership as super::runtime::SoraDecode>::decode(reader)?,
            coverage_state: <DuCoverageState as super::runtime::SoraDecode>::decode(reader)?,
            evidence_quality: <DuEvidenceQuality as super::runtime::SoraDecode>::decode(reader)?,
            source_refs: <Option<Vec<i32>> as super::runtime::SoraDecode>::decode(reader)?,
            tags: <Option<Vec<String>> as super::runtime::SoraDecode>::decode(reader)?,
            source_id: <Option<String> as super::runtime::SoraDecode>::decode(reader)?,
            equation_id: <Option<i32> as super::runtime::SoraDecode>::decode(reader)?,
            main_path_count: <Option<String> as super::runtime::SoraDecode>::decode(reader)?,
            sub_path_count: <Option<String> as super::runtime::SoraDecode>::decode(reader)?,
            required_blessing_states: <Option<String> as super::runtime::SoraDecode>::decode(reader)?,
            payload_json: <String as super::runtime::SoraDecode>::decode(reader)?,
        })
    }
}

impl DivergentUniverseEquationRecipes {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct DivergentUniverseEquationRecipesTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, DivergentUniverseEquationRecipes>,
    by_stable_key: SoraMap<String, i32>,
}

impl DivergentUniverseEquationRecipesTable {
    pub const NAME: &'static str = "DivergentUniverseEquationRecipes";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "DivergentUniverseEquationRecipes",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[
            super::SoraIndexInfo {
                name: "by_stable_key",
                unique: true,
                fields: &["stable_key"],
            },
        ],
    };

    pub(super) fn from_rows(rows: Vec<DivergentUniverseEquationRecipes>) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        let by_stable_key = super::build_unique_map_index(
            rows.iter(),
            |row| row.stable_key.clone(),
            |row| row.id,
        );
        let rows = super::decode_map_table(rows, |row| row.id);
        Ok(Self {
            keys,
            rows,
            by_stable_key,
        })
    }

    pub fn get(&self, key: &i32) -> Option<&DivergentUniverseEquationRecipes> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &DivergentUniverseEquationRecipes> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
    pub fn get_by_stable_key(&self, stable_key: &str) -> Option<&DivergentUniverseEquationRecipes> {
        self.by_stable_key.get(stable_key).and_then(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for DivergentUniverseEquationRecipesTable {
    type Target = SoraMap<i32, DivergentUniverseEquationRecipes>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for DivergentUniverseEquationRecipesTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for DivergentUniverseEquationRecipesTable {
    type Key = i32;
    type Row = DivergentUniverseEquationRecipes;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
