// This file was generated by Sora. Do not edit manually.

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum PfCoverageState {
    DataReady,
    ResearchGap,
    Excluded,
}

impl super::runtime::SoraDecode for PfCoverageState {
    fn decode(reader: &mut super::runtime::SoraReader<'_>) -> Result<Self, super::runtime::SoraReadError> {
        match reader.read_var_u32()? {
            0 => Ok(Self::DataReady),
            1 => Ok(Self::ResearchGap),
            2 => Ok(Self::Excluded),
            value => Err(super::runtime::SoraReadError::new(format!("invalid enum ordinal {} for PfCoverageState", value))),
        }
    }
}
