// This file was generated by Sora. Do not edit manually.

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum FateRuntimeCardOwner {
    Trailblazer,
    Gilgamesh,
    Archer,
    Saber,
    Rin,
    Neutral,
}

impl super::runtime::SoraDecode for FateRuntimeCardOwner {
    fn decode(
        reader: &mut super::runtime::SoraReader<'_>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        match reader.read_var_u32()? {
            0 => Ok(Self::Trailblazer),
            1 => Ok(Self::Gilgamesh),
            2 => Ok(Self::Archer),
            3 => Ok(Self::Saber),
            4 => Ok(Self::Rin),
            5 => Ok(Self::Neutral),
            value => Err(super::runtime::SoraReadError::new(format!(
                "invalid enum ordinal {} for FateRuntimeCardOwner",
                value
            ))),
        }
    }
}
