// This file was generated by Sora. Do not edit manually.
use super::SoraMap;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct FateRuntimeStoryFights {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "battle_event_id")]
    pub battle_event_id: i32,
    #[serde(rename = "map_entrance_id")]
    pub map_entrance_id: i32,
    #[serde(rename = "source_ref")]
    pub source_ref: String,
}

impl super::runtime::SoraDecode for FateRuntimeStoryFights {
    fn decode(
        reader: &mut super::runtime::SoraReader<'_>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            battle_event_id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            map_entrance_id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            source_ref: <String as super::runtime::SoraDecode>::decode(reader)?,
        })
    }
}

impl FateRuntimeStoryFights {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct FateRuntimeStoryFightsTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, FateRuntimeStoryFights>,
}

impl FateRuntimeStoryFightsTable {
    pub const NAME: &'static str = "FateRuntimeStoryFights";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "FateRuntimeStoryFights",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[],
    };

    pub(super) fn from_rows(
        rows: Vec<FateRuntimeStoryFights>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        Ok(Self {
            keys,
            rows: super::decode_map_table(rows, |row| row.id),
        })
    }

    pub fn get(&self, key: &i32) -> Option<&FateRuntimeStoryFights> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &FateRuntimeStoryFights> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for FateRuntimeStoryFightsTable {
    type Target = SoraMap<i32, FateRuntimeStoryFights>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for FateRuntimeStoryFightsTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for FateRuntimeStoryFightsTable {
    type Key = i32;
    type Row = FateRuntimeStoryFights;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
