// This file was generated by Sora. Do not edit manually.

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum FateRuntimeBoardNodeKind {
    Choice,
    Battle,
    Completed,
}

impl super::runtime::SoraDecode for FateRuntimeBoardNodeKind {
    fn decode(
        reader: &mut super::runtime::SoraReader<'_>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        match reader.read_var_u32()? {
            0 => Ok(Self::Choice),
            1 => Ok(Self::Battle),
            2 => Ok(Self::Completed),
            value => Err(super::runtime::SoraReadError::new(format!(
                "invalid enum ordinal {} for FateRuntimeBoardNodeKind",
                value
            ))),
        }
    }
}
