// This file was generated by Sora. Do not edit manually.

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum GbRuntimeInputKind {
    Equipment,
    AnyStandardWeapon,
}

impl super::runtime::SoraDecode for GbRuntimeInputKind {
    fn decode(
        reader: &mut super::runtime::SoraReader<'_>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        match reader.read_var_u32()? {
            0 => Ok(Self::Equipment),
            1 => Ok(Self::AnyStandardWeapon),
            value => Err(super::runtime::SoraReadError::new(format!(
                "invalid enum ordinal {} for GbRuntimeInputKind",
                value
            ))),
        }
    }
}
