// This file was generated by Sora. Do not edit manually.
use super::SoraMap;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GbRuntimeTeamBonuses {
    #[serde(rename = "stage_id")]
    pub stage_id: i32,
    #[serde(rename = "profile_id")]
    pub profile_id: i32,
    #[serde(rename = "maze_buff_id")]
    pub maze_buff_id: i32,
    #[serde(rename = "level")]
    pub level: i32,
    #[serde(rename = "parameters")]
    pub parameters: Vec<String>,
    #[serde(rename = "ability_binding")]
    pub ability_binding: String,
    #[serde(rename = "runtime_binding_exact")]
    pub runtime_binding_exact: bool,
    #[serde(rename = "source_ref")]
    pub source_ref: String,
}

impl super::runtime::SoraDecode for GbRuntimeTeamBonuses {
    fn decode(
        reader: &mut super::runtime::SoraReader<'_>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            stage_id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            profile_id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            maze_buff_id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            level: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            parameters: <Vec<String> as super::runtime::SoraDecode>::decode(reader)?,
            ability_binding: <String as super::runtime::SoraDecode>::decode(reader)?,
            runtime_binding_exact: <bool as super::runtime::SoraDecode>::decode(reader)?,
            source_ref: <String as super::runtime::SoraDecode>::decode(reader)?,
        })
    }
}

impl GbRuntimeTeamBonuses {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct GbRuntimeTeamBonusesTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, GbRuntimeTeamBonuses>,
}

impl GbRuntimeTeamBonusesTable {
    pub const NAME: &'static str = "GbRuntimeTeamBonuses";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "GbRuntimeTeamBonuses",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "stage_id",
            ty: "i32",
        }),
        indexes: &[],
    };

    pub(super) fn from_rows(
        rows: Vec<GbRuntimeTeamBonuses>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.stage_id).collect::<Vec<_>>();
        Ok(Self {
            keys,
            rows: super::decode_map_table(rows, |row| row.stage_id),
        })
    }

    pub fn get(&self, key: &i32) -> Option<&GbRuntimeTeamBonuses> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &GbRuntimeTeamBonuses> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for GbRuntimeTeamBonusesTable {
    type Target = SoraMap<i32, GbRuntimeTeamBonuses>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for GbRuntimeTeamBonusesTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for GbRuntimeTeamBonusesTable {
    type Key = i32;
    type Row = GbRuntimeTeamBonuses;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
