// This file was generated by Sora. Do not edit manually.
use super::SoraMap;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GbRuntimeRecipes {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "profile_id")]
    pub profile_id: i32,
    #[serde(rename = "stable_key")]
    pub stable_key: String,
    #[serde(rename = "output_equipment_id")]
    pub output_equipment_id: i32,
    #[serde(rename = "tier")]
    pub tier: String,
    #[serde(rename = "source_ref")]
    pub source_ref: String,
}

impl super::runtime::SoraDecode for GbRuntimeRecipes {
    fn decode(
        reader: &mut super::runtime::SoraReader<'_>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            profile_id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            stable_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            output_equipment_id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            tier: <String as super::runtime::SoraDecode>::decode(reader)?,
            source_ref: <String as super::runtime::SoraDecode>::decode(reader)?,
        })
    }
}

impl GbRuntimeRecipes {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct GbRuntimeRecipesTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, GbRuntimeRecipes>,
}

impl GbRuntimeRecipesTable {
    pub const NAME: &'static str = "GbRuntimeRecipes";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "GbRuntimeRecipes",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[],
    };

    pub(super) fn from_rows(
        rows: Vec<GbRuntimeRecipes>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        Ok(Self {
            keys,
            rows: super::decode_map_table(rows, |row| row.id),
        })
    }

    pub fn get(&self, key: &i32) -> Option<&GbRuntimeRecipes> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &GbRuntimeRecipes> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for GbRuntimeRecipesTable {
    type Target = SoraMap<i32, GbRuntimeRecipes>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for GbRuntimeRecipesTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for GbRuntimeRecipesTable {
    type Key = i32;
    type Row = GbRuntimeRecipes;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
