
[[rows]]
character_id = 37
level = 80
promotion = 6
hp_decimal = "1000"
atk_decimal = "650"
def_decimal = "450"
spd_decimal = "105"

[[rows]]
character_id = 38
level = 80
promotion = 6
hp_decimal = "1100"
atk_decimal = "600"
def_decimal = "500"
spd_decimal = "102"

[[rows]]
character_id = 39
level = 80
promotion = 6
hp_decimal = "1200"
atk_decimal = "550"
def_decimal = "550"
spd_decimal = "98"
