
[[rows]]
character_id = 37
sequence = 1
slot = "Basic"
ability_id = 2
invested_level_cap = 6

[[rows]]
character_id = 38
sequence = 1
slot = "Basic"
ability_id = 2
invested_level_cap = 6

[[rows]]
character_id = 39
sequence = 1
slot = "Basic"
ability_id = 2
invested_level_cap = 6
