
[[rows]]
id = 37
rarity = 4
path = "Hunt"
element = "Physical"
base_energy_decimal = "100"
base_aggro_decimal = "75"

[[rows]]
id = 38
rarity = 4
path = "Nihility"
element = "Lightning"
base_energy_decimal = "110"
base_aggro_decimal = "100"

[[rows]]
id = 39
rarity = 4
path = "Abundance"
element = "Imaginary"
base_energy_decimal = "120"
base_aggro_decimal = "100"
