[[rows]]
variant_id = 26
level = 80
difficulty_key = "standard"
hp_decimal = "100000"
atk_decimal = "700"
def_decimal = "600"
spd_decimal = "100"
effect_resistance_decimal = "0.2"
crit_damage_decimal = "0.5"

[[rows]]
variant_id = 40
level = 80
difficulty_key = "standard"
hp_decimal = "10000"
atk_decimal = "350"
def_decimal = "300"
spd_decimal = "90"
effect_resistance_decimal = "0"
crit_damage_decimal = "0.5"
