// This file was generated by Sora. Do not edit manually.
use super::SoraMap;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct CurrencyWarsEconomyRules {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "stable_key")]
    pub stable_key: String,
    #[serde(rename = "schema_revision")]
    pub schema_revision: String,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "name_en")]
    pub name_en: String,
    #[serde(rename = "name_zh_cn")]
    pub name_zh_cn: String,
    #[serde(rename = "summary_en")]
    pub summary_en: String,
    #[serde(rename = "summary_zh_cn")]
    pub summary_zh_cn: String,
    #[serde(rename = "ownership")]
    pub ownership: String,
    #[serde(rename = "coverage_state")]
    pub coverage_state: String,
    #[serde(rename = "evidence_quality")]
    pub evidence_quality: String,
    #[serde(rename = "source_refs_json")]
    pub source_refs_json: String,
    #[serde(rename = "tags_json")]
    pub tags_json: String,
    #[serde(rename = "currency_ids")]
    pub currency_ids: Option<String>,
    #[serde(rename = "experience_rules")]
    pub experience_rules: Option<String>,
    #[serde(rename = "refresh_rules")]
    pub refresh_rules: Option<String>,
    #[serde(rename = "team_size_rules")]
    pub team_size_rules: Option<String>,
}

impl super::runtime::SoraDecode for CurrencyWarsEconomyRules {
    fn decode(reader: &mut super::runtime::SoraReader<'_>) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            stable_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            schema_revision: <String as super::runtime::SoraDecode>::decode(reader)?,
            kind: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            ownership: <String as super::runtime::SoraDecode>::decode(reader)?,
            coverage_state: <String as super::runtime::SoraDecode>::decode(reader)?,
            evidence_quality: <String as super::runtime::SoraDecode>::decode(reader)?,
            source_refs_json: <String as super::runtime::SoraDecode>::decode(reader)?,
            tags_json: <String as super::runtime::SoraDecode>::decode(reader)?,
            currency_ids: <Option<String> as super::runtime::SoraDecode>::decode(reader)?,
            experience_rules: <Option<String> as super::runtime::SoraDecode>::decode(reader)?,
            refresh_rules: <Option<String> as super::runtime::SoraDecode>::decode(reader)?,
            team_size_rules: <Option<String> as super::runtime::SoraDecode>::decode(reader)?,
        })
    }
}

impl CurrencyWarsEconomyRules {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct CurrencyWarsEconomyRulesTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, CurrencyWarsEconomyRules>,
    by_stable_key: SoraMap<String, i32>,
}

impl CurrencyWarsEconomyRulesTable {
    pub const NAME: &'static str = "CurrencyWarsEconomyRules";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "CurrencyWarsEconomyRules",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[
            super::SoraIndexInfo {
                name: "by_stable_key",
                unique: true,
                fields: &["stable_key"],
            },
        ],
    };

    pub(super) fn from_rows(rows: Vec<CurrencyWarsEconomyRules>) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        let by_stable_key = super::build_unique_map_index(
            rows.iter(),
            |row| row.stable_key.clone(),
            |row| row.id,
        );
        let rows = super::decode_map_table(rows, |row| row.id);
        Ok(Self {
            keys,
            rows,
            by_stable_key,
        })
    }

    pub fn get(&self, key: &i32) -> Option<&CurrencyWarsEconomyRules> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &CurrencyWarsEconomyRules> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
    pub fn get_by_stable_key(&self, stable_key: &str) -> Option<&CurrencyWarsEconomyRules> {
        self.by_stable_key.get(stable_key).and_then(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for CurrencyWarsEconomyRulesTable {
    type Target = SoraMap<i32, CurrencyWarsEconomyRules>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for CurrencyWarsEconomyRulesTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for CurrencyWarsEconomyRulesTable {
    type Key = i32;
    type Row = CurrencyWarsEconomyRules;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
