// This file was generated by Sora. Do not edit manually.
use super::SoraMap;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct CurrencyWarsStarStates {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "stable_key")]
    pub stable_key: String,
    #[serde(rename = "schema_revision")]
    pub schema_revision: String,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "name_en")]
    pub name_en: String,
    #[serde(rename = "name_zh_cn")]
    pub name_zh_cn: String,
    #[serde(rename = "summary_en")]
    pub summary_en: String,
    #[serde(rename = "summary_zh_cn")]
    pub summary_zh_cn: String,
    #[serde(rename = "ownership")]
    pub ownership: String,
    #[serde(rename = "coverage_state")]
    pub coverage_state: String,
    #[serde(rename = "evidence_quality")]
    pub evidence_quality: String,
    #[serde(rename = "source_refs_json")]
    pub source_refs_json: String,
    #[serde(rename = "tags_json")]
    pub tags_json: String,
    #[serde(rename = "avatar_id")]
    pub avatar_id: Option<String>,
    #[serde(rename = "star_level")]
    pub star_level: Option<String>,
    #[serde(rename = "copy_count")]
    pub copy_count: Option<String>,
    #[serde(rename = "scaling_refs")]
    pub scaling_refs: Option<String>,
    #[serde(rename = "rank_attachments")]
    pub rank_attachments: Option<String>,
    #[serde(rename = "battle_event_id")]
    pub battle_event_id: Option<String>,
    #[serde(rename = "skill_override_source_ids")]
    pub skill_override_source_ids: Option<String>,
    #[serde(rename = "skill_override_destination_ids")]
    pub skill_override_destination_ids: Option<String>,
    #[serde(rename = "front_skill_ids")]
    pub front_skill_ids: Option<String>,
    #[serde(rename = "back_execution_skill_ids")]
    pub back_execution_skill_ids: Option<String>,
    #[serde(rename = "back_skill_ids")]
    pub back_skill_ids: Option<String>,
    #[serde(rename = "back_ability_name")]
    pub back_ability_name: Option<String>,
    #[serde(rename = "config_path")]
    pub config_path: Option<String>,
    #[serde(rename = "ai_path")]
    pub ai_path: Option<String>,
    #[serde(rename = "property_modifiers")]
    pub property_modifiers: Option<String>,
    #[serde(rename = "servant_id")]
    pub servant_id: Option<String>,
    #[serde(rename = "front_power_base")]
    pub front_power_base: Option<String>,
    #[serde(rename = "back_power_base")]
    pub back_power_base: Option<String>,
    #[serde(rename = "luck_chance")]
    pub luck_chance: Option<String>,
    #[serde(rename = "luck_damage")]
    pub luck_damage: Option<String>,
    #[serde(rename = "extra_heal_base")]
    pub extra_heal_base: Option<String>,
    #[serde(rename = "extra_shield_base")]
    pub extra_shield_base: Option<String>,
    #[serde(rename = "hp_base")]
    pub hp_base: Option<String>,
    #[serde(rename = "hp_inherit")]
    pub hp_inherit: Option<String>,
    #[serde(rename = "hp_skill_id")]
    pub hp_skill_id: Option<String>,
    #[serde(rename = "speed_base")]
    pub speed_base: Option<String>,
    #[serde(rename = "speed_inherit")]
    pub speed_inherit: Option<String>,
    #[serde(rename = "speed_skill_id")]
    pub speed_skill_id: Option<String>,
}

impl super::runtime::SoraDecode for CurrencyWarsStarStates {
    fn decode(reader: &mut super::runtime::SoraReader<'_>) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            stable_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            schema_revision: <String as super::runtime::SoraDecode>::decode(reader)?,
            kind: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            ownership: <String as super::runtime::SoraDecode>::decode(reader)?,
            coverage_state: <String as super::runtime::SoraDecode>::decode(reader)?,
            evidence_quality: <String as super::runtime::SoraDecode>::decode(reader)?,
            source_refs_json: <String as super::runtime::SoraDecode>::decode(reader)?,
            tags_json: <String as super::runtime::SoraDecode>::decode(reader)?,
            avatar_id: match reader.read_u8()? { 0 => None, 1 => Some(<String as super::runtime::SoraDecode>::decode(reader)?), value => return Err(super::runtime::SoraReadError::new(format!("invalid option presence {}", value))), },
            star_level: match reader.read_u8()? { 0 => None, 1 => Some(<String as super::runtime::SoraDecode>::decode(reader)?), value => return Err(super::runtime::SoraReadError::new(format!("invalid option presence {}", value))), },
            copy_count: match reader.read_u8()? { 0 => None, 1 => Some(<String as super::runtime::SoraDecode>::decode(reader)?), value => return Err(super::runtime::SoraReadError::new(format!("invalid option presence {}", value))), },
            scaling_refs: match reader.read_u8()? { 0 => None, 1 => Some(<String as super::runtime::SoraDecode>::decode(reader)?), value => return Err(super::runtime::SoraReadError::new(format!("invalid option presence {}", value))), },
            rank_attachments: match reader.read_u8()? { 0 => None, 1 => Some(<String as super::runtime::SoraDecode>::decode(reader)?), value => return Err(super::runtime::SoraReadError::new(format!("invalid option presence {}", value))), },
            battle_event_id: match reader.read_u8()? { 0 => None, 1 => Some(<String as super::runtime::SoraDecode>::decode(reader)?), value => return Err(super::runtime::SoraReadError::new(format!("invalid option presence {}", value))), },
            skill_override_source_ids: match reader.read_u8()? { 0 => None, 1 => Some(<String as super::runtime::SoraDecode>::decode(reader)?), value => return Err(super::runtime::SoraReadError::new(format!("invalid option presence {}", value))), },
            skill_override_destination_ids: match reader.read_u8()? { 0 => None, 1 => Some(<String as super::runtime::SoraDecode>::decode(reader)?), value => return Err(super::runtime::SoraReadError::new(format!("invalid option presence {}", value))), },
            front_skill_ids: match reader.read_u8()? { 0 => None, 1 => Some(<String as super::runtime::SoraDecode>::decode(reader)?), value => return Err(super::runtime::SoraReadError::new(format!("invalid option presence {}", value))), },
            back_execution_skill_ids: match reader.read_u8()? { 0 => None, 1 => Some(<String as super::runtime::SoraDecode>::decode(reader)?), value => return Err(super::runtime::SoraReadError::new(format!("invalid option presence {}", value))), },
            back_skill_ids: match reader.read_u8()? { 0 => None, 1 => Some(<String as super::runtime::SoraDecode>::decode(reader)?), value => return Err(super::runtime::SoraReadError::new(format!("invalid option presence {}", value))), },
            back_ability_name: match reader.read_u8()? { 0 => None, 1 => Some(<String as super::runtime::SoraDecode>::decode(reader)?), value => return Err(super::runtime::SoraReadError::new(format!("invalid option presence {}", value))), },
            config_path: match reader.read_u8()? { 0 => None, 1 => Some(<String as super::runtime::SoraDecode>::decode(reader)?), value => return Err(super::runtime::SoraReadError::new(format!("invalid option presence {}", value))), },
            ai_path: match reader.read_u8()? { 0 => None, 1 => Some(<String as super::runtime::SoraDecode>::decode(reader)?), value => return Err(super::runtime::SoraReadError::new(format!("invalid option presence {}", value))), },
            property_modifiers: match reader.read_u8()? { 0 => None, 1 => Some(<String as super::runtime::SoraDecode>::decode(reader)?), value => return Err(super::runtime::SoraReadError::new(format!("invalid option presence {}", value))), },
            servant_id: match reader.read_u8()? { 0 => None, 1 => Some(<String as super::runtime::SoraDecode>::decode(reader)?), value => return Err(super::runtime::SoraReadError::new(format!("invalid option presence {}", value))), },
            front_power_base: match reader.read_u8()? { 0 => None, 1 => Some(<String as super::runtime::SoraDecode>::decode(reader)?), value => return Err(super::runtime::SoraReadError::new(format!("invalid option presence {}", value))), },
            back_power_base: match reader.read_u8()? { 0 => None, 1 => Some(<String as super::runtime::SoraDecode>::decode(reader)?), value => return Err(super::runtime::SoraReadError::new(format!("invalid option presence {}", value))), },
            luck_chance: match reader.read_u8()? { 0 => None, 1 => Some(<String as super::runtime::SoraDecode>::decode(reader)?), value => return Err(super::runtime::SoraReadError::new(format!("invalid option presence {}", value))), },
            luck_damage: match reader.read_u8()? { 0 => None, 1 => Some(<String as super::runtime::SoraDecode>::decode(reader)?), value => return Err(super::runtime::SoraReadError::new(format!("invalid option presence {}", value))), },
            extra_heal_base: match reader.read_u8()? { 0 => None, 1 => Some(<String as super::runtime::SoraDecode>::decode(reader)?), value => return Err(super::runtime::SoraReadError::new(format!("invalid option presence {}", value))), },
            extra_shield_base: match reader.read_u8()? { 0 => None, 1 => Some(<String as super::runtime::SoraDecode>::decode(reader)?), value => return Err(super::runtime::SoraReadError::new(format!("invalid option presence {}", value))), },
            hp_base: match reader.read_u8()? { 0 => None, 1 => Some(<String as super::runtime::SoraDecode>::decode(reader)?), value => return Err(super::runtime::SoraReadError::new(format!("invalid option presence {}", value))), },
            hp_inherit: match reader.read_u8()? { 0 => None, 1 => Some(<String as super::runtime::SoraDecode>::decode(reader)?), value => return Err(super::runtime::SoraReadError::new(format!("invalid option presence {}", value))), },
            hp_skill_id: match reader.read_u8()? { 0 => None, 1 => Some(<String as super::runtime::SoraDecode>::decode(reader)?), value => return Err(super::runtime::SoraReadError::new(format!("invalid option presence {}", value))), },
            speed_base: match reader.read_u8()? { 0 => None, 1 => Some(<String as super::runtime::SoraDecode>::decode(reader)?), value => return Err(super::runtime::SoraReadError::new(format!("invalid option presence {}", value))), },
            speed_inherit: match reader.read_u8()? { 0 => None, 1 => Some(<String as super::runtime::SoraDecode>::decode(reader)?), value => return Err(super::runtime::SoraReadError::new(format!("invalid option presence {}", value))), },
            speed_skill_id: match reader.read_u8()? { 0 => None, 1 => Some(<String as super::runtime::SoraDecode>::decode(reader)?), value => return Err(super::runtime::SoraReadError::new(format!("invalid option presence {}", value))), },
        })
    }
}

impl CurrencyWarsStarStates {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct CurrencyWarsStarStatesTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, CurrencyWarsStarStates>,
    by_stable_key: SoraMap<String, i32>,
}

impl CurrencyWarsStarStatesTable {
    pub const NAME: &'static str = "CurrencyWarsStarStates";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "CurrencyWarsStarStates",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[
            super::SoraIndexInfo {
                name: "by_stable_key",
                unique: true,
                fields: &["stable_key"],
            },
        ],
    };

    pub(super) fn from_rows(rows: Vec<CurrencyWarsStarStates>) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        let by_stable_key = super::build_unique_map_index(
            rows.iter(),
            |row| row.stable_key.clone(),
            |row| row.id,
        );
        let rows = super::decode_map_table(rows, |row| row.id);
        Ok(Self {
            keys,
            rows,
            by_stable_key,
        })
    }

    pub fn get(&self, key: &i32) -> Option<&CurrencyWarsStarStates> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &CurrencyWarsStarStates> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
    pub fn get_by_stable_key(&self, stable_key: &str) -> Option<&CurrencyWarsStarStates> {
        self.by_stable_key.get(stable_key).and_then(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for CurrencyWarsStarStatesTable {
    type Target = SoraMap<i32, CurrencyWarsStarStates>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for CurrencyWarsStarStatesTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for CurrencyWarsStarStatesTable {
    type Key = i32;
    type Row = CurrencyWarsStarStates;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
