// This file was generated by Sora. Do not edit manually.
use super::SoraMap;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct FsnOwners {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "stable_key")]
    pub stable_key: String,
    #[serde(rename = "family")]
    pub family: String,
    #[serde(rename = "name_zh")]
    pub name_zh: String,
    #[serde(rename = "name_en")]
    pub name_en: String,
    #[serde(rename = "summary_zh")]
    pub summary_zh: String,
    #[serde(rename = "summary_en")]
    pub summary_en: String,
    #[serde(rename = "ownership")]
    pub ownership: String,
    #[serde(rename = "disposition")]
    pub disposition: String,
    #[serde(rename = "enabled")]
    pub enabled: String,
    #[serde(rename = "source_refs_json")]
    pub source_refs_json: String,
    #[serde(rename = "evidence_quality")]
    pub evidence_quality: String,
    #[serde(rename = "mechanism_quality")]
    pub mechanism_quality: String,
    #[serde(rename = "confidence")]
    pub confidence: String,
    #[serde(rename = "text_hashes_json")]
    pub text_hashes_json: String,
    #[serde(rename = "mechanic_payload_json")]
    pub mechanic_payload_json: String,
    #[serde(rename = "notes")]
    pub notes: String,
}

impl super::runtime::SoraDecode for FsnOwners {
    fn decode(reader: &mut super::runtime::SoraReader<'_>) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            stable_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            family: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_zh: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_zh: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            ownership: <String as super::runtime::SoraDecode>::decode(reader)?,
            disposition: <String as super::runtime::SoraDecode>::decode(reader)?,
            enabled: <String as super::runtime::SoraDecode>::decode(reader)?,
            source_refs_json: <String as super::runtime::SoraDecode>::decode(reader)?,
            evidence_quality: <String as super::runtime::SoraDecode>::decode(reader)?,
            mechanism_quality: <String as super::runtime::SoraDecode>::decode(reader)?,
            confidence: <String as super::runtime::SoraDecode>::decode(reader)?,
            text_hashes_json: <String as super::runtime::SoraDecode>::decode(reader)?,
            mechanic_payload_json: <String as super::runtime::SoraDecode>::decode(reader)?,
            notes: <String as super::runtime::SoraDecode>::decode(reader)?,
        })
    }
}

impl FsnOwners {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct FsnOwnersTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, FsnOwners>,
    by_stable_key: SoraMap<String, i32>,
}

impl FsnOwnersTable {
    pub const NAME: &'static str = "FsnOwners";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "FsnOwners",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[
            super::SoraIndexInfo {
                name: "by_stable_key",
                unique: true,
                fields: &["stable_key"],
            },
        ],
    };

    pub(super) fn from_rows(rows: Vec<FsnOwners>) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        let by_stable_key = super::build_unique_map_index(
            rows.iter(),
            |row| row.stable_key.clone(),
            |row| row.id,
        );
        let rows = super::decode_map_table(rows, |row| row.id);
        Ok(Self {
            keys,
            rows,
            by_stable_key,
        })
    }

    pub fn get(&self, key: &i32) -> Option<&FsnOwners> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &FsnOwners> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
    pub fn get_by_stable_key(&self, stable_key: &str) -> Option<&FsnOwners> {
        self.by_stable_key.get(stable_key).and_then(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for FsnOwnersTable {
    type Target = SoraMap<i32, FsnOwners>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for FsnOwnersTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for FsnOwnersTable {
    type Key = i32;
    type Row = FsnOwners;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
