// This file was generated by Sora. Do not edit manually.

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum MocOwnership {
    MemoryOfChaos,
    Shared,
}

impl super::runtime::SoraDecode for MocOwnership {
    fn decode(reader: &mut super::runtime::SoraReader<'_>) -> Result<Self, super::runtime::SoraReadError> {
        match reader.read_var_u32()? {
            0 => Ok(Self::MemoryOfChaos),
            1 => Ok(Self::Shared),
            value => Err(super::runtime::SoraReadError::new(format!("invalid enum ordinal {} for MocOwnership", value))),
        }
    }
}
