//! Semantic rejection vectors for authored decision relationships and provenance.

use super::{EditedRows, expansion_policy, reward_policies};
use crate::{
    divergent_universe::load_divergent_universe_bundle,
    divergent_universe_decisions::{BUNDLE, DecisionDataError, validation::compile},
    divergent_universe_decisions_generated::{SoraConfig, runtime::SoraBundle},
};
use serde_json::Value;
use std::collections::BTreeMap;

#[test]
fn semantic_decision_validation_rejects_bad_joins_provenance_and_orphan_rows() {
    let reference = load_divergent_universe_bundle().unwrap();
    let bundle = SoraBundle::parse(BUNDLE).unwrap();
    let config = SoraConfig::from_source(&bundle).unwrap();
    let baseline = BTreeMap::from([
        expansion_policy::table(&config),
        reward_policies::battle_stats_table(&config),
        reward_policies::battle_reactions_table(&config),
        reward_policies::tawot_services_table(&config),
        reward_policies::domain_grants_table(&config),
        (
            "DuCurioDomainExpiries",
            serde_json::to_value(
                config
                    .du_curio_domain_expiries()
                    .ordered_rows()
                    .collect::<Vec<_>>(),
            )
            .unwrap(),
        ),
        (
            "DuBattleFragments",
            serde_json::to_value(
                config
                    .du_battle_fragments()
                    .ordered_rows()
                    .collect::<Vec<_>>(),
            )
            .unwrap(),
        ),
        (
            "DuEvolutionEvents",
            serde_json::to_value(
                config
                    .du_evolution_events()
                    .ordered_rows()
                    .collect::<Vec<_>>(),
            )
            .unwrap(),
        ),
        (
            "DuEvolutionOptions",
            serde_json::to_value(
                config
                    .du_evolution_options()
                    .ordered_rows()
                    .collect::<Vec<_>>(),
            )
            .unwrap(),
        ),
        (
            "DuCurioEvolutions",
            serde_json::to_value(
                config
                    .du_curio_evolutions()
                    .ordered_rows()
                    .collect::<Vec<_>>(),
            )
            .unwrap(),
        ),
        (
            "DuCurioBattleGrants",
            serde_json::to_value(
                config
                    .du_curio_battle_grants()
                    .ordered_rows()
                    .collect::<Vec<_>>(),
            )
            .unwrap(),
        ),
        (
            "DuEncounterPools",
            serde_json::to_value(
                config
                    .du_encounter_pools()
                    .ordered_rows()
                    .collect::<Vec<_>>(),
            )
            .unwrap(),
        ),
        (
            "DuDomainChoices",
            serde_json::to_value(
                config
                    .du_domain_choices()
                    .ordered_rows()
                    .collect::<Vec<_>>(),
            )
            .unwrap(),
        ),
        (
            "DuCurioVictoryBlessings",
            serde_json::to_value(
                config
                    .du_curio_victory_blessings()
                    .ordered_rows()
                    .collect::<Vec<_>>(),
            )
            .unwrap(),
        ),
        (
            "DuBattleRoutes",
            serde_json::to_value(config.du_battle_routes().ordered_rows().collect::<Vec<_>>())
                .unwrap(),
        ),
        (
            "DuInitialEquations",
            serde_json::to_value(
                config
                    .du_initial_equations()
                    .ordered_rows()
                    .collect::<Vec<_>>(),
            )
            .unwrap(),
        ),
        (
            "DuEquationGrants",
            serde_json::to_value(
                config
                    .du_equation_grants()
                    .ordered_rows()
                    .collect::<Vec<_>>(),
            )
            .unwrap(),
        ),
        (
            "DuCurioBattleWeights",
            serde_json::to_value(
                config
                    .du_curio_battle_weights()
                    .ordered_rows()
                    .collect::<Vec<_>>(),
            )
            .unwrap(),
        ),
        (
            "DuBattleBlessings",
            serde_json::to_value(
                config
                    .du_battle_blessings()
                    .ordered_rows()
                    .collect::<Vec<_>>(),
            )
            .unwrap(),
        ),
        (
            "DuCurioFragmentGains",
            serde_json::to_value(
                config
                    .du_curio_fragment_gains()
                    .ordered_rows()
                    .collect::<Vec<_>>(),
            )
            .unwrap(),
        ),
        (
            "DuCurioAcquisitions",
            serde_json::to_value(
                config
                    .du_curio_acquisitions()
                    .ordered_rows()
                    .collect::<Vec<_>>(),
            )
            .unwrap(),
        ),
        (
            "DuDecisionSources",
            serde_json::to_value(
                config
                    .du_decision_sources()
                    .ordered_rows()
                    .collect::<Vec<_>>(),
            )
            .unwrap(),
        ),
        (
            "DuDecisionPolicies",
            serde_json::to_value(
                config
                    .du_decision_policies()
                    .ordered_rows()
                    .collect::<Vec<_>>(),
            )
            .unwrap(),
        ),
        (
            "DuDecisionOccurrences",
            serde_json::to_value(
                config
                    .du_decision_occurrences()
                    .ordered_rows()
                    .collect::<Vec<_>>(),
            )
            .unwrap(),
        ),
        (
            "DuDecisionChoices",
            serde_json::to_value(
                config
                    .du_decision_choices()
                    .ordered_rows()
                    .collect::<Vec<_>>(),
            )
            .unwrap(),
        ),
        (
            "DuDecisionOutcomes",
            serde_json::to_value(
                config
                    .du_decision_outcomes()
                    .ordered_rows()
                    .collect::<Vec<_>>(),
            )
            .unwrap(),
        ),
    ]);
    let edits = [
        (
            "DuCurioVictoryBlessings",
            "count",
            Value::from(0),
            DecisionDataError::InvalidReward,
        ),
        (
            "DuCurioVictoryBlessings",
            "count",
            Value::from(2),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuCurioVictoryBlessings",
            "count_parameter",
            Value::from(0),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuCurioVictoryBlessings",
            "effect_id",
            Value::from("2194"),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuCurioVictoryBlessings",
            "minimum_rarity",
            Value::from(0),
            DecisionDataError::InvalidReward,
        ),
        (
            "DuCurioVictoryBlessings",
            "maximum_rarity",
            Value::from(4),
            DecisionDataError::InvalidReward,
        ),
        (
            "DuCurioVictoryBlessings",
            "domains",
            Value::from(Vec::<String>::new()),
            DecisionDataError::InvalidPolicy,
        ),
        (
            "DuCurioVictoryBlessings",
            "domains",
            Value::from(vec!["Elite", "Elite"]),
            DecisionDataError::InvalidPolicy,
        ),
        (
            "DuCurioVictoryBlessings",
            "policy_note",
            Value::from(""),
            DecisionDataError::InvalidPolicy,
        ),
        (
            "DuCurioVictoryBlessings",
            "source_ids",
            Value::from(vec![999]),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuEvolutionEvents",
            "layer_ordinal",
            Value::from(3),
            DecisionDataError::InvalidIdentity,
        ),
        (
            "DuEvolutionEvents",
            "evolution_id",
            Value::from(999),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuEvolutionEvents",
            "layer_ordinal",
            Value::from(1),
            DecisionDataError::InvalidPolicy,
        ),
        (
            "DuEvolutionEvents",
            "policy_note",
            Value::from(""),
            DecisionDataError::InvalidPolicy,
        ),
        (
            "DuEvolutionOptions",
            "event_id",
            Value::from(999),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuEvolutionOptions",
            "fragment_cost",
            Value::from(-1),
            DecisionDataError::InvalidReward,
        ),
        (
            "DuEvolutionOptions",
            "curio_count",
            Value::from(2),
            DecisionDataError::InvalidReward,
        ),
        (
            "DuEvolutionOptions",
            "success_denominator",
            Value::from(0),
            DecisionDataError::InvalidReward,
        ),
        (
            "DuEvolutionOptions",
            "source_ids",
            Value::from(vec![999]),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuCurioEvolutions",
            "from_state",
            Value::from("divergent-universe.curio-state.9197"),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuCurioEvolutions",
            "to_state",
            Value::from("divergent-universe.curio-state.9197"),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuCurioEvolutions",
            "owner",
            Value::from("divergent-universe.curio.9001"),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuCurioEvolutions",
            "occurrence",
            Value::from("divergent-universe.occurrence.0"),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuCurioEvolutions",
            "policy_note",
            Value::from(""),
            DecisionDataError::InvalidPolicy,
        ),
        (
            "DuCurioEvolutions",
            "source_ids",
            Value::from(vec![999]),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuCurioBattleGrants",
            "state_key",
            Value::from("divergent-universe.curio-state.9196"),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuCurioBattleGrants",
            "effect_id",
            Value::from("2196"),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuCurioBattleGrants",
            "amount_parameter",
            Value::from(1),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuCurioBattleGrants",
            "amount_per_full_hp",
            Value::from(16),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuCurioBattleGrants",
            "amount_per_full_hp",
            Value::from(0),
            DecisionDataError::InvalidReward,
        ),
        (
            "DuCurioBattleGrants",
            "policy_note",
            Value::from(""),
            DecisionDataError::InvalidPolicy,
        ),
        (
            "DuCurioBattleGrants",
            "source_ids",
            Value::from(vec![999]),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuEncounterPools",
            "encounter_group",
            Value::from("divergent-universe.encounter-group.0"),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuEncounterPools",
            "first_stage",
            Value::from("0"),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuEncounterPools",
            "candidate_stages",
            Value::from(vec!["0"]),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuEncounterPools",
            "candidate_stages",
            Value::from(Vec::<String>::new()),
            DecisionDataError::InvalidPolicy,
        ),
        (
            "DuEncounterPools",
            "candidate_stages",
            Value::from(vec!["83002081", "83002081"]),
            DecisionDataError::InvalidPolicy,
        ),
        (
            "DuEncounterPools",
            "candidate_stages",
            Value::from(vec!["83002111", "83002081"]),
            DecisionDataError::InvalidPolicy,
        ),
        (
            "DuEncounterPools",
            "policy_note",
            Value::from(""),
            DecisionDataError::InvalidPolicy,
        ),
        (
            "DuEncounterPools",
            "source_ids",
            Value::from(vec![999]),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuBattleRoutes",
            "battles_per_layer",
            Value::from(0),
            DecisionDataError::InvalidPolicy,
        ),
        (
            "DuBattleRoutes",
            "battles_per_layer",
            Value::from(2),
            DecisionDataError::InvalidPolicy,
        ),
        (
            "DuBattleRoutes",
            "policy_note",
            Value::from(""),
            DecisionDataError::InvalidPolicy,
        ),
        (
            "DuBattleRoutes",
            "source_ids",
            Value::from(vec![999]),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuInitialEquations",
            "offer_width",
            Value::from(0),
            DecisionDataError::InvalidPolicy,
        ),
        (
            "DuInitialEquations",
            "offer_width",
            Value::from(9),
            DecisionDataError::InvalidPolicy,
        ),
        (
            "DuInitialEquations",
            "policy_note",
            Value::from(""),
            DecisionDataError::InvalidPolicy,
        ),
        (
            "DuInitialEquations",
            "source_ids",
            Value::from(vec![999]),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuEquationGrants",
            "count",
            Value::from(2),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuEquationGrants",
            "count_parameter",
            Value::from(1),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuEquationGrants",
            "domain_limit",
            Value::from(2),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuEquationGrants",
            "effect_id",
            Value::from("2043"),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuEquationGrants",
            "source_ids",
            Value::from(vec![999]),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuCurioBattleWeights",
            "bonus_weight",
            Value::from(0),
            DecisionDataError::InvalidReward,
        ),
        (
            "DuCurioBattleWeights",
            "bonus_weight",
            Value::from(1_000_001),
            DecisionDataError::InvalidReward,
        ),
        (
            "DuCurioBattleWeights",
            "state_key",
            Value::from("divergent-universe.curio-state.9001"),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuCurioBattleWeights",
            "effect_id",
            Value::from("2044"),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuCurioBattleWeights",
            "path_type",
            Value::from("124"),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuCurioBattleWeights",
            "policy_note",
            Value::from(""),
            DecisionDataError::InvalidPolicy,
        ),
        (
            "DuCurioBattleWeights",
            "source_ids",
            Value::from(vec![999]),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuBattleBlessings",
            "offer_width",
            Value::from(0),
            DecisionDataError::InvalidReward,
        ),
        (
            "DuBattleBlessings",
            "maximum_rarity",
            Value::from(0),
            DecisionDataError::InvalidReward,
        ),
        (
            "DuBattleBlessings",
            "suppression_states",
            Value::from(vec!["divergent-universe.curio-state.9001"]),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuBattleBlessings",
            "suppression_effects",
            Value::from(vec!["2001"]),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuBattleBlessings",
            "source_ids",
            Value::from(vec![999]),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuBattleBlessings",
            "policy_note",
            Value::from(""),
            DecisionDataError::InvalidPolicy,
        ),
        (
            "DuBattleBlessings",
            "replacement_condition",
            Value::from(""),
            DecisionDataError::InvalidPolicy,
        ),
        (
            "DuCurioFragmentGains",
            "state_key",
            Value::from("divergent-universe.curio-state.9001"),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuCurioFragmentGains",
            "effect_id",
            Value::from("2079"),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuCurioFragmentGains",
            "bonus_fraction",
            Value::from("0.3"),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuCurioFragmentGains",
            "parameter_index",
            Value::from(0),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuCurioFragmentGains",
            "source_ids",
            Value::from(vec![999]),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuCurioFragmentGains",
            "replacement_condition",
            Value::from(""),
            DecisionDataError::InvalidPolicy,
        ),
        (
            "DuCurioAcquisitions",
            "state_key",
            Value::from("divergent-universe.curio-state.9001"),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuCurioAcquisitions",
            "effect_id",
            Value::from("2053"),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuCurioAcquisitions",
            "amount",
            Value::from("301"),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuCurioAcquisitions",
            "parameter_index",
            Value::from(0),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuCurioAcquisitions",
            "replacement_condition",
            Value::from(""),
            DecisionDataError::InvalidPolicy,
        ),
        (
            "DuCurioAcquisitions",
            "source_ids",
            Value::from(vec![999]),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuDecisionOccurrences",
            "reference_variant",
            Value::from("divergent-universe.occurrence-variant.700103"),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuDecisionChoices",
            "occurrence_id",
            Value::from(999),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuDecisionOutcomes",
            "choice_id",
            Value::from(999),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuDecisionOutcomes",
            "source_id",
            Value::from(999),
            DecisionDataError::InvalidReference,
        ),
        (
            "DuDecisionChoices",
            "ordinal",
            Value::from(2),
            DecisionDataError::InvalidOrder,
        ),
        (
            "DuDecisionChoices",
            "fragment_cost",
            Value::from(-1),
            DecisionDataError::InvalidReward,
        ),
        (
            "DuDecisionPolicies",
            "replacement_condition",
            Value::from(""),
            DecisionDataError::InvalidPolicy,
        ),
        (
            "DuDecisionSources",
            "sha256",
            Value::from("not-a-digest"),
            DecisionDataError::InvalidProvenance,
        ),
        (
            "DuDecisionPolicies",
            "source_ids",
            Value::from(vec![1, 1]),
            DecisionDataError::InvalidProvenance,
        ),
    ];
    reward_policies::validate(&baseline, &reference);
    expansion_policy::validate(&baseline, &reference);
    for (table, field, value, expected) in edits {
        let mut rows = EditedRows(baseline.clone());
        rows.0.get_mut(table).unwrap()[0][field] = value;
        let edited = SoraConfig::from_source(&rows).unwrap();
        assert_eq!(
            compile(&edited, &reference),
            Err(expected),
            "{table}.{field}"
        );
    }
    for (index, field, value, expected) in [
        (
            0,
            "minimum_rarity",
            Value::from(1),
            DecisionDataError::InvalidReward,
        ),
        (
            15,
            "minimum_rarity",
            Value::Null,
            DecisionDataError::InvalidReward,
        ),
        (
            15,
            "maximum_rarity",
            Value::Null,
            DecisionDataError::InvalidReward,
        ),
        (
            15,
            "minimum_rarity",
            Value::from(0),
            DecisionDataError::InvalidReward,
        ),
        (
            15,
            "minimum_rarity",
            Value::from(2),
            DecisionDataError::InvalidReward,
        ),
        (
            15,
            "maximum_rarity",
            Value::from(4),
            DecisionDataError::InvalidReward,
        ),
        (
            15,
            "path_types",
            serde_json::json!(["126"]),
            DecisionDataError::InvalidReward,
        ),
        (
            15,
            "amount",
            Value::from("2"),
            DecisionDataError::InvalidReference,
        ),
        (
            15,
            "policy",
            Value::from("StableStateOrderFloorBeforeEachGrant"),
            DecisionDataError::InvalidPolicy,
        ),
        (
            0,
            "path_types",
            serde_json::json!(["126"]),
            DecisionDataError::InvalidReward,
        ),
        (
            6,
            "path_types",
            Value::Null,
            DecisionDataError::InvalidReference,
        ),
        (
            6,
            "path_types",
            serde_json::json!([]),
            DecisionDataError::InvalidReference,
        ),
        (
            6,
            "path_types",
            serde_json::json!(["126", "126"]),
            DecisionDataError::InvalidReference,
        ),
        (
            6,
            "path_types",
            serde_json::json!(["123"]),
            DecisionDataError::InvalidReference,
        ),
        (
            6,
            "policy",
            Value::from("StableStateOrderFloorBeforeEachGrant"),
            DecisionDataError::InvalidPolicy,
        ),
    ] {
        let mut rows = EditedRows(baseline.clone());
        rows.0.get_mut("DuCurioAcquisitions").unwrap()[index][field] = value;
        let edited = SoraConfig::from_source(&rows).unwrap();
        assert_eq!(
            compile(&edited, &reference),
            Err(expected),
            "acquisition[{index}].{field}"
        );
    }
}
