// This file was generated by Sora. Do not edit manually.
use super::aa_coverage_state::AaCoverageState;
use super::aa_evidence_quality::AaEvidenceQuality;
use super::aa_mechanism_quality::AaMechanismQuality;
use super::aa_ownership::AaOwnership;
use super::SoraMap;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct AaEnemySlots {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "stable_key")]
    pub stable_key: String,
    #[serde(rename = "row_order")]
    pub row_order: i32,
    #[serde(rename = "name_en")]
    pub name_en: String,
    #[serde(rename = "name_zh_cn")]
    pub name_zh_cn: String,
    #[serde(rename = "summary_en")]
    pub summary_en: String,
    #[serde(rename = "summary_zh_cn")]
    pub summary_zh_cn: String,
    #[serde(rename = "ownership")]
    pub ownership: AAOwnership,
    #[serde(rename = "coverage_state")]
    pub coverage_state: AACoverageState,
    #[serde(rename = "evidence_quality")]
    pub evidence_quality: AAEvidenceQuality,
    #[serde(rename = "mechanism_quality")]
    pub mechanism_quality: AAMechanismQuality,
    #[serde(rename = "manifest_record_ids")]
    pub manifest_record_ids: Vec<String>,
    #[serde(rename = "source_ref_ids")]
    pub source_ref_ids: Vec<String>,
    #[serde(rename = "payload_json")]
    pub payload_json: String,
    #[serde(rename = "runtime_executable")]
    pub runtime_executable: bool,
    #[serde(rename = "encounter_id")]
    pub encounter_id: i32,
    #[serde(rename = "wave_order")]
    pub wave_order: i32,
    #[serde(rename = "slot_order")]
    pub slot_order: i32,
    #[serde(rename = "enemy_id")]
    pub enemy_id: i32,
}

impl super::runtime::SoraDecode for AaEnemySlots {
    fn decode(reader: &mut super::runtime::SoraReader<'_>) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            stable_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            row_order: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            name_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            ownership: <AAOwnership as super::runtime::SoraDecode>::decode(reader)?,
            coverage_state: <AACoverageState as super::runtime::SoraDecode>::decode(reader)?,
            evidence_quality: <AAEvidenceQuality as super::runtime::SoraDecode>::decode(reader)?,
            mechanism_quality: <AAMechanismQuality as super::runtime::SoraDecode>::decode(reader)?,
            manifest_record_ids: <Vec<String> as super::runtime::SoraDecode>::decode(reader)?,
            source_ref_ids: <Vec<String> as super::runtime::SoraDecode>::decode(reader)?,
            payload_json: <String as super::runtime::SoraDecode>::decode(reader)?,
            runtime_executable: <bool as super::runtime::SoraDecode>::decode(reader)?,
            encounter_id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            wave_order: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            slot_order: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            enemy_id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
        })
    }
}

impl AaEnemySlots {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct AaEnemySlotsTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, AaEnemySlots>,
    by_stable_key: SoraMap<String, i32>,
}

impl AaEnemySlotsTable {
    pub const NAME: &'static str = "AAEnemySlots";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "AaEnemySlots",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[
            super::SoraIndexInfo {
                name: "by_stable_key",
                unique: true,
                fields: &["stable_key"],
            },
        ],
    };

    pub(super) fn from_rows(rows: Vec<AaEnemySlots>) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        let by_stable_key = super::build_unique_map_index(
            rows.iter(),
            |row| row.stable_key.clone(),
            |row| row.id,
        );
        let rows = super::decode_map_table(rows, |row| row.id);
        Ok(Self {
            keys,
            rows,
            by_stable_key,
        })
    }

    pub fn get(&self, key: &i32) -> Option<&AaEnemySlots> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &AaEnemySlots> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
    pub fn get_by_stable_key(&self, stable_key: &str) -> Option<&AaEnemySlots> {
        self.by_stable_key.get(stable_key).and_then(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for AaEnemySlotsTable {
    type Target = SoraMap<i32, AaEnemySlots>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for AaEnemySlotsTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for AaEnemySlotsTable {
    type Key = i32;
    type Row = AaEnemySlots;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
