// This file was generated by Sora. Do not edit manually.
use super::SoraMap;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ApsRuntimeNodes {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "stage_id")]
    pub stage_id: i32,
    #[serde(rename = "stable_key")]
    pub stable_key: String,
    #[serde(rename = "node_index")]
    pub node_index: i32,
    #[serde(rename = "team_index")]
    pub team_index: i32,
    #[serde(rename = "encounter_id")]
    pub encounter_id: i32,
    #[serde(rename = "maze_buff_id")]
    pub maze_buff_id: i32,
    #[serde(rename = "axiom_bundle_ids")]
    pub axiom_bundle_ids: Vec<i32>,
    #[serde(rename = "source_ref")]
    pub source_ref: String,
}

impl super::runtime::SoraDecode for ApsRuntimeNodes {
    fn decode(
        reader: &mut super::runtime::SoraReader<'_>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            stage_id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            stable_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            node_index: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            team_index: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            encounter_id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            maze_buff_id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            axiom_bundle_ids: <Vec<i32> as super::runtime::SoraDecode>::decode(reader)?,
            source_ref: <String as super::runtime::SoraDecode>::decode(reader)?,
        })
    }
}

impl ApsRuntimeNodes {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct ApsRuntimeNodesTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, ApsRuntimeNodes>,
    by_stable_key: SoraMap<String, i32>,
}

impl ApsRuntimeNodesTable {
    pub const NAME: &'static str = "ApsRuntimeNodes";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "ApsRuntimeNodes",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[super::SoraIndexInfo {
            name: "by_stable_key",
            unique: true,
            fields: &["stable_key"],
        }],
    };

    pub(super) fn from_rows(
        rows: Vec<ApsRuntimeNodes>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        let by_stable_key =
            super::build_unique_map_index(rows.iter(), |row| row.stable_key.clone(), |row| row.id);
        let rows = super::decode_map_table(rows, |row| row.id);
        Ok(Self {
            keys,
            rows,
            by_stable_key,
        })
    }

    pub fn get(&self, key: &i32) -> Option<&ApsRuntimeNodes> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &ApsRuntimeNodes> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
    pub fn get_by_stable_key(&self, stable_key: &str) -> Option<&ApsRuntimeNodes> {
        self.by_stable_key
            .get(stable_key)
            .and_then(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for ApsRuntimeNodesTable {
    type Target = SoraMap<i32, ApsRuntimeNodes>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for ApsRuntimeNodesTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for ApsRuntimeNodesTable {
    type Key = i32;
    type Row = ApsRuntimeNodes;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
