// This file was generated by Sora. Do not edit manually.
use super::SoraMap;
use super::anomaly_stage_kind::AnomalyStageKind;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ArbRuntimeStages {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "profile_id")]
    pub profile_id: i32,
    #[serde(rename = "stable_key")]
    pub stable_key: String,
    #[serde(rename = "source_stage_id")]
    pub source_stage_id: i32,
    #[serde(rename = "kind")]
    pub kind: AnomalyStageKind,
    #[serde(rename = "display_order")]
    pub display_order: i32,
    #[serde(rename = "team_index")]
    pub team_index: i32,
    #[serde(rename = "cycle_limit")]
    pub cycle_limit: i32,
    #[serde(rename = "encounter_id")]
    pub encounter_id: i32,
    #[serde(rename = "source_ref")]
    pub source_ref: String,
}

impl super::runtime::SoraDecode for ArbRuntimeStages {
    fn decode(
        reader: &mut super::runtime::SoraReader<'_>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            profile_id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            stable_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            source_stage_id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            kind: <AnomalyStageKind as super::runtime::SoraDecode>::decode(reader)?,
            display_order: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            team_index: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            cycle_limit: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            encounter_id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            source_ref: <String as super::runtime::SoraDecode>::decode(reader)?,
        })
    }
}

impl ArbRuntimeStages {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct ArbRuntimeStagesTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, ArbRuntimeStages>,
    by_stable_key: SoraMap<String, i32>,
}

impl ArbRuntimeStagesTable {
    pub const NAME: &'static str = "ArbRuntimeStages";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "ArbRuntimeStages",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[super::SoraIndexInfo {
            name: "by_stable_key",
            unique: true,
            fields: &["stable_key"],
        }],
    };

    pub(super) fn from_rows(
        rows: Vec<ArbRuntimeStages>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        let by_stable_key =
            super::build_unique_map_index(rows.iter(), |row| row.stable_key.clone(), |row| row.id);
        let rows = super::decode_map_table(rows, |row| row.id);
        Ok(Self {
            keys,
            rows,
            by_stable_key,
        })
    }

    pub fn get(&self, key: &i32) -> Option<&ArbRuntimeStages> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &ArbRuntimeStages> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
    pub fn get_by_stable_key(&self, stable_key: &str) -> Option<&ArbRuntimeStages> {
        self.by_stable_key
            .get(stable_key)
            .and_then(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for ArbRuntimeStagesTable {
    type Target = SoraMap<i32, ArbRuntimeStages>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for ArbRuntimeStagesTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for ArbRuntimeStagesTable {
    type Key = i32;
    type Row = ArbRuntimeStages;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
