// This file was generated by Sora. Do not edit manually.
use super::SoraMap;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ArbRuntimeProfiles {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "stable_key")]
    pub stable_key: String,
    #[serde(rename = "game_version")]
    pub game_version: String,
    #[serde(rename = "first_window_scaled")]
    pub first_window_scaled: i64,
    #[serde(rename = "later_window_scaled")]
    pub later_window_scaled: i64,
    #[serde(rename = "source_ref")]
    pub source_ref: String,
}

impl super::runtime::SoraDecode for ArbRuntimeProfiles {
    fn decode(
        reader: &mut super::runtime::SoraReader<'_>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            stable_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            game_version: <String as super::runtime::SoraDecode>::decode(reader)?,
            first_window_scaled: <i64 as super::runtime::SoraDecode>::decode(reader)?,
            later_window_scaled: <i64 as super::runtime::SoraDecode>::decode(reader)?,
            source_ref: <String as super::runtime::SoraDecode>::decode(reader)?,
        })
    }
}

impl ArbRuntimeProfiles {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct ArbRuntimeProfilesTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, ArbRuntimeProfiles>,
    by_stable_key: SoraMap<String, i32>,
}

impl ArbRuntimeProfilesTable {
    pub const NAME: &'static str = "ArbRuntimeProfiles";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "ArbRuntimeProfiles",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[super::SoraIndexInfo {
            name: "by_stable_key",
            unique: true,
            fields: &["stable_key"],
        }],
    };

    pub(super) fn from_rows(
        rows: Vec<ArbRuntimeProfiles>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        let by_stable_key =
            super::build_unique_map_index(rows.iter(), |row| row.stable_key.clone(), |row| row.id);
        let rows = super::decode_map_table(rows, |row| row.id);
        Ok(Self {
            keys,
            rows,
            by_stable_key,
        })
    }

    pub fn get(&self, key: &i32) -> Option<&ArbRuntimeProfiles> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &ArbRuntimeProfiles> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
    pub fn get_by_stable_key(&self, stable_key: &str) -> Option<&ArbRuntimeProfiles> {
        self.by_stable_key
            .get(stable_key)
            .and_then(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for ArbRuntimeProfilesTable {
    type Target = SoraMap<i32, ArbRuntimeProfiles>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for ArbRuntimeProfilesTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for ArbRuntimeProfilesTable {
    type Key = i32;
    type Row = ArbRuntimeProfiles;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
