// This file was generated by Sora. Do not edit manually.

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum ChallengeObjectiveKind {
    Complete,
    NoDefeatedParticipants,
    RemainingCyclesAtLeast,
    ScoreAtLeast,
}

impl super::runtime::SoraDecode for ChallengeObjectiveKind {
    fn decode(
        reader: &mut super::runtime::SoraReader<'_>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        match reader.read_var_u32()? {
            0 => Ok(Self::Complete),
            1 => Ok(Self::NoDefeatedParticipants),
            2 => Ok(Self::RemainingCyclesAtLeast),
            3 => Ok(Self::ScoreAtLeast),
            value => Err(super::runtime::SoraReadError::new(format!(
                "invalid enum ordinal {} for ChallengeObjectiveKind",
                value
            ))),
        }
    }
}
