// This file was generated by Sora. Do not edit manually.
use super::SoraMap;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct MocRuntimeEncounters {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "node_id")]
    pub node_id: i32,
    #[serde(rename = "level")]
    pub level: i32,
    #[serde(rename = "hard_level_group")]
    pub hard_level_group: i32,
    #[serde(rename = "source_url")]
    pub source_url: String,
    #[serde(rename = "source_revision")]
    pub source_revision: String,
    #[serde(rename = "source_path")]
    pub source_path: String,
    #[serde(rename = "source_locator")]
    pub source_locator: String,
    #[serde(rename = "evidence_digest")]
    pub evidence_digest: String,
    #[serde(rename = "evidence_quality")]
    pub evidence_quality: String,
    #[serde(rename = "mechanism_quality")]
    pub mechanism_quality: String,
}

impl super::runtime::SoraDecode for MocRuntimeEncounters {
    fn decode(
        reader: &mut super::runtime::SoraReader<'_>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            node_id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            level: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            hard_level_group: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            source_url: <String as super::runtime::SoraDecode>::decode(reader)?,
            source_revision: <String as super::runtime::SoraDecode>::decode(reader)?,
            source_path: <String as super::runtime::SoraDecode>::decode(reader)?,
            source_locator: <String as super::runtime::SoraDecode>::decode(reader)?,
            evidence_digest: <String as super::runtime::SoraDecode>::decode(reader)?,
            evidence_quality: <String as super::runtime::SoraDecode>::decode(reader)?,
            mechanism_quality: <String as super::runtime::SoraDecode>::decode(reader)?,
        })
    }
}

impl MocRuntimeEncounters {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct MocRuntimeEncountersTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, MocRuntimeEncounters>,
    by_node: SoraMap<i32, i32>,
}

impl MocRuntimeEncountersTable {
    pub const NAME: &'static str = "MocRuntimeEncounters";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "MocRuntimeEncounters",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[super::SoraIndexInfo {
            name: "by_node",
            unique: true,
            fields: &["node_id"],
        }],
    };

    pub(super) fn from_rows(
        rows: Vec<MocRuntimeEncounters>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        let by_node = super::build_unique_map_index(rows.iter(), |row| row.node_id, |row| row.id);
        let rows = super::decode_map_table(rows, |row| row.id);
        Ok(Self {
            keys,
            rows,
            by_node,
        })
    }

    pub fn get(&self, key: &i32) -> Option<&MocRuntimeEncounters> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &MocRuntimeEncounters> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
    pub fn get_by_node(&self, node_id: i32) -> Option<&MocRuntimeEncounters> {
        self.by_node
            .get(&node_id)
            .and_then(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for MocRuntimeEncountersTable {
    type Target = SoraMap<i32, MocRuntimeEncounters>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for MocRuntimeEncountersTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for MocRuntimeEncountersTable {
    type Key = i32;
    type Row = MocRuntimeEncounters;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
