// This file was generated by Sora. Do not edit manually.
use super::SoraMap;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct MocRuntimeWaves {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "encounter_id")]
    pub encounter_id: i32,
    #[serde(rename = "sequence")]
    pub sequence: i32,
    #[serde(rename = "source_url")]
    pub source_url: String,
    #[serde(rename = "source_revision")]
    pub source_revision: String,
    #[serde(rename = "source_path")]
    pub source_path: String,
    #[serde(rename = "source_locator")]
    pub source_locator: String,
    #[serde(rename = "evidence_digest")]
    pub evidence_digest: String,
    #[serde(rename = "evidence_quality")]
    pub evidence_quality: String,
    #[serde(rename = "mechanism_quality")]
    pub mechanism_quality: String,
}

impl super::runtime::SoraDecode for MocRuntimeWaves {
    fn decode(
        reader: &mut super::runtime::SoraReader<'_>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            encounter_id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            sequence: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            source_url: <String as super::runtime::SoraDecode>::decode(reader)?,
            source_revision: <String as super::runtime::SoraDecode>::decode(reader)?,
            source_path: <String as super::runtime::SoraDecode>::decode(reader)?,
            source_locator: <String as super::runtime::SoraDecode>::decode(reader)?,
            evidence_digest: <String as super::runtime::SoraDecode>::decode(reader)?,
            evidence_quality: <String as super::runtime::SoraDecode>::decode(reader)?,
            mechanism_quality: <String as super::runtime::SoraDecode>::decode(reader)?,
        })
    }
}

impl MocRuntimeWaves {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct MocRuntimeWavesTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, MocRuntimeWaves>,
}

impl MocRuntimeWavesTable {
    pub const NAME: &'static str = "MocRuntimeWaves";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "MocRuntimeWaves",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[],
    };

    pub(super) fn from_rows(
        rows: Vec<MocRuntimeWaves>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        Ok(Self {
            keys,
            rows: super::decode_map_table(rows, |row| row.id),
        })
    }

    pub fn get(&self, key: &i32) -> Option<&MocRuntimeWaves> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &MocRuntimeWaves> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for MocRuntimeWavesTable {
    type Target = SoraMap<i32, MocRuntimeWaves>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for MocRuntimeWavesTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for MocRuntimeWavesTable {
    type Key = i32;
    type Row = MocRuntimeWaves;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
