// This file was generated by Sora. Do not edit manually.
use super::SoraMap;
use super::challenge_objective_kind::ChallengeObjectiveKind;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct MocRuntimeObjectives {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "profile_id")]
    pub profile_id: i32,
    #[serde(rename = "stable_key")]
    pub stable_key: String,
    #[serde(rename = "kind")]
    pub kind: ChallengeObjectiveKind,
    #[serde(rename = "threshold")]
    pub threshold: i64,
    #[serde(rename = "source_url")]
    pub source_url: String,
    #[serde(rename = "source_revision")]
    pub source_revision: String,
    #[serde(rename = "source_path")]
    pub source_path: String,
    #[serde(rename = "source_locator")]
    pub source_locator: String,
    #[serde(rename = "evidence_digest")]
    pub evidence_digest: String,
    #[serde(rename = "evidence_quality")]
    pub evidence_quality: String,
    #[serde(rename = "mechanism_quality")]
    pub mechanism_quality: String,
}

impl super::runtime::SoraDecode for MocRuntimeObjectives {
    fn decode(
        reader: &mut super::runtime::SoraReader<'_>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            profile_id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            stable_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            kind: <ChallengeObjectiveKind as super::runtime::SoraDecode>::decode(reader)?,
            threshold: <i64 as super::runtime::SoraDecode>::decode(reader)?,
            source_url: <String as super::runtime::SoraDecode>::decode(reader)?,
            source_revision: <String as super::runtime::SoraDecode>::decode(reader)?,
            source_path: <String as super::runtime::SoraDecode>::decode(reader)?,
            source_locator: <String as super::runtime::SoraDecode>::decode(reader)?,
            evidence_digest: <String as super::runtime::SoraDecode>::decode(reader)?,
            evidence_quality: <String as super::runtime::SoraDecode>::decode(reader)?,
            mechanism_quality: <String as super::runtime::SoraDecode>::decode(reader)?,
        })
    }
}

impl MocRuntimeObjectives {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct MocRuntimeObjectivesTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, MocRuntimeObjectives>,
    by_stable_key: SoraMap<String, i32>,
}

impl MocRuntimeObjectivesTable {
    pub const NAME: &'static str = "MocRuntimeObjectives";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "MocRuntimeObjectives",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[super::SoraIndexInfo {
            name: "by_stable_key",
            unique: true,
            fields: &["stable_key"],
        }],
    };

    pub(super) fn from_rows(
        rows: Vec<MocRuntimeObjectives>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        let by_stable_key =
            super::build_unique_map_index(rows.iter(), |row| row.stable_key.clone(), |row| row.id);
        let rows = super::decode_map_table(rows, |row| row.id);
        Ok(Self {
            keys,
            rows,
            by_stable_key,
        })
    }

    pub fn get(&self, key: &i32) -> Option<&MocRuntimeObjectives> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &MocRuntimeObjectives> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
    pub fn get_by_stable_key(&self, stable_key: &str) -> Option<&MocRuntimeObjectives> {
        self.by_stable_key
            .get(stable_key)
            .and_then(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for MocRuntimeObjectivesTable {
    type Target = SoraMap<i32, MocRuntimeObjectives>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for MocRuntimeObjectivesTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for MocRuntimeObjectivesTable {
    type Key = i32;
    type Row = MocRuntimeObjectives;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
