// This file was generated by Sora. Do not edit manually.
use super::SoraMap;
use super::challenge_combat_element::ChallengeCombatElement;
use super::challenge_enemy_rank::ChallengeEnemyRank;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct MocRuntimeEnemySlots {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "wave_id")]
    pub wave_id: i32,
    #[serde(rename = "enemy_binding_id")]
    pub enemy_binding_id: i32,
    #[serde(rename = "spawn_sequence")]
    pub spawn_sequence: i32,
    #[serde(rename = "formation_index")]
    pub formation_index: i32,
    #[serde(rename = "rank")]
    pub rank: ChallengeEnemyRank,
    #[serde(rename = "weaknesses")]
    pub weaknesses: Option<Vec<ChallengeCombatElement>>,
    #[serde(rename = "maximum_hp_scaled")]
    pub maximum_hp_scaled: i64,
    #[serde(rename = "attack_scaled")]
    pub attack_scaled: i64,
    #[serde(rename = "defense_scaled")]
    pub defense_scaled: i64,
    #[serde(rename = "speed_scaled")]
    pub speed_scaled: i64,
    #[serde(rename = "effect_hit_rate_scaled")]
    pub effect_hit_rate_scaled: i64,
    #[serde(rename = "effect_resistance_scaled")]
    pub effect_resistance_scaled: i64,
    #[serde(rename = "toughness_scaled")]
    pub toughness_scaled: i64,
    #[serde(rename = "source_url")]
    pub source_url: String,
    #[serde(rename = "source_revision")]
    pub source_revision: String,
    #[serde(rename = "source_path")]
    pub source_path: String,
    #[serde(rename = "source_locator")]
    pub source_locator: String,
    #[serde(rename = "evidence_digest")]
    pub evidence_digest: String,
    #[serde(rename = "evidence_quality")]
    pub evidence_quality: String,
    #[serde(rename = "mechanism_quality")]
    pub mechanism_quality: String,
}

impl super::runtime::SoraDecode for MocRuntimeEnemySlots {
    fn decode(
        reader: &mut super::runtime::SoraReader<'_>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            wave_id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            enemy_binding_id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            spawn_sequence: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            formation_index: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            rank: <ChallengeEnemyRank as super::runtime::SoraDecode>::decode(reader)?,
            weaknesses:
                <Option<Vec<ChallengeCombatElement>> as super::runtime::SoraDecode>::decode(reader)?,
            maximum_hp_scaled: <i64 as super::runtime::SoraDecode>::decode(reader)?,
            attack_scaled: <i64 as super::runtime::SoraDecode>::decode(reader)?,
            defense_scaled: <i64 as super::runtime::SoraDecode>::decode(reader)?,
            speed_scaled: <i64 as super::runtime::SoraDecode>::decode(reader)?,
            effect_hit_rate_scaled: <i64 as super::runtime::SoraDecode>::decode(reader)?,
            effect_resistance_scaled: <i64 as super::runtime::SoraDecode>::decode(reader)?,
            toughness_scaled: <i64 as super::runtime::SoraDecode>::decode(reader)?,
            source_url: <String as super::runtime::SoraDecode>::decode(reader)?,
            source_revision: <String as super::runtime::SoraDecode>::decode(reader)?,
            source_path: <String as super::runtime::SoraDecode>::decode(reader)?,
            source_locator: <String as super::runtime::SoraDecode>::decode(reader)?,
            evidence_digest: <String as super::runtime::SoraDecode>::decode(reader)?,
            evidence_quality: <String as super::runtime::SoraDecode>::decode(reader)?,
            mechanism_quality: <String as super::runtime::SoraDecode>::decode(reader)?,
        })
    }
}

impl MocRuntimeEnemySlots {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct MocRuntimeEnemySlotsTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, MocRuntimeEnemySlots>,
}

impl MocRuntimeEnemySlotsTable {
    pub const NAME: &'static str = "MocRuntimeEnemySlots";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "MocRuntimeEnemySlots",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[],
    };

    pub(super) fn from_rows(
        rows: Vec<MocRuntimeEnemySlots>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        Ok(Self {
            keys,
            rows: super::decode_map_table(rows, |row| row.id),
        })
    }

    pub fn get(&self, key: &i32) -> Option<&MocRuntimeEnemySlots> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &MocRuntimeEnemySlots> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for MocRuntimeEnemySlotsTable {
    type Target = SoraMap<i32, MocRuntimeEnemySlots>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for MocRuntimeEnemySlotsTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for MocRuntimeEnemySlotsTable {
    type Key = i32;
    type Row = MocRuntimeEnemySlots;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
