// This file was generated by Sora. Do not edit manually.

#![allow(dead_code)]

pub mod aps_runtime_encounters;
pub mod aps_runtime_enemies;
pub mod aps_runtime_enemy_slots;
pub mod aps_runtime_nodes;
pub mod aps_runtime_objectives;
pub mod aps_runtime_policies;
pub mod aps_runtime_profiles;
pub mod aps_runtime_stages;
pub mod challenge_clock_expiry;
pub mod challenge_combat_element;
pub mod challenge_enemy_rank;
pub mod challenge_objective_kind;
pub mod challenge_policy_confidence;
pub mod moc_runtime_encounters;
pub mod moc_runtime_enemy_bindings;
pub mod moc_runtime_enemy_slots;
pub mod moc_runtime_nodes;
pub mod moc_runtime_objectives;
pub mod moc_runtime_policies;
pub mod moc_runtime_profiles;
pub mod moc_runtime_stages;
pub mod moc_runtime_waves;
pub mod pf_runtime_cacophonies;
pub mod pf_runtime_encounters;
pub mod pf_runtime_enemies;
pub mod pf_runtime_enemy_slots;
pub mod pf_runtime_nodes;
pub mod pf_runtime_objectives;
pub mod pf_runtime_policies;
pub mod pf_runtime_profiles;
pub mod pf_runtime_stages;
pub mod pf_runtime_waves;
pub mod pure_fiction_spawn_end;
pub mod runtime;
pub type SoraMap<K, V> = std::collections::HashMap<K, V>;

pub const SCHEMA_FINGERPRINT: &str = "29200a2d5ee8ade0";

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SoraTableShape {
    List,
    Keyed,
    Singleton,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SoraKeyInfo {
    pub name: &'static str,
    pub ty: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SoraIndexInfo {
    pub name: &'static str,
    pub unique: bool,
    pub fields: &'static [&'static str],
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SoraTableInfo {
    pub name: &'static str,
    pub row_type: &'static str,
    pub shape: SoraTableShape,
    pub primary_key: Option<SoraKeyInfo>,
    pub indexes: &'static [SoraIndexInfo],
}

pub trait ErasedSoraTable: std::any::Any + Send + Sync {
    fn info(&self) -> &'static SoraTableInfo;
    fn len(&self) -> usize;

    fn is_empty(&self) -> bool {
        self.len() == 0
    }
}

pub trait SoraKeyedTable: ErasedSoraTable {
    type Key: std::cmp::Eq + std::hash::Hash + 'static;
    type Row: 'static;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row>;
    fn keys(&self) -> &[Self::Key];
}

pub trait SoraListTable: ErasedSoraTable {
    type Row: 'static;

    fn as_slice(&self) -> &[Self::Row];
}

pub trait SoraSingleTable: ErasedSoraTable {
    type Row: 'static;

    fn get(&self) -> &Self::Row;
}

pub struct SoraConfig {
    tables: SoraMap<&'static str, Box<dyn ErasedSoraTable>>,
}

impl std::fmt::Debug for SoraConfig {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let mut tables = self.tables.keys().copied().collect::<Vec<_>>();
        tables.sort_unstable();
        f.debug_struct("SoraConfig")
            .field("tables", &tables)
            .finish()
    }
}

impl SoraConfig {
    pub fn from_source(
        source: &impl runtime::SoraTableSource,
    ) -> Result<Self, runtime::SoraReadError> {
        let schema_fingerprint = source.schema_fingerprint()?;
        if schema_fingerprint != SCHEMA_FINGERPRINT {
            return Err(runtime::SoraReadError::new(format!(
                "schema fingerprint mismatch: generated code expects {}, bundle contains {}",
                SCHEMA_FINGERPRINT, schema_fingerprint
            )));
        }
        let mut tables: SoraMap<&'static str, Box<dyn ErasedSoraTable>> =
            sora_map_with_capacity(27);
        tables.insert(
            moc_runtime_profiles::MocRuntimeProfilesTable::NAME,
            Box::new(moc_runtime_profiles::MocRuntimeProfilesTable::from_rows(
                source.decode_table::<moc_runtime_profiles::MocRuntimeProfiles>(
                    moc_runtime_profiles::MocRuntimeProfilesTable::NAME,
                )?,
            )?),
        );
        tables.insert(
            moc_runtime_stages::MocRuntimeStagesTable::NAME,
            Box::new(moc_runtime_stages::MocRuntimeStagesTable::from_rows(
                source.decode_table::<moc_runtime_stages::MocRuntimeStages>(
                    moc_runtime_stages::MocRuntimeStagesTable::NAME,
                )?,
            )?),
        );
        tables.insert(
            moc_runtime_nodes::MocRuntimeNodesTable::NAME,
            Box::new(moc_runtime_nodes::MocRuntimeNodesTable::from_rows(
                source.decode_table::<moc_runtime_nodes::MocRuntimeNodes>(
                    moc_runtime_nodes::MocRuntimeNodesTable::NAME,
                )?,
            )?),
        );
        tables.insert(
            moc_runtime_objectives::MocRuntimeObjectivesTable::NAME,
            Box::new(
                moc_runtime_objectives::MocRuntimeObjectivesTable::from_rows(
                    source.decode_table::<moc_runtime_objectives::MocRuntimeObjectives>(
                        moc_runtime_objectives::MocRuntimeObjectivesTable::NAME,
                    )?,
                )?,
            ),
        );
        tables.insert(
            moc_runtime_policies::MocRuntimePoliciesTable::NAME,
            Box::new(moc_runtime_policies::MocRuntimePoliciesTable::from_rows(
                source.decode_table::<moc_runtime_policies::MocRuntimePolicies>(
                    moc_runtime_policies::MocRuntimePoliciesTable::NAME,
                )?,
            )?),
        );
        tables.insert(
            moc_runtime_enemy_bindings::MocRuntimeEnemyBindingsTable::NAME,
            Box::new(
                moc_runtime_enemy_bindings::MocRuntimeEnemyBindingsTable::from_rows(
                    source.decode_table::<moc_runtime_enemy_bindings::MocRuntimeEnemyBindings>(
                        moc_runtime_enemy_bindings::MocRuntimeEnemyBindingsTable::NAME,
                    )?,
                )?,
            ),
        );
        tables.insert(
            moc_runtime_encounters::MocRuntimeEncountersTable::NAME,
            Box::new(
                moc_runtime_encounters::MocRuntimeEncountersTable::from_rows(
                    source.decode_table::<moc_runtime_encounters::MocRuntimeEncounters>(
                        moc_runtime_encounters::MocRuntimeEncountersTable::NAME,
                    )?,
                )?,
            ),
        );
        tables.insert(
            moc_runtime_waves::MocRuntimeWavesTable::NAME,
            Box::new(moc_runtime_waves::MocRuntimeWavesTable::from_rows(
                source.decode_table::<moc_runtime_waves::MocRuntimeWaves>(
                    moc_runtime_waves::MocRuntimeWavesTable::NAME,
                )?,
            )?),
        );
        tables.insert(
            moc_runtime_enemy_slots::MocRuntimeEnemySlotsTable::NAME,
            Box::new(
                moc_runtime_enemy_slots::MocRuntimeEnemySlotsTable::from_rows(
                    source.decode_table::<moc_runtime_enemy_slots::MocRuntimeEnemySlots>(
                        moc_runtime_enemy_slots::MocRuntimeEnemySlotsTable::NAME,
                    )?,
                )?,
            ),
        );
        tables.insert(
            aps_runtime_profiles::ApsRuntimeProfilesTable::NAME,
            Box::new(aps_runtime_profiles::ApsRuntimeProfilesTable::from_rows(
                source.decode_table::<aps_runtime_profiles::ApsRuntimeProfiles>(
                    aps_runtime_profiles::ApsRuntimeProfilesTable::NAME,
                )?,
            )?),
        );
        tables.insert(
            aps_runtime_stages::ApsRuntimeStagesTable::NAME,
            Box::new(aps_runtime_stages::ApsRuntimeStagesTable::from_rows(
                source.decode_table::<aps_runtime_stages::ApsRuntimeStages>(
                    aps_runtime_stages::ApsRuntimeStagesTable::NAME,
                )?,
            )?),
        );
        tables.insert(
            aps_runtime_nodes::ApsRuntimeNodesTable::NAME,
            Box::new(aps_runtime_nodes::ApsRuntimeNodesTable::from_rows(
                source.decode_table::<aps_runtime_nodes::ApsRuntimeNodes>(
                    aps_runtime_nodes::ApsRuntimeNodesTable::NAME,
                )?,
            )?),
        );
        tables.insert(
            aps_runtime_objectives::ApsRuntimeObjectivesTable::NAME,
            Box::new(
                aps_runtime_objectives::ApsRuntimeObjectivesTable::from_rows(
                    source.decode_table::<aps_runtime_objectives::ApsRuntimeObjectives>(
                        aps_runtime_objectives::ApsRuntimeObjectivesTable::NAME,
                    )?,
                )?,
            ),
        );
        tables.insert(
            aps_runtime_policies::ApsRuntimePoliciesTable::NAME,
            Box::new(aps_runtime_policies::ApsRuntimePoliciesTable::from_rows(
                source.decode_table::<aps_runtime_policies::ApsRuntimePolicies>(
                    aps_runtime_policies::ApsRuntimePoliciesTable::NAME,
                )?,
            )?),
        );
        tables.insert(
            aps_runtime_enemies::ApsRuntimeEnemiesTable::NAME,
            Box::new(aps_runtime_enemies::ApsRuntimeEnemiesTable::from_rows(
                source.decode_table::<aps_runtime_enemies::ApsRuntimeEnemies>(
                    aps_runtime_enemies::ApsRuntimeEnemiesTable::NAME,
                )?,
            )?),
        );
        tables.insert(
            aps_runtime_encounters::ApsRuntimeEncountersTable::NAME,
            Box::new(
                aps_runtime_encounters::ApsRuntimeEncountersTable::from_rows(
                    source.decode_table::<aps_runtime_encounters::ApsRuntimeEncounters>(
                        aps_runtime_encounters::ApsRuntimeEncountersTable::NAME,
                    )?,
                )?,
            ),
        );
        tables.insert(
            aps_runtime_enemy_slots::ApsRuntimeEnemySlotsTable::NAME,
            Box::new(
                aps_runtime_enemy_slots::ApsRuntimeEnemySlotsTable::from_rows(
                    source.decode_table::<aps_runtime_enemy_slots::ApsRuntimeEnemySlots>(
                        aps_runtime_enemy_slots::ApsRuntimeEnemySlotsTable::NAME,
                    )?,
                )?,
            ),
        );
        tables.insert(
            pf_runtime_profiles::PfRuntimeProfilesTable::NAME,
            Box::new(pf_runtime_profiles::PfRuntimeProfilesTable::from_rows(
                source.decode_table::<pf_runtime_profiles::PfRuntimeProfiles>(
                    pf_runtime_profiles::PfRuntimeProfilesTable::NAME,
                )?,
            )?),
        );
        tables.insert(
            pf_runtime_stages::PfRuntimeStagesTable::NAME,
            Box::new(pf_runtime_stages::PfRuntimeStagesTable::from_rows(
                source.decode_table::<pf_runtime_stages::PfRuntimeStages>(
                    pf_runtime_stages::PfRuntimeStagesTable::NAME,
                )?,
            )?),
        );
        tables.insert(
            pf_runtime_nodes::PfRuntimeNodesTable::NAME,
            Box::new(pf_runtime_nodes::PfRuntimeNodesTable::from_rows(
                source.decode_table::<pf_runtime_nodes::PfRuntimeNodes>(
                    pf_runtime_nodes::PfRuntimeNodesTable::NAME,
                )?,
            )?),
        );
        tables.insert(
            pf_runtime_objectives::PfRuntimeObjectivesTable::NAME,
            Box::new(pf_runtime_objectives::PfRuntimeObjectivesTable::from_rows(
                source.decode_table::<pf_runtime_objectives::PfRuntimeObjectives>(
                    pf_runtime_objectives::PfRuntimeObjectivesTable::NAME,
                )?,
            )?),
        );
        tables.insert(
            pf_runtime_cacophonies::PfRuntimeCacophoniesTable::NAME,
            Box::new(
                pf_runtime_cacophonies::PfRuntimeCacophoniesTable::from_rows(
                    source.decode_table::<pf_runtime_cacophonies::PfRuntimeCacophonies>(
                        pf_runtime_cacophonies::PfRuntimeCacophoniesTable::NAME,
                    )?,
                )?,
            ),
        );
        tables.insert(
            pf_runtime_policies::PfRuntimePoliciesTable::NAME,
            Box::new(pf_runtime_policies::PfRuntimePoliciesTable::from_rows(
                source.decode_table::<pf_runtime_policies::PfRuntimePolicies>(
                    pf_runtime_policies::PfRuntimePoliciesTable::NAME,
                )?,
            )?),
        );
        tables.insert(
            pf_runtime_enemies::PfRuntimeEnemiesTable::NAME,
            Box::new(pf_runtime_enemies::PfRuntimeEnemiesTable::from_rows(
                source.decode_table::<pf_runtime_enemies::PfRuntimeEnemies>(
                    pf_runtime_enemies::PfRuntimeEnemiesTable::NAME,
                )?,
            )?),
        );
        tables.insert(
            pf_runtime_encounters::PfRuntimeEncountersTable::NAME,
            Box::new(pf_runtime_encounters::PfRuntimeEncountersTable::from_rows(
                source.decode_table::<pf_runtime_encounters::PfRuntimeEncounters>(
                    pf_runtime_encounters::PfRuntimeEncountersTable::NAME,
                )?,
            )?),
        );
        tables.insert(
            pf_runtime_waves::PfRuntimeWavesTable::NAME,
            Box::new(pf_runtime_waves::PfRuntimeWavesTable::from_rows(
                source.decode_table::<pf_runtime_waves::PfRuntimeWaves>(
                    pf_runtime_waves::PfRuntimeWavesTable::NAME,
                )?,
            )?),
        );
        tables.insert(
            pf_runtime_enemy_slots::PfRuntimeEnemySlotsTable::NAME,
            Box::new(pf_runtime_enemy_slots::PfRuntimeEnemySlotsTable::from_rows(
                source.decode_table::<pf_runtime_enemy_slots::PfRuntimeEnemySlots>(
                    pf_runtime_enemy_slots::PfRuntimeEnemySlotsTable::NAME,
                )?,
            )?),
        );
        Ok(Self { tables })
    }

    fn table<T: ErasedSoraTable + 'static>(&self, name: &'static str) -> &T {
        self.tables
            .get(name)
            .and_then(|table| {
                let table: &dyn std::any::Any = table.as_ref();
                table.downcast_ref::<T>()
            })
            .unwrap_or_else(|| {
                panic!(
                    "generated SoraConfig is missing table `{}` or has an unexpected table type",
                    name
                )
            })
    }

    pub fn tables(&self) -> impl Iterator<Item = &dyn ErasedSoraTable> {
        self.tables.values().map(Box::as_ref)
    }

    pub fn moc_runtime_profiles(&self) -> &moc_runtime_profiles::MocRuntimeProfilesTable {
        self.table(moc_runtime_profiles::MocRuntimeProfilesTable::NAME)
    }

    pub fn moc_runtime_stages(&self) -> &moc_runtime_stages::MocRuntimeStagesTable {
        self.table(moc_runtime_stages::MocRuntimeStagesTable::NAME)
    }

    pub fn moc_runtime_nodes(&self) -> &moc_runtime_nodes::MocRuntimeNodesTable {
        self.table(moc_runtime_nodes::MocRuntimeNodesTable::NAME)
    }

    pub fn moc_runtime_objectives(&self) -> &moc_runtime_objectives::MocRuntimeObjectivesTable {
        self.table(moc_runtime_objectives::MocRuntimeObjectivesTable::NAME)
    }

    pub fn moc_runtime_policies(&self) -> &moc_runtime_policies::MocRuntimePoliciesTable {
        self.table(moc_runtime_policies::MocRuntimePoliciesTable::NAME)
    }

    pub fn moc_runtime_enemy_bindings(
        &self,
    ) -> &moc_runtime_enemy_bindings::MocRuntimeEnemyBindingsTable {
        self.table(moc_runtime_enemy_bindings::MocRuntimeEnemyBindingsTable::NAME)
    }

    pub fn moc_runtime_encounters(&self) -> &moc_runtime_encounters::MocRuntimeEncountersTable {
        self.table(moc_runtime_encounters::MocRuntimeEncountersTable::NAME)
    }

    pub fn moc_runtime_waves(&self) -> &moc_runtime_waves::MocRuntimeWavesTable {
        self.table(moc_runtime_waves::MocRuntimeWavesTable::NAME)
    }

    pub fn moc_runtime_enemy_slots(&self) -> &moc_runtime_enemy_slots::MocRuntimeEnemySlotsTable {
        self.table(moc_runtime_enemy_slots::MocRuntimeEnemySlotsTable::NAME)
    }

    pub fn aps_runtime_profiles(&self) -> &aps_runtime_profiles::ApsRuntimeProfilesTable {
        self.table(aps_runtime_profiles::ApsRuntimeProfilesTable::NAME)
    }

    pub fn aps_runtime_stages(&self) -> &aps_runtime_stages::ApsRuntimeStagesTable {
        self.table(aps_runtime_stages::ApsRuntimeStagesTable::NAME)
    }

    pub fn aps_runtime_nodes(&self) -> &aps_runtime_nodes::ApsRuntimeNodesTable {
        self.table(aps_runtime_nodes::ApsRuntimeNodesTable::NAME)
    }

    pub fn aps_runtime_objectives(&self) -> &aps_runtime_objectives::ApsRuntimeObjectivesTable {
        self.table(aps_runtime_objectives::ApsRuntimeObjectivesTable::NAME)
    }

    pub fn aps_runtime_policies(&self) -> &aps_runtime_policies::ApsRuntimePoliciesTable {
        self.table(aps_runtime_policies::ApsRuntimePoliciesTable::NAME)
    }

    pub fn aps_runtime_enemies(&self) -> &aps_runtime_enemies::ApsRuntimeEnemiesTable {
        self.table(aps_runtime_enemies::ApsRuntimeEnemiesTable::NAME)
    }

    pub fn aps_runtime_encounters(&self) -> &aps_runtime_encounters::ApsRuntimeEncountersTable {
        self.table(aps_runtime_encounters::ApsRuntimeEncountersTable::NAME)
    }

    pub fn aps_runtime_enemy_slots(&self) -> &aps_runtime_enemy_slots::ApsRuntimeEnemySlotsTable {
        self.table(aps_runtime_enemy_slots::ApsRuntimeEnemySlotsTable::NAME)
    }

    pub fn pf_runtime_profiles(&self) -> &pf_runtime_profiles::PfRuntimeProfilesTable {
        self.table(pf_runtime_profiles::PfRuntimeProfilesTable::NAME)
    }

    pub fn pf_runtime_stages(&self) -> &pf_runtime_stages::PfRuntimeStagesTable {
        self.table(pf_runtime_stages::PfRuntimeStagesTable::NAME)
    }

    pub fn pf_runtime_nodes(&self) -> &pf_runtime_nodes::PfRuntimeNodesTable {
        self.table(pf_runtime_nodes::PfRuntimeNodesTable::NAME)
    }

    pub fn pf_runtime_objectives(&self) -> &pf_runtime_objectives::PfRuntimeObjectivesTable {
        self.table(pf_runtime_objectives::PfRuntimeObjectivesTable::NAME)
    }

    pub fn pf_runtime_cacophonies(&self) -> &pf_runtime_cacophonies::PfRuntimeCacophoniesTable {
        self.table(pf_runtime_cacophonies::PfRuntimeCacophoniesTable::NAME)
    }

    pub fn pf_runtime_policies(&self) -> &pf_runtime_policies::PfRuntimePoliciesTable {
        self.table(pf_runtime_policies::PfRuntimePoliciesTable::NAME)
    }

    pub fn pf_runtime_enemies(&self) -> &pf_runtime_enemies::PfRuntimeEnemiesTable {
        self.table(pf_runtime_enemies::PfRuntimeEnemiesTable::NAME)
    }

    pub fn pf_runtime_encounters(&self) -> &pf_runtime_encounters::PfRuntimeEncountersTable {
        self.table(pf_runtime_encounters::PfRuntimeEncountersTable::NAME)
    }

    pub fn pf_runtime_waves(&self) -> &pf_runtime_waves::PfRuntimeWavesTable {
        self.table(pf_runtime_waves::PfRuntimeWavesTable::NAME)
    }

    pub fn pf_runtime_enemy_slots(&self) -> &pf_runtime_enemy_slots::PfRuntimeEnemySlotsTable {
        self.table(pf_runtime_enemy_slots::PfRuntimeEnemySlotsTable::NAME)
    }
}

fn sora_map_with_capacity<K, V>(capacity: usize) -> SoraMap<K, V>
where
    K: std::cmp::Eq + std::hash::Hash,
{
    SoraMap::with_capacity(capacity)
}

fn decode_map_table<K, V>(rows: Vec<V>, key: impl Fn(&V) -> K) -> SoraMap<K, V>
where
    K: std::cmp::Eq + std::hash::Hash,
{
    rows.into_iter().map(|row| (key(&row), row)).collect()
}

fn build_unique_list_index<'a, K, V: 'a>(
    rows: impl Iterator<Item = &'a V>,
    key: impl Fn(&V) -> K,
) -> SoraMap<K, usize>
where
    K: std::cmp::Eq + std::hash::Hash,
{
    let mut index = sora_map_with_capacity(rows.size_hint().0);
    for (position, row) in rows.enumerate() {
        index.insert(key(row), position);
    }
    index
}

fn build_unique_map_index<'a, K, P, V: 'a>(
    rows: impl Iterator<Item = &'a V>,
    key: impl Fn(&V) -> K,
    primary_key: impl Fn(&V) -> P,
) -> SoraMap<K, P>
where
    K: std::cmp::Eq + std::hash::Hash,
    P: std::cmp::Eq + std::hash::Hash,
{
    let mut index = sora_map_with_capacity(rows.size_hint().0);
    for row in rows {
        index.insert(key(row), primary_key(row));
    }
    index
}
