// This file was generated by Sora. Do not edit manually.
use super::SoraMap;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct PfRuntimeCacophonies {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "profile_id")]
    pub profile_id: i32,
    #[serde(rename = "stable_key")]
    pub stable_key: String,
    #[serde(rename = "upstream_buff_id")]
    pub upstream_buff_id: i32,
    #[serde(rename = "binding_key")]
    pub binding_key: String,
    #[serde(rename = "parameters")]
    pub parameters: Vec<String>,
    #[serde(rename = "source_ref")]
    pub source_ref: String,
}

impl super::runtime::SoraDecode for PfRuntimeCacophonies {
    fn decode(
        reader: &mut super::runtime::SoraReader<'_>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            profile_id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            stable_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            upstream_buff_id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            binding_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            parameters: <Vec<String> as super::runtime::SoraDecode>::decode(reader)?,
            source_ref: <String as super::runtime::SoraDecode>::decode(reader)?,
        })
    }
}

impl PfRuntimeCacophonies {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct PfRuntimeCacophoniesTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, PfRuntimeCacophonies>,
    by_stable_key: SoraMap<String, i32>,
}

impl PfRuntimeCacophoniesTable {
    pub const NAME: &'static str = "PfRuntimeCacophonies";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "PfRuntimeCacophonies",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[super::SoraIndexInfo {
            name: "by_stable_key",
            unique: true,
            fields: &["stable_key"],
        }],
    };

    pub(super) fn from_rows(
        rows: Vec<PfRuntimeCacophonies>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        let by_stable_key =
            super::build_unique_map_index(rows.iter(), |row| row.stable_key.clone(), |row| row.id);
        let rows = super::decode_map_table(rows, |row| row.id);
        Ok(Self {
            keys,
            rows,
            by_stable_key,
        })
    }

    pub fn get(&self, key: &i32) -> Option<&PfRuntimeCacophonies> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &PfRuntimeCacophonies> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
    pub fn get_by_stable_key(&self, stable_key: &str) -> Option<&PfRuntimeCacophonies> {
        self.by_stable_key
            .get(stable_key)
            .and_then(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for PfRuntimeCacophoniesTable {
    type Target = SoraMap<i32, PfRuntimeCacophonies>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for PfRuntimeCacophoniesTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for PfRuntimeCacophoniesTable {
    type Key = i32;
    type Row = PfRuntimeCacophonies;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
