"""Released Footstep operands, with independently replaceable execution fields."""
from hashlib import sha256

HP_POLICY_NOTE = "VersionedProjectPolicy: original entry-form Destruction/Remembrance only, excluding owned linked actors. Observe negative effective DamageApplied and explicit HpChanged AfterEvent, priority zero, once per event. Independent battle-local absolute HP residue accumulates actual loss; live maximum HP times the fraction floors to six places, then the accumulated loss divided by that threshold floors to integral Skill Points. Consume thresholds even for discarded capped gains; healing retains residue and maximum-HP clamps add none. Preserve observed cause actor/ancestry, with the original owner selector choosing the receiving team. Transformations and waves retain residue; Won/Lost clears it. Shared checked operations roll back numeric faults, with no RNG. Hidden callback correspondence, capacity/rounding, overflow banking and gain attribution are independent low-confidence fields, not source parity."
HP_REPLACEMENT = "Alternatives are entry-max thresholds, percentage residue, including capacity clamps, healing reset, banking capped points or owner-sourced gain attribution. The selected fields reuse immutable shared event facts and bounded checked operations. Replace each field independently when released typed executable evidence or reproducible observations establish it. Command tests cover actual consumption/damage, shields, fractions/caps, healing, original Paths, independent owners, lifecycle, terminal reset, arithmetic rollback and fresh hashes. Equipment admission is not Forge, complete-run release or terminal reference coverage."
SKILL_POLICY_NOTE = "VersionedProjectPolicy: original entry-form Destruction/Remembrance only. Observe complete Skill ActionResolved at AfterAction, priority zero, once per Action, including nondamaging Skills. Add one permanent non-dispellable RefreshAndAddStacks Buff up to the exact cap, independent per original. Dynamic modifier-local stacks multiply the additive ratio with six-place Floor in Ordinary/DoT/Additional DamageBoost; only actual OriginalUnit producers qualify. Current Skill damage is not retroactively changed; Basic/Ultimate/FollowUp and linked/countdown actors add no layer. Waves and transformations retain stacks; explicit removal and Won/Lost tear down captures, and a fresh battle starts empty. Timing, calculator reach, retention and actor borrowing are independent low-confidence execution fields, not decoded source parity."
SKILL_REPLACEMENT = "Alternatives include declaration-time or same-Skill stacking, different damage-purpose sets, linked recipients, reset-on-transform/wave or different removal retention. The selected complete-action boundary and original ownership use shared events/effects/formulas, checked arithmetic and no RNG. Replace each field independently with released typed semantics or reproducible current observations. Command tests cover multi-hit versus one Skill, nondamaging Skills, caps, all original Paths, independent/inherited owners, actual damage, removal, terminal cleanup, invalid operands, numeric rollback and fresh hashes. Normal equipment admission is not Forge, full-run replay or terminal reference coverage."


def append_weighted_curio_footstep(data: dict[str, list[list[object]]]) -> None:
    for ordinal, suffix, locator, digest in [
        (134, "hex", "ExcelOutput/RogueTournHex.json; HexID=1011; TournMode=Tourn3; MazeBuffID=633411; AvatarType=Warrior,Memory", "51e91a6f53ab0545330e477d806a165108f6c7e5e70ad52b02f92c1dc4d36455"),
        (135, "maze-buff", "ExcelOutput/MazeBuff.json; ID=633411; Lv=1; ParamList=0.5,0.08,10; StageAbility_633411", "2fab98b723ee20d8798c68e200cc9c3704abc347b0983b2955cbd40b85bfeeac"),
        (136, "text-en", "TextMap/TextMapEN.json; hash=10599000866283908992; HP-loss point and Skill damage clauses", "afc6d0ff9eeb20d09042e61c311e60d4ed56e69757f1ac42466ca4840e6ed789"),
        (137, "text-zh", "TextMap/TextMapCHS.json; hash=10599000866283908992; HP-loss point and Skill damage clauses", "ec49e07932b4ed8aba9679e247d8e554ca69e831fea7931d94682551de567147"),
        (138, "program", "Config/ConfigAbility/Level/Rogue_S7/Level_RogueBuff_Ability_HEX_S7.json; Name=StageAbility_633411; Modifier_StageAbility_633411_Sub; OnListenHPChange,OnAfterSkillUse; AllDamageTypeAddedRatio", "5ad6c48751023184f5572e0069c5d02c841aef4de3cec092d0c2bc4913d17e47"),
    ]:
        data["Sources"].append([ordinal, f"du.source.weighted-curio-footstep.{suffix}",
            "https://gitlab.com/Dimbreath/turnbasedgamedata", "fd978d6ef09f941fba644c731ab54abd6f7c3568", "4.4", "2026-10-05",
            locator, digest, "ExactStructured", "Exact released joins, operands and named callback structure; hidden dynamic postfix and native timing parity are not inferred."])
    for ordinal, suffix, note, anchor in [(139, "hp-policy", HP_POLICY_NOTE, "independently-replaceable-execution-policy"), (140, "skill-policy", SKILL_POLICY_NOTE, "after-skill-damage-policy")]:
        data["Sources"].append([ordinal, f"du.source.weighted-curio-footstep.{suffix}",
            "https://gitlab.com/Dimbreath/turnbasedgamedata", "fd978d6ef09f941fba644c731ab54abd6f7c3568", "4.4", "2026-10-05",
            f"docs/divergent-universe-weighted-curio-footstep.md#{anchor}", sha256(note.encode("utf-8")).hexdigest(), "ProjectPolicy", f"Digest binds the corresponding {suffix} note in WeightedCurioFootsteps, not an upstream blob. See the independently replaceable execution fields and replacement conditions."])
    data["WeightedCurioFootsteps"] = [[1, "du.weighted-curio-footstep.footstep-of-gods", "divergent-universe.weighted-curio.1011", "633411", "Warrior|Memory",
        1, "0.5", 2, "0.08", 3, 10, "EffectiveHpLossAfterSkillOriginalDamage",
        "Destruction/Remembrance originals gain Skill Points from cumulative HP loss and stack a damage bonus after Skills.",
        "毁灭／记忆原角色累计降低生命值获得战技点，战技结束后叠加伤害增益。",
        HP_POLICY_NOTE, HP_REPLACEMENT, SKILL_POLICY_NOTE, SKILL_REPLACEMENT, "134|135|136|137|138|139|140"]]
