// This file was generated by Sora. Do not edit manually.
use super::SoraMap;
use super::gold_gears_coverage_state::GoldGearsCoverageState;
use super::gold_gears_evidence_quality::GoldGearsEvidenceQuality;
use super::gold_gears_ownership::GoldGearsOwnership;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GoldGearsService {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "stable_key")]
    pub stable_key: String,
    #[serde(rename = "schema_revision")]
    pub schema_revision: String,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "name_en")]
    pub name_en: String,
    #[serde(rename = "name_zh_cn")]
    pub name_zh_cn: String,
    #[serde(rename = "summary_en")]
    pub summary_en: String,
    #[serde(rename = "summary_zh_cn")]
    pub summary_zh_cn: String,
    #[serde(rename = "ownership")]
    pub ownership: GoldGearsOwnership,
    #[serde(rename = "coverage_state")]
    pub coverage_state: GoldGearsCoverageState,
    #[serde(rename = "evidence_quality")]
    pub evidence_quality: GoldGearsEvidenceQuality,
    #[serde(rename = "source_refs")]
    pub source_refs: Option<Vec<String>>,
    #[serde(rename = "tags")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "source_ids")]
    pub source_ids: Vec<String>,
    #[serde(rename = "source_mode_owner")]
    pub source_mode_owner: String,
    #[serde(rename = "service_kind")]
    pub service_kind: String,
    #[serde(rename = "currency_id")]
    pub currency_id: String,
    #[serde(rename = "price_formula_id")]
    pub price_formula_id: String,
    #[serde(rename = "inherited_offer_pool_id")]
    pub inherited_offer_pool_id: String,
    #[serde(rename = "inherited_rule_ids")]
    pub inherited_rule_ids: Option<Vec<String>>,
    #[serde(rename = "parameters_json")]
    pub parameters_json: String,
    #[serde(rename = "gold_gears_offer_rule_json")]
    pub gold_gears_offer_rule_json: String,
    #[serde(rename = "selection_policy_json")]
    pub selection_policy_json: String,
    #[serde(rename = "rule_contribution_id")]
    pub rule_contribution_id: String,
}

impl super::runtime::SoraDecode for GoldGearsService {
    fn decode(
        reader: &mut super::runtime::SoraReader<'_>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            stable_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            schema_revision: <String as super::runtime::SoraDecode>::decode(reader)?,
            kind: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            ownership: <GoldGearsOwnership as super::runtime::SoraDecode>::decode(reader)?,
            coverage_state: <GoldGearsCoverageState as super::runtime::SoraDecode>::decode(reader)?,
            evidence_quality: <GoldGearsEvidenceQuality as super::runtime::SoraDecode>::decode(
                reader,
            )?,
            source_refs: <Option<Vec<String>> as super::runtime::SoraDecode>::decode(reader)?,
            tags: <Option<Vec<String>> as super::runtime::SoraDecode>::decode(reader)?,
            source_ids: <Vec<String> as super::runtime::SoraDecode>::decode(reader)?,
            source_mode_owner: <String as super::runtime::SoraDecode>::decode(reader)?,
            service_kind: <String as super::runtime::SoraDecode>::decode(reader)?,
            currency_id: <String as super::runtime::SoraDecode>::decode(reader)?,
            price_formula_id: <String as super::runtime::SoraDecode>::decode(reader)?,
            inherited_offer_pool_id: <String as super::runtime::SoraDecode>::decode(reader)?,
            inherited_rule_ids: <Option<Vec<String>> as super::runtime::SoraDecode>::decode(
                reader,
            )?,
            parameters_json: <String as super::runtime::SoraDecode>::decode(reader)?,
            gold_gears_offer_rule_json: <String as super::runtime::SoraDecode>::decode(reader)?,
            selection_policy_json: <String as super::runtime::SoraDecode>::decode(reader)?,
            rule_contribution_id: <String as super::runtime::SoraDecode>::decode(reader)?,
        })
    }
}

impl GoldGearsService {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct GoldGearsServiceTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, GoldGearsService>,
    by_stable_key: SoraMap<String, i32>,
}

impl GoldGearsServiceTable {
    pub const NAME: &'static str = "GoldGearsService";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "GoldGearsService",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[super::SoraIndexInfo {
            name: "by_stable_key",
            unique: true,
            fields: &["stable_key"],
        }],
    };

    pub(super) fn from_rows(
        rows: Vec<GoldGearsService>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        let by_stable_key =
            super::build_unique_map_index(rows.iter(), |row| row.stable_key.clone(), |row| row.id);
        let rows = super::decode_map_table(rows, |row| row.id);
        Ok(Self {
            keys,
            rows,
            by_stable_key,
        })
    }

    pub fn get(&self, key: &i32) -> Option<&GoldGearsService> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &GoldGearsService> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
    pub fn get_by_stable_key(&self, stable_key: &str) -> Option<&GoldGearsService> {
        self.by_stable_key
            .get(stable_key)
            .and_then(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for GoldGearsServiceTable {
    type Target = SoraMap<i32, GoldGearsService>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for GoldGearsServiceTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for GoldGearsServiceTable {
    type Key = i32;
    type Row = GoldGearsService;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
