// This file was generated by Sora. Do not edit manually.
use super::SoraMap;
use super::gold_gears_coverage_state::GoldGearsCoverageState;
use super::gold_gears_evidence_quality::GoldGearsEvidenceQuality;
use super::gold_gears_ownership::GoldGearsOwnership;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GoldGearsDiceDefinition {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "stable_key")]
    pub stable_key: String,
    #[serde(rename = "schema_revision")]
    pub schema_revision: String,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "name_en")]
    pub name_en: String,
    #[serde(rename = "name_zh_cn")]
    pub name_zh_cn: String,
    #[serde(rename = "summary_en")]
    pub summary_en: String,
    #[serde(rename = "summary_zh_cn")]
    pub summary_zh_cn: String,
    #[serde(rename = "ownership")]
    pub ownership: GoldGearsOwnership,
    #[serde(rename = "coverage_state")]
    pub coverage_state: GoldGearsCoverageState,
    #[serde(rename = "evidence_quality")]
    pub evidence_quality: GoldGearsEvidenceQuality,
    #[serde(rename = "source_refs")]
    pub source_refs: Option<Vec<String>>,
    #[serde(rename = "tags")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "source_id")]
    pub source_id: String,
    #[serde(rename = "sort")]
    pub sort: i32,
    #[serde(rename = "category_id")]
    pub category_id: i32,
    #[serde(rename = "category_source_id")]
    pub category_source_id: String,
    #[serde(rename = "name_text_hash")]
    pub name_text_hash: String,
    #[serde(rename = "introduction_text_hash")]
    pub introduction_text_hash: String,
    #[serde(rename = "effect_bundle_text_hash")]
    pub effect_bundle_text_hash: String,
    #[serde(rename = "effect_parts_json")]
    pub effect_parts_json: String,
    #[serde(rename = "initial_effect_extra_ids")]
    pub initial_effect_extra_ids: Option<Vec<String>>,
    #[serde(rename = "passive_effect_extra_ids")]
    pub passive_effect_extra_ids: Option<Vec<String>>,
    #[serde(rename = "starting_effect_toast_text_hash")]
    pub starting_effect_toast_text_hash: String,
    #[serde(rename = "available_by_default")]
    pub available_by_default: bool,
    #[serde(rename = "unlock_id")]
    pub unlock_id: Option<String>,
    #[serde(rename = "default_ultra_surface_id")]
    pub default_ultra_surface_id: String,
    #[serde(rename = "default_common_surface_ids")]
    pub default_common_surface_ids: Vec<String>,
    #[serde(rename = "default_surface_ids")]
    pub default_surface_ids: Vec<String>,
    #[serde(rename = "suggestive_surface_ids")]
    pub suggestive_surface_ids: Option<Vec<String>>,
    #[serde(rename = "recommended_surface_ids")]
    pub recommended_surface_ids: Option<Vec<String>>,
    #[serde(rename = "dice_icon_path")]
    pub dice_icon_path: String,
}

impl super::runtime::SoraDecode for GoldGearsDiceDefinition {
    fn decode(
        reader: &mut super::runtime::SoraReader<'_>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            stable_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            schema_revision: <String as super::runtime::SoraDecode>::decode(reader)?,
            kind: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            ownership: <GoldGearsOwnership as super::runtime::SoraDecode>::decode(reader)?,
            coverage_state: <GoldGearsCoverageState as super::runtime::SoraDecode>::decode(reader)?,
            evidence_quality: <GoldGearsEvidenceQuality as super::runtime::SoraDecode>::decode(
                reader,
            )?,
            source_refs: <Option<Vec<String>> as super::runtime::SoraDecode>::decode(reader)?,
            tags: <Option<Vec<String>> as super::runtime::SoraDecode>::decode(reader)?,
            source_id: <String as super::runtime::SoraDecode>::decode(reader)?,
            sort: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            category_id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            category_source_id: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_text_hash: <String as super::runtime::SoraDecode>::decode(reader)?,
            introduction_text_hash: <String as super::runtime::SoraDecode>::decode(reader)?,
            effect_bundle_text_hash: <String as super::runtime::SoraDecode>::decode(reader)?,
            effect_parts_json: <String as super::runtime::SoraDecode>::decode(reader)?,
            initial_effect_extra_ids: <Option<Vec<String>> as super::runtime::SoraDecode>::decode(
                reader,
            )?,
            passive_effect_extra_ids: <Option<Vec<String>> as super::runtime::SoraDecode>::decode(
                reader,
            )?,
            starting_effect_toast_text_hash: <String as super::runtime::SoraDecode>::decode(
                reader,
            )?,
            available_by_default: <bool as super::runtime::SoraDecode>::decode(reader)?,
            unlock_id: <Option<String> as super::runtime::SoraDecode>::decode(reader)?,
            default_ultra_surface_id: <String as super::runtime::SoraDecode>::decode(reader)?,
            default_common_surface_ids: <Vec<String> as super::runtime::SoraDecode>::decode(
                reader,
            )?,
            default_surface_ids: <Vec<String> as super::runtime::SoraDecode>::decode(reader)?,
            suggestive_surface_ids: <Option<Vec<String>> as super::runtime::SoraDecode>::decode(
                reader,
            )?,
            recommended_surface_ids: <Option<Vec<String>> as super::runtime::SoraDecode>::decode(
                reader,
            )?,
            dice_icon_path: <String as super::runtime::SoraDecode>::decode(reader)?,
        })
    }
}

impl GoldGearsDiceDefinition {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct GoldGearsDiceDefinitionTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, GoldGearsDiceDefinition>,
    by_stable_key: SoraMap<String, i32>,
}

impl GoldGearsDiceDefinitionTable {
    pub const NAME: &'static str = "GoldGearsDiceDefinition";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "GoldGearsDiceDefinition",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[super::SoraIndexInfo {
            name: "by_stable_key",
            unique: true,
            fields: &["stable_key"],
        }],
    };

    pub(super) fn from_rows(
        rows: Vec<GoldGearsDiceDefinition>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        let by_stable_key =
            super::build_unique_map_index(rows.iter(), |row| row.stable_key.clone(), |row| row.id);
        let rows = super::decode_map_table(rows, |row| row.id);
        Ok(Self {
            keys,
            rows,
            by_stable_key,
        })
    }

    pub fn get(&self, key: &i32) -> Option<&GoldGearsDiceDefinition> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &GoldGearsDiceDefinition> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
    pub fn get_by_stable_key(&self, stable_key: &str) -> Option<&GoldGearsDiceDefinition> {
        self.by_stable_key
            .get(stable_key)
            .and_then(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for GoldGearsDiceDefinitionTable {
    type Target = SoraMap<i32, GoldGearsDiceDefinition>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for GoldGearsDiceDefinitionTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for GoldGearsDiceDefinitionTable {
    type Key = i32;
    type Row = GoldGearsDiceDefinition;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
