// This file was generated by Sora. Do not edit manually.
use super::SoraMap;
use super::gold_gears_coverage_state::GoldGearsCoverageState;
use super::gold_gears_evidence_quality::GoldGearsEvidenceQuality;
use super::gold_gears_ownership::GoldGearsOwnership;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GoldGearsPath {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "stable_key")]
    pub stable_key: String,
    #[serde(rename = "schema_revision")]
    pub schema_revision: String,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "name_en")]
    pub name_en: String,
    #[serde(rename = "name_zh_cn")]
    pub name_zh_cn: String,
    #[serde(rename = "summary_en")]
    pub summary_en: String,
    #[serde(rename = "summary_zh_cn")]
    pub summary_zh_cn: String,
    #[serde(rename = "ownership")]
    pub ownership: GoldGearsOwnership,
    #[serde(rename = "coverage_state")]
    pub coverage_state: GoldGearsCoverageState,
    #[serde(rename = "evidence_quality")]
    pub evidence_quality: GoldGearsEvidenceQuality,
    #[serde(rename = "source_refs")]
    pub source_refs: Option<Vec<String>>,
    #[serde(rename = "tags")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "source_id")]
    pub source_id: String,
    #[serde(rename = "sort")]
    pub sort: i32,
    #[serde(rename = "buff_type")]
    pub buff_type: i32,
    #[serde(rename = "shared_resonance_id")]
    pub shared_resonance_id: i32,
    #[serde(rename = "shared_formation_ids")]
    pub shared_formation_ids: Vec<String>,
    #[serde(rename = "path_boost_id")]
    pub path_boost_id: i32,
    #[serde(rename = "normal_battle_event_group")]
    pub normal_battle_event_group: String,
    #[serde(rename = "enhanced_battle_event_group")]
    pub enhanced_battle_event_group: String,
}

impl super::runtime::SoraDecode for GoldGearsPath {
    fn decode(
        reader: &mut super::runtime::SoraReader<'_>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            stable_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            schema_revision: <String as super::runtime::SoraDecode>::decode(reader)?,
            kind: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            ownership: <GoldGearsOwnership as super::runtime::SoraDecode>::decode(reader)?,
            coverage_state: <GoldGearsCoverageState as super::runtime::SoraDecode>::decode(reader)?,
            evidence_quality: <GoldGearsEvidenceQuality as super::runtime::SoraDecode>::decode(
                reader,
            )?,
            source_refs: <Option<Vec<String>> as super::runtime::SoraDecode>::decode(reader)?,
            tags: <Option<Vec<String>> as super::runtime::SoraDecode>::decode(reader)?,
            source_id: <String as super::runtime::SoraDecode>::decode(reader)?,
            sort: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            buff_type: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            shared_resonance_id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            shared_formation_ids: <Vec<String> as super::runtime::SoraDecode>::decode(reader)?,
            path_boost_id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            normal_battle_event_group: <String as super::runtime::SoraDecode>::decode(reader)?,
            enhanced_battle_event_group: <String as super::runtime::SoraDecode>::decode(reader)?,
        })
    }
}

impl GoldGearsPath {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct GoldGearsPathTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, GoldGearsPath>,
    by_stable_key: SoraMap<String, i32>,
}

impl GoldGearsPathTable {
    pub const NAME: &'static str = "GoldGearsPath";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "GoldGearsPath",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[super::SoraIndexInfo {
            name: "by_stable_key",
            unique: true,
            fields: &["stable_key"],
        }],
    };

    pub(super) fn from_rows(
        rows: Vec<GoldGearsPath>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        let by_stable_key =
            super::build_unique_map_index(rows.iter(), |row| row.stable_key.clone(), |row| row.id);
        let rows = super::decode_map_table(rows, |row| row.id);
        Ok(Self {
            keys,
            rows,
            by_stable_key,
        })
    }

    pub fn get(&self, key: &i32) -> Option<&GoldGearsPath> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &GoldGearsPath> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
    pub fn get_by_stable_key(&self, stable_key: &str) -> Option<&GoldGearsPath> {
        self.by_stable_key
            .get(stable_key)
            .and_then(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for GoldGearsPathTable {
    type Target = SoraMap<i32, GoldGearsPath>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for GoldGearsPathTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for GoldGearsPathTable {
    type Key = i32;
    type Row = GoldGearsPath;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
