import path from "node:path";
import process from "node:process";
import { createContext, writeOrCheck } from "./lib/common.mjs";
import { topology } from "./lib/topology.mjs";
import { paths } from "./lib/paths.mjs";
import { blessings } from "./lib/blessings.mjs";
import { curios } from "./lib/curios.mjs";
import { occurrences } from "./lib/occurrences.mjs";
import { services } from "./lib/services.mjs";
import { abilityTree } from "./lib/ability-tree.mjs";

const args = process.argv.slice(2);
const check = args.includes("--check");
const root = path.resolve(args.find((argument) => !argument.startsWith("--")) ?? ".");
const ctx = await createContext(root);
const outputs = await topology(ctx);
for (const [name, value] of await paths(ctx)) outputs.set(name, value);
for (const [name, value] of await blessings(ctx)) outputs.set(name, value);
for (const [name, value] of await curios(ctx)) outputs.set(name, value);
for (const [name, value] of await occurrences(ctx)) outputs.set(name, value);
for (const [name, value] of await services(ctx)) outputs.set(name, value);
for (const [name, value] of await abilityTree(ctx)) outputs.set(name, value);
outputs.set("sources.json", [...ctx.evidence.values()].sort((left, right) => left.id.localeCompare(right.id)));
await writeOrCheck(ctx, outputs, check);
console.log(`Standard universe reference pack ${check ? "verified" : "generated"}: ${outputs.size} files, ${[...outputs.values()].reduce((sum, records) => sum + records.length, 0)} rows.`);
