// This file was generated by Sora. Do not edit manually.
use super::SoraMap;
use super::swarm_disaster_coverage_state::SwarmDisasterCoverageState;
use super::swarm_disaster_evidence_grade::SwarmDisasterEvidenceGrade;
use super::swarm_disaster_ownership::SwarmDisasterOwnership;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct SwarmDisasterRoom {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "stable_key")]
    pub stable_key: String,
    #[serde(rename = "schema_revision")]
    pub schema_revision: String,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "name_en")]
    pub name_en: String,
    #[serde(rename = "name_zh_cn")]
    pub name_zh_cn: String,
    #[serde(rename = "summary_en")]
    pub summary_en: String,
    #[serde(rename = "summary_zh_cn")]
    pub summary_zh_cn: String,
    #[serde(rename = "ownership")]
    pub ownership: SwarmDisasterOwnership,
    #[serde(rename = "coverage_state")]
    pub coverage_state: SwarmDisasterCoverageState,
    #[serde(rename = "evidence_quality")]
    pub evidence_quality: SwarmDisasterEvidenceGrade,
    #[serde(rename = "source_refs")]
    pub source_refs: Option<Vec<String>>,
    #[serde(rename = "tags")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "source_id")]
    pub source_id: String,
    #[serde(rename = "sub_mode")]
    pub sub_mode: String,
    #[serde(rename = "section_ids")]
    pub section_ids: Vec<String>,
    #[serde(rename = "domain_id")]
    pub domain_id: Option<i32>,
    #[serde(rename = "encounter_pool_ids")]
    pub encounter_pool_ids: Option<Vec<String>>,
    #[serde(rename = "domain_binding_state")]
    pub domain_binding_state: String,
    #[serde(rename = "encounter_binding_state")]
    pub encounter_binding_state: String,
}

impl super::runtime::SoraDecode for SwarmDisasterRoom {
    fn decode(
        reader: &mut super::runtime::SoraReader<'_>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            stable_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            schema_revision: <String as super::runtime::SoraDecode>::decode(reader)?,
            kind: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            ownership: <SwarmDisasterOwnership as super::runtime::SoraDecode>::decode(reader)?,
            coverage_state: <SwarmDisasterCoverageState as super::runtime::SoraDecode>::decode(
                reader,
            )?,
            evidence_quality: <SwarmDisasterEvidenceGrade as super::runtime::SoraDecode>::decode(
                reader,
            )?,
            source_refs: <Option<Vec<String>> as super::runtime::SoraDecode>::decode(reader)?,
            tags: <Option<Vec<String>> as super::runtime::SoraDecode>::decode(reader)?,
            source_id: <String as super::runtime::SoraDecode>::decode(reader)?,
            sub_mode: <String as super::runtime::SoraDecode>::decode(reader)?,
            section_ids: <Vec<String> as super::runtime::SoraDecode>::decode(reader)?,
            domain_id: <Option<i32> as super::runtime::SoraDecode>::decode(reader)?,
            encounter_pool_ids: <Option<Vec<String>> as super::runtime::SoraDecode>::decode(
                reader,
            )?,
            domain_binding_state: <String as super::runtime::SoraDecode>::decode(reader)?,
            encounter_binding_state: <String as super::runtime::SoraDecode>::decode(reader)?,
        })
    }
}

impl SwarmDisasterRoom {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct SwarmDisasterRoomTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, SwarmDisasterRoom>,
    by_stable_key: SoraMap<String, i32>,
}

impl SwarmDisasterRoomTable {
    pub const NAME: &'static str = "SwarmDisasterRoom";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "SwarmDisasterRoom",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[super::SoraIndexInfo {
            name: "by_stable_key",
            unique: true,
            fields: &["stable_key"],
        }],
    };

    pub(super) fn from_rows(
        rows: Vec<SwarmDisasterRoom>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        let by_stable_key =
            super::build_unique_map_index(rows.iter(), |row| row.stable_key.clone(), |row| row.id);
        let rows = super::decode_map_table(rows, |row| row.id);
        Ok(Self {
            keys,
            rows,
            by_stable_key,
        })
    }

    pub fn get(&self, key: &i32) -> Option<&SwarmDisasterRoom> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &SwarmDisasterRoom> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
    pub fn get_by_stable_key(&self, stable_key: &str) -> Option<&SwarmDisasterRoom> {
        self.by_stable_key
            .get(stable_key)
            .and_then(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for SwarmDisasterRoomTable {
    type Target = SoraMap<i32, SwarmDisasterRoom>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for SwarmDisasterRoomTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for SwarmDisasterRoomTable {
    type Key = i32;
    type Row = SwarmDisasterRoom;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
