// This file was generated by Sora. Do not edit manually.
use super::SoraMap;
use super::swarm_disaster_coverage_state::SwarmDisasterCoverageState;
use super::swarm_disaster_evidence_grade::SwarmDisasterEvidenceGrade;
use super::swarm_disaster_ownership::SwarmDisasterOwnership;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct SwarmDisasterMechanicRule {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "stable_key")]
    pub stable_key: String,
    #[serde(rename = "schema_revision")]
    pub schema_revision: String,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "name_en")]
    pub name_en: String,
    #[serde(rename = "name_zh_cn")]
    pub name_zh_cn: String,
    #[serde(rename = "summary_en")]
    pub summary_en: String,
    #[serde(rename = "summary_zh_cn")]
    pub summary_zh_cn: String,
    #[serde(rename = "ownership")]
    pub ownership: SwarmDisasterOwnership,
    #[serde(rename = "coverage_state")]
    pub coverage_state: SwarmDisasterCoverageState,
    #[serde(rename = "evidence_quality")]
    pub evidence_quality: SwarmDisasterEvidenceGrade,
    #[serde(rename = "source_refs")]
    pub source_refs: Option<Vec<String>>,
    #[serde(rename = "tags")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "family_id")]
    pub family_id: String,
    #[serde(rename = "domain")]
    pub domain: String,
    #[serde(rename = "triggers")]
    pub triggers: Vec<String>,
    #[serde(rename = "state_slots_json")]
    pub state_slots_json: String,
    #[serde(rename = "program_json")]
    pub program_json: String,
    #[serde(rename = "fixture_ids")]
    pub fixture_ids: Vec<String>,
    #[serde(rename = "execution_disposition")]
    pub execution_disposition: String,
    #[serde(rename = "runtime_handler_id")]
    pub runtime_handler_id: Option<String>,
}

impl super::runtime::SoraDecode for SwarmDisasterMechanicRule {
    fn decode(
        reader: &mut super::runtime::SoraReader<'_>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            stable_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            schema_revision: <String as super::runtime::SoraDecode>::decode(reader)?,
            kind: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            ownership: <SwarmDisasterOwnership as super::runtime::SoraDecode>::decode(reader)?,
            coverage_state: <SwarmDisasterCoverageState as super::runtime::SoraDecode>::decode(
                reader,
            )?,
            evidence_quality: <SwarmDisasterEvidenceGrade as super::runtime::SoraDecode>::decode(
                reader,
            )?,
            source_refs: <Option<Vec<String>> as super::runtime::SoraDecode>::decode(reader)?,
            tags: <Option<Vec<String>> as super::runtime::SoraDecode>::decode(reader)?,
            family_id: <String as super::runtime::SoraDecode>::decode(reader)?,
            domain: <String as super::runtime::SoraDecode>::decode(reader)?,
            triggers: <Vec<String> as super::runtime::SoraDecode>::decode(reader)?,
            state_slots_json: <String as super::runtime::SoraDecode>::decode(reader)?,
            program_json: <String as super::runtime::SoraDecode>::decode(reader)?,
            fixture_ids: <Vec<String> as super::runtime::SoraDecode>::decode(reader)?,
            execution_disposition: <String as super::runtime::SoraDecode>::decode(reader)?,
            runtime_handler_id: <Option<String> as super::runtime::SoraDecode>::decode(reader)?,
        })
    }
}

impl SwarmDisasterMechanicRule {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct SwarmDisasterMechanicRuleTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, SwarmDisasterMechanicRule>,
    by_stable_key: SoraMap<String, i32>,
}

impl SwarmDisasterMechanicRuleTable {
    pub const NAME: &'static str = "SwarmDisasterMechanicRule";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "SwarmDisasterMechanicRule",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[super::SoraIndexInfo {
            name: "by_stable_key",
            unique: true,
            fields: &["stable_key"],
        }],
    };

    pub(super) fn from_rows(
        rows: Vec<SwarmDisasterMechanicRule>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        let by_stable_key =
            super::build_unique_map_index(rows.iter(), |row| row.stable_key.clone(), |row| row.id);
        let rows = super::decode_map_table(rows, |row| row.id);
        Ok(Self {
            keys,
            rows,
            by_stable_key,
        })
    }

    pub fn get(&self, key: &i32) -> Option<&SwarmDisasterMechanicRule> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &SwarmDisasterMechanicRule> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
    pub fn get_by_stable_key(&self, stable_key: &str) -> Option<&SwarmDisasterMechanicRule> {
        self.by_stable_key
            .get(stable_key)
            .and_then(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for SwarmDisasterMechanicRuleTable {
    type Target = SoraMap<i32, SwarmDisasterMechanicRule>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for SwarmDisasterMechanicRuleTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for SwarmDisasterMechanicRuleTable {
    type Key = i32;
    type Row = SwarmDisasterMechanicRule;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
