// This file was generated by Sora. Do not edit manually.
use super::SoraMap;
use super::swarm_disaster_coverage_state::SwarmDisasterCoverageState;
use super::swarm_disaster_evidence_grade::SwarmDisasterEvidenceGrade;
use super::swarm_disaster_ownership::SwarmDisasterOwnership;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct SwarmDisasterCountdownDisarray {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "stable_key")]
    pub stable_key: String,
    #[serde(rename = "schema_revision")]
    pub schema_revision: String,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "name_en")]
    pub name_en: String,
    #[serde(rename = "name_zh_cn")]
    pub name_zh_cn: String,
    #[serde(rename = "summary_en")]
    pub summary_en: String,
    #[serde(rename = "summary_zh_cn")]
    pub summary_zh_cn: String,
    #[serde(rename = "ownership")]
    pub ownership: SwarmDisasterOwnership,
    #[serde(rename = "coverage_state")]
    pub coverage_state: SwarmDisasterCoverageState,
    #[serde(rename = "evidence_quality")]
    pub evidence_quality: SwarmDisasterEvidenceGrade,
    #[serde(rename = "source_refs")]
    pub source_refs: Option<Vec<String>>,
    #[serde(rename = "tags")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "initial_value")]
    pub initial_value: String,
    #[serde(rename = "initial_value_quality")]
    pub initial_value_quality: String,
    #[serde(rename = "movement_delta")]
    pub movement_delta: String,
    #[serde(rename = "movement_delta_quality")]
    pub movement_delta_quality: String,
    #[serde(rename = "carry_policy")]
    pub carry_policy: String,
    #[serde(rename = "transition_boundary")]
    pub transition_boundary: String,
    #[serde(rename = "transition_result")]
    pub transition_result: String,
    #[serde(rename = "warning_threshold")]
    pub warning_threshold: String,
    #[serde(rename = "same_boundary_order")]
    pub same_boundary_order: String,
    #[serde(rename = "cap_policy")]
    pub cap_policy: String,
    #[serde(rename = "disarray_tiers_json")]
    pub disarray_tiers_json: String,
    #[serde(rename = "source_constant_bindings_json")]
    pub source_constant_bindings_json: String,
}

impl super::runtime::SoraDecode for SwarmDisasterCountdownDisarray {
    fn decode(
        reader: &mut super::runtime::SoraReader<'_>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            stable_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            schema_revision: <String as super::runtime::SoraDecode>::decode(reader)?,
            kind: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            ownership: <SwarmDisasterOwnership as super::runtime::SoraDecode>::decode(reader)?,
            coverage_state: <SwarmDisasterCoverageState as super::runtime::SoraDecode>::decode(
                reader,
            )?,
            evidence_quality: <SwarmDisasterEvidenceGrade as super::runtime::SoraDecode>::decode(
                reader,
            )?,
            source_refs: <Option<Vec<String>> as super::runtime::SoraDecode>::decode(reader)?,
            tags: <Option<Vec<String>> as super::runtime::SoraDecode>::decode(reader)?,
            initial_value: <String as super::runtime::SoraDecode>::decode(reader)?,
            initial_value_quality: <String as super::runtime::SoraDecode>::decode(reader)?,
            movement_delta: <String as super::runtime::SoraDecode>::decode(reader)?,
            movement_delta_quality: <String as super::runtime::SoraDecode>::decode(reader)?,
            carry_policy: <String as super::runtime::SoraDecode>::decode(reader)?,
            transition_boundary: <String as super::runtime::SoraDecode>::decode(reader)?,
            transition_result: <String as super::runtime::SoraDecode>::decode(reader)?,
            warning_threshold: <String as super::runtime::SoraDecode>::decode(reader)?,
            same_boundary_order: <String as super::runtime::SoraDecode>::decode(reader)?,
            cap_policy: <String as super::runtime::SoraDecode>::decode(reader)?,
            disarray_tiers_json: <String as super::runtime::SoraDecode>::decode(reader)?,
            source_constant_bindings_json: <String as super::runtime::SoraDecode>::decode(reader)?,
        })
    }
}

impl SwarmDisasterCountdownDisarray {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct SwarmDisasterCountdownDisarrayTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, SwarmDisasterCountdownDisarray>,
    by_stable_key: SoraMap<String, i32>,
}

impl SwarmDisasterCountdownDisarrayTable {
    pub const NAME: &'static str = "SwarmDisasterCountdownDisarray";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "SwarmDisasterCountdownDisarray",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[super::SoraIndexInfo {
            name: "by_stable_key",
            unique: true,
            fields: &["stable_key"],
        }],
    };

    pub(super) fn from_rows(
        rows: Vec<SwarmDisasterCountdownDisarray>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        let by_stable_key =
            super::build_unique_map_index(rows.iter(), |row| row.stable_key.clone(), |row| row.id);
        let rows = super::decode_map_table(rows, |row| row.id);
        Ok(Self {
            keys,
            rows,
            by_stable_key,
        })
    }

    pub fn get(&self, key: &i32) -> Option<&SwarmDisasterCountdownDisarray> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &SwarmDisasterCountdownDisarray> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
    pub fn get_by_stable_key(&self, stable_key: &str) -> Option<&SwarmDisasterCountdownDisarray> {
        self.by_stable_key
            .get(stable_key)
            .and_then(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for SwarmDisasterCountdownDisarrayTable {
    type Target = SoraMap<i32, SwarmDisasterCountdownDisarray>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for SwarmDisasterCountdownDisarrayTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for SwarmDisasterCountdownDisarrayTable {
    type Key = i32;
    type Row = SwarmDisasterCountdownDisarray;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
