// This file was generated by Sora. Do not edit manually.
use super::SoraMap;
use super::swarm_disaster_coverage_state::SwarmDisasterCoverageState;
use super::swarm_disaster_evidence_grade::SwarmDisasterEvidenceGrade;
use super::swarm_disaster_ownership::SwarmDisasterOwnership;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct SwarmDisasterEncounterGroup {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "stable_key")]
    pub stable_key: String,
    #[serde(rename = "schema_revision")]
    pub schema_revision: String,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "name_en")]
    pub name_en: String,
    #[serde(rename = "name_zh_cn")]
    pub name_zh_cn: String,
    #[serde(rename = "summary_en")]
    pub summary_en: String,
    #[serde(rename = "summary_zh_cn")]
    pub summary_zh_cn: String,
    #[serde(rename = "ownership")]
    pub ownership: SwarmDisasterOwnership,
    #[serde(rename = "coverage_state")]
    pub coverage_state: SwarmDisasterCoverageState,
    #[serde(rename = "evidence_quality")]
    pub evidence_quality: SwarmDisasterEvidenceGrade,
    #[serde(rename = "source_refs")]
    pub source_refs: Option<Vec<String>>,
    #[serde(rename = "tags")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "room_id")]
    pub room_id: Option<String>,
    #[serde(rename = "room_scope_json")]
    pub room_scope_json: String,
    #[serde(rename = "source_group_id")]
    pub source_group_id: String,
    #[serde(rename = "source_namespace")]
    pub source_namespace: String,
    #[serde(rename = "encounter_role")]
    pub encounter_role: String,
    #[serde(rename = "eligible_area_ids")]
    pub eligible_area_ids: Option<Vec<String>>,
    #[serde(rename = "displayed_boss_choice_ids")]
    pub displayed_boss_choice_ids: Option<Vec<String>>,
    #[serde(rename = "difficulty_binding_json")]
    pub difficulty_binding_json: String,
    #[serde(rename = "weighted_members_json")]
    pub weighted_members_json: String,
    #[serde(rename = "wave_ids")]
    pub wave_ids: Vec<String>,
    #[serde(rename = "weight_policy_json")]
    pub weight_policy_json: String,
}

impl super::runtime::SoraDecode for SwarmDisasterEncounterGroup {
    fn decode(
        reader: &mut super::runtime::SoraReader<'_>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            stable_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            schema_revision: <String as super::runtime::SoraDecode>::decode(reader)?,
            kind: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            ownership: <SwarmDisasterOwnership as super::runtime::SoraDecode>::decode(reader)?,
            coverage_state: <SwarmDisasterCoverageState as super::runtime::SoraDecode>::decode(
                reader,
            )?,
            evidence_quality: <SwarmDisasterEvidenceGrade as super::runtime::SoraDecode>::decode(
                reader,
            )?,
            source_refs: <Option<Vec<String>> as super::runtime::SoraDecode>::decode(reader)?,
            tags: <Option<Vec<String>> as super::runtime::SoraDecode>::decode(reader)?,
            room_id: <Option<String> as super::runtime::SoraDecode>::decode(reader)?,
            room_scope_json: <String as super::runtime::SoraDecode>::decode(reader)?,
            source_group_id: <String as super::runtime::SoraDecode>::decode(reader)?,
            source_namespace: <String as super::runtime::SoraDecode>::decode(reader)?,
            encounter_role: <String as super::runtime::SoraDecode>::decode(reader)?,
            eligible_area_ids: <Option<Vec<String>> as super::runtime::SoraDecode>::decode(reader)?,
            displayed_boss_choice_ids: <Option<Vec<String>> as super::runtime::SoraDecode>::decode(
                reader,
            )?,
            difficulty_binding_json: <String as super::runtime::SoraDecode>::decode(reader)?,
            weighted_members_json: <String as super::runtime::SoraDecode>::decode(reader)?,
            wave_ids: <Vec<String> as super::runtime::SoraDecode>::decode(reader)?,
            weight_policy_json: <String as super::runtime::SoraDecode>::decode(reader)?,
        })
    }
}

impl SwarmDisasterEncounterGroup {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct SwarmDisasterEncounterGroupTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, SwarmDisasterEncounterGroup>,
    by_stable_key: SoraMap<String, i32>,
}

impl SwarmDisasterEncounterGroupTable {
    pub const NAME: &'static str = "SwarmDisasterEncounterGroup";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "SwarmDisasterEncounterGroup",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[super::SoraIndexInfo {
            name: "by_stable_key",
            unique: true,
            fields: &["stable_key"],
        }],
    };

    pub(super) fn from_rows(
        rows: Vec<SwarmDisasterEncounterGroup>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        let by_stable_key =
            super::build_unique_map_index(rows.iter(), |row| row.stable_key.clone(), |row| row.id);
        let rows = super::decode_map_table(rows, |row| row.id);
        Ok(Self {
            keys,
            rows,
            by_stable_key,
        })
    }

    pub fn get(&self, key: &i32) -> Option<&SwarmDisasterEncounterGroup> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &SwarmDisasterEncounterGroup> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
    pub fn get_by_stable_key(&self, stable_key: &str) -> Option<&SwarmDisasterEncounterGroup> {
        self.by_stable_key
            .get(stable_key)
            .and_then(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for SwarmDisasterEncounterGroupTable {
    type Target = SoraMap<i32, SwarmDisasterEncounterGroup>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for SwarmDisasterEncounterGroupTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for SwarmDisasterEncounterGroupTable {
    type Key = i32;
    type Row = SwarmDisasterEncounterGroup;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
