// This file was generated by Sora. Do not edit manually.
use super::SoraMap;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GbAccessoryLevels {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "stable_key")]
    pub stable_key: String,
    #[serde(rename = "schema_revision")]
    pub schema_revision: String,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "name_en")]
    pub name_en: String,
    #[serde(rename = "name_zh_cn")]
    pub name_zh_cn: String,
    #[serde(rename = "summary_en")]
    pub summary_en: String,
    #[serde(rename = "summary_zh_cn")]
    pub summary_zh_cn: String,
    #[serde(rename = "profile_ids")]
    pub profile_ids: String,
    #[serde(rename = "ownership")]
    pub ownership: String,
    #[serde(rename = "coverage_state")]
    pub coverage_state: String,
    #[serde(rename = "evidence_quality")]
    pub evidence_quality: String,
    #[serde(rename = "mechanism_quality")]
    pub mechanism_quality: String,
    #[serde(rename = "manifest_record_ids")]
    pub manifest_record_ids: String,
    #[serde(rename = "source_refs")]
    pub source_refs: String,
    #[serde(rename = "tags")]
    pub tags: String,
    #[serde(rename = "binding_key")]
    pub binding_key: String,
    #[serde(rename = "buff_battle_description_hash")]
    pub buff_battle_description_hash: String,
    #[serde(rename = "buff_description_hash")]
    pub buff_description_hash: String,
    #[serde(rename = "buff_name_hash")]
    pub buff_name_hash: String,
    #[serde(rename = "buff_rarity")]
    pub buff_rarity: String,
    #[serde(rename = "buff_series")]
    pub buff_series: String,
    #[serde(rename = "buff_simple_description_hash")]
    pub buff_simple_description_hash: String,
    #[serde(rename = "dynamic_index_list")]
    pub dynamic_index_list: String,
    #[serde(rename = "index_list")]
    pub index_list: String,
    #[serde(rename = "level")]
    pub level: String,
    #[serde(rename = "maze_buff_id")]
    pub maze_buff_id: String,
    #[serde(rename = "maze_buff_type")]
    pub maze_buff_type: String,
    #[serde(rename = "modifier_name")]
    pub modifier_name: String,
    #[serde(rename = "parameter_values")]
    pub parameter_values: String,
    #[serde(rename = "parent_id")]
    pub parent_id: String,
    #[serde(rename = "released_correction_ids")]
    pub released_correction_ids: Option<String>,
    #[serde(rename = "simple_index_list")]
    pub simple_index_list: String,
}

impl super::runtime::SoraDecode for GbAccessoryLevels {
    fn decode(reader: &mut super::runtime::SoraReader<'_>) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            stable_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            schema_revision: <String as super::runtime::SoraDecode>::decode(reader)?,
            kind: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            profile_ids: <String as super::runtime::SoraDecode>::decode(reader)?,
            ownership: <String as super::runtime::SoraDecode>::decode(reader)?,
            coverage_state: <String as super::runtime::SoraDecode>::decode(reader)?,
            evidence_quality: <String as super::runtime::SoraDecode>::decode(reader)?,
            mechanism_quality: <String as super::runtime::SoraDecode>::decode(reader)?,
            manifest_record_ids: <String as super::runtime::SoraDecode>::decode(reader)?,
            source_refs: <String as super::runtime::SoraDecode>::decode(reader)?,
            tags: <String as super::runtime::SoraDecode>::decode(reader)?,
            binding_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            buff_battle_description_hash: <String as super::runtime::SoraDecode>::decode(reader)?,
            buff_description_hash: <String as super::runtime::SoraDecode>::decode(reader)?,
            buff_name_hash: <String as super::runtime::SoraDecode>::decode(reader)?,
            buff_rarity: <String as super::runtime::SoraDecode>::decode(reader)?,
            buff_series: <String as super::runtime::SoraDecode>::decode(reader)?,
            buff_simple_description_hash: <String as super::runtime::SoraDecode>::decode(reader)?,
            dynamic_index_list: <String as super::runtime::SoraDecode>::decode(reader)?,
            index_list: <String as super::runtime::SoraDecode>::decode(reader)?,
            level: <String as super::runtime::SoraDecode>::decode(reader)?,
            maze_buff_id: <String as super::runtime::SoraDecode>::decode(reader)?,
            maze_buff_type: <String as super::runtime::SoraDecode>::decode(reader)?,
            modifier_name: <String as super::runtime::SoraDecode>::decode(reader)?,
            parameter_values: <String as super::runtime::SoraDecode>::decode(reader)?,
            parent_id: <String as super::runtime::SoraDecode>::decode(reader)?,
            released_correction_ids: <Option<String> as super::runtime::SoraDecode>::decode(reader)?,
            simple_index_list: <String as super::runtime::SoraDecode>::decode(reader)?,
        })
    }
}

impl GbAccessoryLevels {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct GbAccessoryLevelsTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, GbAccessoryLevels>,
    by_stable_key: SoraMap<String, i32>,
}

impl GbAccessoryLevelsTable {
    pub const NAME: &'static str = "GbAccessoryLevels";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "GbAccessoryLevels",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[
            super::SoraIndexInfo {
                name: "by_stable_key",
                unique: true,
                fields: &["stable_key"],
            },
        ],
    };

    pub(super) fn from_rows(rows: Vec<GbAccessoryLevels>) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        let by_stable_key = super::build_unique_map_index(
            rows.iter(),
            |row| row.stable_key.clone(),
            |row| row.id,
        );
        let rows = super::decode_map_table(rows, |row| row.id);
        Ok(Self {
            keys,
            rows,
            by_stable_key,
        })
    }

    pub fn get(&self, key: &i32) -> Option<&GbAccessoryLevels> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &GbAccessoryLevels> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
    pub fn get_by_stable_key(&self, stable_key: &str) -> Option<&GbAccessoryLevels> {
        self.by_stable_key.get(stable_key).and_then(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for GbAccessoryLevelsTable {
    type Target = SoraMap<i32, GbAccessoryLevels>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for GbAccessoryLevelsTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for GbAccessoryLevelsTable {
    type Key = i32;
    type Row = GbAccessoryLevels;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
