// This file was generated by Sora. Do not edit manually.
use super::SoraMap;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GbCandidatePools {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "stable_key")]
    pub stable_key: String,
    #[serde(rename = "schema_revision")]
    pub schema_revision: String,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "name_en")]
    pub name_en: String,
    #[serde(rename = "name_zh_cn")]
    pub name_zh_cn: String,
    #[serde(rename = "summary_en")]
    pub summary_en: String,
    #[serde(rename = "summary_zh_cn")]
    pub summary_zh_cn: String,
    #[serde(rename = "profile_ids")]
    pub profile_ids: String,
    #[serde(rename = "ownership")]
    pub ownership: String,
    #[serde(rename = "coverage_state")]
    pub coverage_state: String,
    #[serde(rename = "evidence_quality")]
    pub evidence_quality: String,
    #[serde(rename = "mechanism_quality")]
    pub mechanism_quality: String,
    #[serde(rename = "manifest_record_ids")]
    pub manifest_record_ids: String,
    #[serde(rename = "source_refs")]
    pub source_refs: String,
    #[serde(rename = "tags")]
    pub tags: String,
    #[serde(rename = "candidate_ids")]
    pub candidate_ids: Option<String>,
    #[serde(rename = "card_parameters")]
    pub card_parameters: Option<String>,
    #[serde(rename = "maze_buff_id")]
    pub maze_buff_id: Option<String>,
    #[serde(rename = "maze_buff_parameters")]
    pub maze_buff_parameters: Option<String>,
    #[serde(rename = "pool_order")]
    pub pool_order: Option<String>,
    #[serde(rename = "program_summary")]
    pub program_summary: Option<String>,
    #[serde(rename = "selectable_period_ids")]
    pub selectable_period_ids: Option<String>,
    #[serde(rename = "source_level_id")]
    pub source_level_id: Option<String>,
    #[serde(rename = "source_name_hash")]
    pub source_name_hash: Option<String>,
    #[serde(rename = "source_numeric_id")]
    pub source_numeric_id: Option<String>,
    #[serde(rename = "strategy_type")]
    pub strategy_type: String,
}

impl super::runtime::SoraDecode for GbCandidatePools {
    fn decode(reader: &mut super::runtime::SoraReader<'_>) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            stable_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            schema_revision: <String as super::runtime::SoraDecode>::decode(reader)?,
            kind: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            profile_ids: <String as super::runtime::SoraDecode>::decode(reader)?,
            ownership: <String as super::runtime::SoraDecode>::decode(reader)?,
            coverage_state: <String as super::runtime::SoraDecode>::decode(reader)?,
            evidence_quality: <String as super::runtime::SoraDecode>::decode(reader)?,
            mechanism_quality: <String as super::runtime::SoraDecode>::decode(reader)?,
            manifest_record_ids: <String as super::runtime::SoraDecode>::decode(reader)?,
            source_refs: <String as super::runtime::SoraDecode>::decode(reader)?,
            tags: <String as super::runtime::SoraDecode>::decode(reader)?,
            candidate_ids: <Option<String> as super::runtime::SoraDecode>::decode(reader)?,
            card_parameters: <Option<String> as super::runtime::SoraDecode>::decode(reader)?,
            maze_buff_id: <Option<String> as super::runtime::SoraDecode>::decode(reader)?,
            maze_buff_parameters: <Option<String> as super::runtime::SoraDecode>::decode(reader)?,
            pool_order: <Option<String> as super::runtime::SoraDecode>::decode(reader)?,
            program_summary: <Option<String> as super::runtime::SoraDecode>::decode(reader)?,
            selectable_period_ids: <Option<String> as super::runtime::SoraDecode>::decode(reader)?,
            source_level_id: <Option<String> as super::runtime::SoraDecode>::decode(reader)?,
            source_name_hash: <Option<String> as super::runtime::SoraDecode>::decode(reader)?,
            source_numeric_id: <Option<String> as super::runtime::SoraDecode>::decode(reader)?,
            strategy_type: <String as super::runtime::SoraDecode>::decode(reader)?,
        })
    }
}

impl GbCandidatePools {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct GbCandidatePoolsTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, GbCandidatePools>,
    by_stable_key: SoraMap<String, i32>,
}

impl GbCandidatePoolsTable {
    pub const NAME: &'static str = "GbCandidatePools";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "GbCandidatePools",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[
            super::SoraIndexInfo {
                name: "by_stable_key",
                unique: true,
                fields: &["stable_key"],
            },
        ],
    };

    pub(super) fn from_rows(rows: Vec<GbCandidatePools>) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        let by_stable_key = super::build_unique_map_index(
            rows.iter(),
            |row| row.stable_key.clone(),
            |row| row.id,
        );
        let rows = super::decode_map_table(rows, |row| row.id);
        Ok(Self {
            keys,
            rows,
            by_stable_key,
        })
    }

    pub fn get(&self, key: &i32) -> Option<&GbCandidatePools> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &GbCandidatePools> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
    pub fn get_by_stable_key(&self, stable_key: &str) -> Option<&GbCandidatePools> {
        self.by_stable_key.get(stable_key).and_then(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for GbCandidatePoolsTable {
    type Target = SoraMap<i32, GbCandidatePools>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for GbCandidatePoolsTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for GbCandidatePoolsTable {
    type Key = i32;
    type Row = GbCandidatePools;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
