// This file was generated by Sora. Do not edit manually.
use super::SoraMap;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GbMechanicRules {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "stable_key")]
    pub stable_key: String,
    #[serde(rename = "schema_revision")]
    pub schema_revision: String,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "name_en")]
    pub name_en: String,
    #[serde(rename = "name_zh_cn")]
    pub name_zh_cn: String,
    #[serde(rename = "summary_en")]
    pub summary_en: String,
    #[serde(rename = "summary_zh_cn")]
    pub summary_zh_cn: String,
    #[serde(rename = "profile_ids")]
    pub profile_ids: String,
    #[serde(rename = "ownership")]
    pub ownership: String,
    #[serde(rename = "coverage_state")]
    pub coverage_state: String,
    #[serde(rename = "evidence_quality")]
    pub evidence_quality: String,
    #[serde(rename = "mechanism_quality")]
    pub mechanism_quality: String,
    #[serde(rename = "manifest_record_ids")]
    pub manifest_record_ids: String,
    #[serde(rename = "source_refs")]
    pub source_refs: String,
    #[serde(rename = "tags")]
    pub tags: String,
    #[serde(rename = "family_id")]
    pub family_id: String,
    #[serde(rename = "fixture_ids")]
    pub fixture_ids: String,
    #[serde(rename = "ordered_operations")]
    pub ordered_operations: String,
    #[serde(rename = "preconditions")]
    pub preconditions: String,
    #[serde(rename = "rule_order")]
    pub rule_order: String,
    #[serde(rename = "runtime_executable")]
    pub runtime_executable: String,
    #[serde(rename = "state_owner")]
    pub state_owner: String,
    #[serde(rename = "trigger_point")]
    pub trigger_point: String,
}

impl super::runtime::SoraDecode for GbMechanicRules {
    fn decode(reader: &mut super::runtime::SoraReader<'_>) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            stable_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            schema_revision: <String as super::runtime::SoraDecode>::decode(reader)?,
            kind: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            profile_ids: <String as super::runtime::SoraDecode>::decode(reader)?,
            ownership: <String as super::runtime::SoraDecode>::decode(reader)?,
            coverage_state: <String as super::runtime::SoraDecode>::decode(reader)?,
            evidence_quality: <String as super::runtime::SoraDecode>::decode(reader)?,
            mechanism_quality: <String as super::runtime::SoraDecode>::decode(reader)?,
            manifest_record_ids: <String as super::runtime::SoraDecode>::decode(reader)?,
            source_refs: <String as super::runtime::SoraDecode>::decode(reader)?,
            tags: <String as super::runtime::SoraDecode>::decode(reader)?,
            family_id: <String as super::runtime::SoraDecode>::decode(reader)?,
            fixture_ids: <String as super::runtime::SoraDecode>::decode(reader)?,
            ordered_operations: <String as super::runtime::SoraDecode>::decode(reader)?,
            preconditions: <String as super::runtime::SoraDecode>::decode(reader)?,
            rule_order: <String as super::runtime::SoraDecode>::decode(reader)?,
            runtime_executable: <String as super::runtime::SoraDecode>::decode(reader)?,
            state_owner: <String as super::runtime::SoraDecode>::decode(reader)?,
            trigger_point: <String as super::runtime::SoraDecode>::decode(reader)?,
        })
    }
}

impl GbMechanicRules {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct GbMechanicRulesTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, GbMechanicRules>,
    by_stable_key: SoraMap<String, i32>,
}

impl GbMechanicRulesTable {
    pub const NAME: &'static str = "GbMechanicRules";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "GbMechanicRules",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[
            super::SoraIndexInfo {
                name: "by_stable_key",
                unique: true,
                fields: &["stable_key"],
            },
        ],
    };

    pub(super) fn from_rows(rows: Vec<GbMechanicRules>) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        let by_stable_key = super::build_unique_map_index(
            rows.iter(),
            |row| row.stable_key.clone(),
            |row| row.id,
        );
        let rows = super::decode_map_table(rows, |row| row.id);
        Ok(Self {
            keys,
            rows,
            by_stable_key,
        })
    }

    pub fn get(&self, key: &i32) -> Option<&GbMechanicRules> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &GbMechanicRules> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
    pub fn get_by_stable_key(&self, stable_key: &str) -> Option<&GbMechanicRules> {
        self.by_stable_key.get(stable_key).and_then(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for GbMechanicRulesTable {
    type Target = SoraMap<i32, GbMechanicRules>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for GbMechanicRulesTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for GbMechanicRulesTable {
    type Key = i32;
    type Row = GbMechanicRules;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
