// This file was generated by Sora. Do not edit manually.
use super::SoraMap;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GbResearchGaps {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "stable_key")]
    pub stable_key: String,
    #[serde(rename = "schema_revision")]
    pub schema_revision: String,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "affected_fixture_ids")]
    pub affected_fixture_ids: String,
    #[serde(rename = "approximation_id")]
    pub approximation_id: String,
    #[serde(rename = "confidence")]
    pub confidence: String,
    #[serde(rename = "field_path")]
    pub field_path: String,
    #[serde(rename = "rationale")]
    pub rationale: String,
    #[serde(rename = "rejected_alternatives")]
    pub rejected_alternatives: String,
    #[serde(rename = "replacement_condition")]
    pub replacement_condition: String,
    #[serde(rename = "selected_policy")]
    pub selected_policy: String,
    #[serde(rename = "state")]
    pub state: String,
    #[serde(rename = "terminal_blocker")]
    pub terminal_blocker: String,
    #[serde(rename = "unavailable_fact")]
    pub unavailable_fact: String,
}

impl super::runtime::SoraDecode for GbResearchGaps {
    fn decode(reader: &mut super::runtime::SoraReader<'_>) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            stable_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            schema_revision: <String as super::runtime::SoraDecode>::decode(reader)?,
            kind: <String as super::runtime::SoraDecode>::decode(reader)?,
            affected_fixture_ids: <String as super::runtime::SoraDecode>::decode(reader)?,
            approximation_id: <String as super::runtime::SoraDecode>::decode(reader)?,
            confidence: <String as super::runtime::SoraDecode>::decode(reader)?,
            field_path: <String as super::runtime::SoraDecode>::decode(reader)?,
            rationale: <String as super::runtime::SoraDecode>::decode(reader)?,
            rejected_alternatives: <String as super::runtime::SoraDecode>::decode(reader)?,
            replacement_condition: <String as super::runtime::SoraDecode>::decode(reader)?,
            selected_policy: <String as super::runtime::SoraDecode>::decode(reader)?,
            state: <String as super::runtime::SoraDecode>::decode(reader)?,
            terminal_blocker: <String as super::runtime::SoraDecode>::decode(reader)?,
            unavailable_fact: <String as super::runtime::SoraDecode>::decode(reader)?,
        })
    }
}

impl GbResearchGaps {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct GbResearchGapsTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, GbResearchGaps>,
    by_stable_key: SoraMap<String, i32>,
}

impl GbResearchGapsTable {
    pub const NAME: &'static str = "GbResearchGaps";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "GbResearchGaps",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[
            super::SoraIndexInfo {
                name: "by_stable_key",
                unique: true,
                fields: &["stable_key"],
            },
        ],
    };

    pub(super) fn from_rows(rows: Vec<GbResearchGaps>) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        let by_stable_key = super::build_unique_map_index(
            rows.iter(),
            |row| row.stable_key.clone(),
            |row| row.id,
        );
        let rows = super::decode_map_table(rows, |row| row.id);
        Ok(Self {
            keys,
            rows,
            by_stable_key,
        })
    }

    pub fn get(&self, key: &i32) -> Option<&GbResearchGaps> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &GbResearchGaps> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
    pub fn get_by_stable_key(&self, stable_key: &str) -> Option<&GbResearchGaps> {
        self.by_stable_key.get(stable_key).and_then(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for GbResearchGapsTable {
    type Target = SoraMap<i32, GbResearchGaps>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for GbResearchGapsTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for GbResearchGapsTable {
    type Key = i32;
    type Row = GbResearchGaps;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
