// This file was generated by Sora. Do not edit manually.
use super::SoraMap;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct GbShopUpgrades {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "stable_key")]
    pub stable_key: String,
    #[serde(rename = "schema_revision")]
    pub schema_revision: String,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "name_en")]
    pub name_en: String,
    #[serde(rename = "name_zh_cn")]
    pub name_zh_cn: String,
    #[serde(rename = "summary_en")]
    pub summary_en: String,
    #[serde(rename = "summary_zh_cn")]
    pub summary_zh_cn: String,
    #[serde(rename = "profile_ids")]
    pub profile_ids: String,
    #[serde(rename = "ownership")]
    pub ownership: String,
    #[serde(rename = "coverage_state")]
    pub coverage_state: String,
    #[serde(rename = "evidence_quality")]
    pub evidence_quality: String,
    #[serde(rename = "mechanism_quality")]
    pub mechanism_quality: String,
    #[serde(rename = "manifest_record_ids")]
    pub manifest_record_ids: String,
    #[serde(rename = "source_refs")]
    pub source_refs: String,
    #[serde(rename = "tags")]
    pub tags: String,
    #[serde(rename = "content_tag")]
    pub content_tag: Option<String>,
    #[serde(rename = "cost")]
    pub cost: String,
    #[serde(rename = "cost_currency_id")]
    pub cost_currency_id: String,
    #[serde(rename = "failure_behavior")]
    pub failure_behavior: String,
    #[serde(rename = "maximum_level")]
    pub maximum_level: String,
    #[serde(rename = "maze_buff_id")]
    pub maze_buff_id: Option<String>,
    #[serde(rename = "maze_buff_parameters")]
    pub maze_buff_parameters: String,
    #[serde(rename = "price_order")]
    pub price_order: Option<String>,
    #[serde(rename = "purchase_level")]
    pub purchase_level: String,
    #[serde(rename = "shop_parameter_values")]
    pub shop_parameter_values: String,
    #[serde(rename = "shop_type")]
    pub shop_type: String,
    #[serde(rename = "source_numeric_id")]
    pub source_numeric_id: String,
    #[serde(rename = "state_owner")]
    pub state_owner: String,
}

impl super::runtime::SoraDecode for GbShopUpgrades {
    fn decode(reader: &mut super::runtime::SoraReader<'_>) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            stable_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            schema_revision: <String as super::runtime::SoraDecode>::decode(reader)?,
            kind: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            profile_ids: <String as super::runtime::SoraDecode>::decode(reader)?,
            ownership: <String as super::runtime::SoraDecode>::decode(reader)?,
            coverage_state: <String as super::runtime::SoraDecode>::decode(reader)?,
            evidence_quality: <String as super::runtime::SoraDecode>::decode(reader)?,
            mechanism_quality: <String as super::runtime::SoraDecode>::decode(reader)?,
            manifest_record_ids: <String as super::runtime::SoraDecode>::decode(reader)?,
            source_refs: <String as super::runtime::SoraDecode>::decode(reader)?,
            tags: <String as super::runtime::SoraDecode>::decode(reader)?,
            content_tag: <Option<String> as super::runtime::SoraDecode>::decode(reader)?,
            cost: <String as super::runtime::SoraDecode>::decode(reader)?,
            cost_currency_id: <String as super::runtime::SoraDecode>::decode(reader)?,
            failure_behavior: <String as super::runtime::SoraDecode>::decode(reader)?,
            maximum_level: <String as super::runtime::SoraDecode>::decode(reader)?,
            maze_buff_id: <Option<String> as super::runtime::SoraDecode>::decode(reader)?,
            maze_buff_parameters: <String as super::runtime::SoraDecode>::decode(reader)?,
            price_order: <Option<String> as super::runtime::SoraDecode>::decode(reader)?,
            purchase_level: <String as super::runtime::SoraDecode>::decode(reader)?,
            shop_parameter_values: <String as super::runtime::SoraDecode>::decode(reader)?,
            shop_type: <String as super::runtime::SoraDecode>::decode(reader)?,
            source_numeric_id: <String as super::runtime::SoraDecode>::decode(reader)?,
            state_owner: <String as super::runtime::SoraDecode>::decode(reader)?,
        })
    }
}

impl GbShopUpgrades {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct GbShopUpgradesTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, GbShopUpgrades>,
    by_stable_key: SoraMap<String, i32>,
}

impl GbShopUpgradesTable {
    pub const NAME: &'static str = "GbShopUpgrades";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "GbShopUpgrades",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[
            super::SoraIndexInfo {
                name: "by_stable_key",
                unique: true,
                fields: &["stable_key"],
            },
        ],
    };

    pub(super) fn from_rows(rows: Vec<GbShopUpgrades>) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        let by_stable_key = super::build_unique_map_index(
            rows.iter(),
            |row| row.stable_key.clone(),
            |row| row.id,
        );
        let rows = super::decode_map_table(rows, |row| row.id);
        Ok(Self {
            keys,
            rows,
            by_stable_key,
        })
    }

    pub fn get(&self, key: &i32) -> Option<&GbShopUpgrades> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &GbShopUpgrades> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
    pub fn get_by_stable_key(&self, stable_key: &str) -> Option<&GbShopUpgrades> {
        self.by_stable_key.get(stable_key).and_then(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for GbShopUpgradesTable {
    type Target = SoraMap<i32, GbShopUpgrades>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for GbShopUpgradesTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for GbShopUpgradesTable {
    type Key = i32;
    type Row = GbShopUpgrades;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
