// This file was generated by Sora. Do not edit manually.

#![allow(dead_code)]

pub mod runtime;
pub mod gb_profiles;
pub mod gb_release_boundaries;
pub mod gb_stages;
pub mod gb_stage_periods;
pub mod gb_level_thresholds;
pub mod gb_candidate_pools;
pub mod gb_candidate_policies;
pub mod gb_inventory_slots;
pub mod gb_inventory_operations;
pub mod gb_profile_differences;
pub mod gb_adventure_strategies;
pub mod gb_progression;
pub mod gb_currencies;
pub mod gb_shop_upgrades;
pub mod gb_unlocks;
pub mod gb_weapons;
pub mod gb_weapon_levels;
pub mod gb_weapon_triggers;
pub mod gb_accessories;
pub mod gb_accessory_levels;
pub mod gb_accessory_bindings;
pub mod gb_synthesis_recipes;
pub mod gb_synthesis_inputs;
pub mod gb_encounters;
pub mod gb_waves;
pub mod gb_enemy_slots;
pub mod gb_enemies;
pub mod gb_enemy_skills;
pub mod gb_enemy_statuses;
pub mod gb_scoring_rules;
pub mod gb_settlement_rules;
pub mod gb_mechanic_rules;
pub mod gb_sources;
pub mod gb_approximations;
pub mod gb_reconciliation;
pub mod gb_coverage;
pub mod gb_research_gaps;
pub mod gb_review_fixtures;
pub mod gb_manifest;
pub mod gb_pack_index;
pub type SoraMap<K, V> = std::collections::HashMap<K, V>;

pub const SCHEMA_FINGERPRINT: &str = "d0c38406def02a52";

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SoraTableShape {
    List,
    Keyed,
    Singleton,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SoraKeyInfo {
    pub name: &'static str,
    pub ty: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SoraIndexInfo {
    pub name: &'static str,
    pub unique: bool,
    pub fields: &'static [&'static str],
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SoraTableInfo {
    pub name: &'static str,
    pub row_type: &'static str,
    pub shape: SoraTableShape,
    pub primary_key: Option<SoraKeyInfo>,
    pub indexes: &'static [SoraIndexInfo],
}

pub trait ErasedSoraTable: std::any::Any + Send + Sync {
    fn info(&self) -> &'static SoraTableInfo;
    fn len(&self) -> usize;

    fn is_empty(&self) -> bool {
        self.len() == 0
    }
}

pub trait SoraKeyedTable: ErasedSoraTable {
    type Key: std::cmp::Eq + std::hash::Hash + 'static;
    type Row: 'static;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row>;
    fn keys(&self) -> &[Self::Key];
}

pub trait SoraListTable: ErasedSoraTable {
    type Row: 'static;

    fn as_slice(&self) -> &[Self::Row];
}

pub trait SoraSingleTable: ErasedSoraTable {
    type Row: 'static;

    fn get(&self) -> &Self::Row;
}

pub struct SoraConfig {
    tables: SoraMap<&'static str, Box<dyn ErasedSoraTable>>,
}

impl std::fmt::Debug for SoraConfig {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let mut tables = self.tables.keys().copied().collect::<Vec<_>>();
        tables.sort_unstable();
        f.debug_struct("SoraConfig").field("tables", &tables).finish()
    }
}

impl SoraConfig {
    pub fn from_source(source: &impl runtime::SoraTableSource) -> Result<Self, runtime::SoraReadError> {
        let schema_fingerprint = source.schema_fingerprint()?;
        if schema_fingerprint != SCHEMA_FINGERPRINT {
            return Err(runtime::SoraReadError::new(format!(
                "schema fingerprint mismatch: generated code expects {}, bundle contains {}",
                SCHEMA_FINGERPRINT,
                schema_fingerprint
            )));
        }
        let mut tables: SoraMap<&'static str, Box<dyn ErasedSoraTable>> =
            sora_map_with_capacity(40);
        tables.insert(gb_profiles::GbProfilesTable::NAME, Box::new(gb_profiles::GbProfilesTable::from_rows(source.decode_table::<gb_profiles::GbProfiles>(gb_profiles::GbProfilesTable::NAME)?)?));
        tables.insert(gb_release_boundaries::GbReleaseBoundariesTable::NAME, Box::new(gb_release_boundaries::GbReleaseBoundariesTable::from_rows(source.decode_table::<gb_release_boundaries::GbReleaseBoundaries>(gb_release_boundaries::GbReleaseBoundariesTable::NAME)?)?));
        tables.insert(gb_stages::GbStagesTable::NAME, Box::new(gb_stages::GbStagesTable::from_rows(source.decode_table::<gb_stages::GbStages>(gb_stages::GbStagesTable::NAME)?)?));
        tables.insert(gb_stage_periods::GbStagePeriodsTable::NAME, Box::new(gb_stage_periods::GbStagePeriodsTable::from_rows(source.decode_table::<gb_stage_periods::GbStagePeriods>(gb_stage_periods::GbStagePeriodsTable::NAME)?)?));
        tables.insert(gb_level_thresholds::GbLevelThresholdsTable::NAME, Box::new(gb_level_thresholds::GbLevelThresholdsTable::from_rows(source.decode_table::<gb_level_thresholds::GbLevelThresholds>(gb_level_thresholds::GbLevelThresholdsTable::NAME)?)?));
        tables.insert(gb_candidate_pools::GbCandidatePoolsTable::NAME, Box::new(gb_candidate_pools::GbCandidatePoolsTable::from_rows(source.decode_table::<gb_candidate_pools::GbCandidatePools>(gb_candidate_pools::GbCandidatePoolsTable::NAME)?)?));
        tables.insert(gb_candidate_policies::GbCandidatePoliciesTable::NAME, Box::new(gb_candidate_policies::GbCandidatePoliciesTable::from_rows(source.decode_table::<gb_candidate_policies::GbCandidatePolicies>(gb_candidate_policies::GbCandidatePoliciesTable::NAME)?)?));
        tables.insert(gb_inventory_slots::GbInventorySlotsTable::NAME, Box::new(gb_inventory_slots::GbInventorySlotsTable::from_rows(source.decode_table::<gb_inventory_slots::GbInventorySlots>(gb_inventory_slots::GbInventorySlotsTable::NAME)?)?));
        tables.insert(gb_inventory_operations::GbInventoryOperationsTable::NAME, Box::new(gb_inventory_operations::GbInventoryOperationsTable::from_rows(source.decode_table::<gb_inventory_operations::GbInventoryOperations>(gb_inventory_operations::GbInventoryOperationsTable::NAME)?)?));
        tables.insert(gb_profile_differences::GbProfileDifferencesTable::NAME, Box::new(gb_profile_differences::GbProfileDifferencesTable::from_rows(source.decode_table::<gb_profile_differences::GbProfileDifferences>(gb_profile_differences::GbProfileDifferencesTable::NAME)?)?));
        tables.insert(gb_adventure_strategies::GbAdventureStrategiesTable::NAME, Box::new(gb_adventure_strategies::GbAdventureStrategiesTable::from_rows(source.decode_table::<gb_adventure_strategies::GbAdventureStrategies>(gb_adventure_strategies::GbAdventureStrategiesTable::NAME)?)?));
        tables.insert(gb_progression::GbProgressionTable::NAME, Box::new(gb_progression::GbProgressionTable::from_rows(source.decode_table::<gb_progression::GbProgression>(gb_progression::GbProgressionTable::NAME)?)?));
        tables.insert(gb_currencies::GbCurrenciesTable::NAME, Box::new(gb_currencies::GbCurrenciesTable::from_rows(source.decode_table::<gb_currencies::GbCurrencies>(gb_currencies::GbCurrenciesTable::NAME)?)?));
        tables.insert(gb_shop_upgrades::GbShopUpgradesTable::NAME, Box::new(gb_shop_upgrades::GbShopUpgradesTable::from_rows(source.decode_table::<gb_shop_upgrades::GbShopUpgrades>(gb_shop_upgrades::GbShopUpgradesTable::NAME)?)?));
        tables.insert(gb_unlocks::GbUnlocksTable::NAME, Box::new(gb_unlocks::GbUnlocksTable::from_rows(source.decode_table::<gb_unlocks::GbUnlocks>(gb_unlocks::GbUnlocksTable::NAME)?)?));
        tables.insert(gb_weapons::GbWeaponsTable::NAME, Box::new(gb_weapons::GbWeaponsTable::from_rows(source.decode_table::<gb_weapons::GbWeapons>(gb_weapons::GbWeaponsTable::NAME)?)?));
        tables.insert(gb_weapon_levels::GbWeaponLevelsTable::NAME, Box::new(gb_weapon_levels::GbWeaponLevelsTable::from_rows(source.decode_table::<gb_weapon_levels::GbWeaponLevels>(gb_weapon_levels::GbWeaponLevelsTable::NAME)?)?));
        tables.insert(gb_weapon_triggers::GbWeaponTriggersTable::NAME, Box::new(gb_weapon_triggers::GbWeaponTriggersTable::from_rows(source.decode_table::<gb_weapon_triggers::GbWeaponTriggers>(gb_weapon_triggers::GbWeaponTriggersTable::NAME)?)?));
        tables.insert(gb_accessories::GbAccessoriesTable::NAME, Box::new(gb_accessories::GbAccessoriesTable::from_rows(source.decode_table::<gb_accessories::GbAccessories>(gb_accessories::GbAccessoriesTable::NAME)?)?));
        tables.insert(gb_accessory_levels::GbAccessoryLevelsTable::NAME, Box::new(gb_accessory_levels::GbAccessoryLevelsTable::from_rows(source.decode_table::<gb_accessory_levels::GbAccessoryLevels>(gb_accessory_levels::GbAccessoryLevelsTable::NAME)?)?));
        tables.insert(gb_accessory_bindings::GbAccessoryBindingsTable::NAME, Box::new(gb_accessory_bindings::GbAccessoryBindingsTable::from_rows(source.decode_table::<gb_accessory_bindings::GbAccessoryBindings>(gb_accessory_bindings::GbAccessoryBindingsTable::NAME)?)?));
        tables.insert(gb_synthesis_recipes::GbSynthesisRecipesTable::NAME, Box::new(gb_synthesis_recipes::GbSynthesisRecipesTable::from_rows(source.decode_table::<gb_synthesis_recipes::GbSynthesisRecipes>(gb_synthesis_recipes::GbSynthesisRecipesTable::NAME)?)?));
        tables.insert(gb_synthesis_inputs::GbSynthesisInputsTable::NAME, Box::new(gb_synthesis_inputs::GbSynthesisInputsTable::from_rows(source.decode_table::<gb_synthesis_inputs::GbSynthesisInputs>(gb_synthesis_inputs::GbSynthesisInputsTable::NAME)?)?));
        tables.insert(gb_encounters::GbEncountersTable::NAME, Box::new(gb_encounters::GbEncountersTable::from_rows(source.decode_table::<gb_encounters::GbEncounters>(gb_encounters::GbEncountersTable::NAME)?)?));
        tables.insert(gb_waves::GbWavesTable::NAME, Box::new(gb_waves::GbWavesTable::from_rows(source.decode_table::<gb_waves::GbWaves>(gb_waves::GbWavesTable::NAME)?)?));
        tables.insert(gb_enemy_slots::GbEnemySlotsTable::NAME, Box::new(gb_enemy_slots::GbEnemySlotsTable::from_rows(source.decode_table::<gb_enemy_slots::GbEnemySlots>(gb_enemy_slots::GbEnemySlotsTable::NAME)?)?));
        tables.insert(gb_enemies::GbEnemiesTable::NAME, Box::new(gb_enemies::GbEnemiesTable::from_rows(source.decode_table::<gb_enemies::GbEnemies>(gb_enemies::GbEnemiesTable::NAME)?)?));
        tables.insert(gb_enemy_skills::GbEnemySkillsTable::NAME, Box::new(gb_enemy_skills::GbEnemySkillsTable::from_rows(source.decode_table::<gb_enemy_skills::GbEnemySkills>(gb_enemy_skills::GbEnemySkillsTable::NAME)?)?));
        tables.insert(gb_enemy_statuses::GbEnemyStatusesTable::NAME, Box::new(gb_enemy_statuses::GbEnemyStatusesTable::from_rows(source.decode_table::<gb_enemy_statuses::GbEnemyStatuses>(gb_enemy_statuses::GbEnemyStatusesTable::NAME)?)?));
        tables.insert(gb_scoring_rules::GbScoringRulesTable::NAME, Box::new(gb_scoring_rules::GbScoringRulesTable::from_rows(source.decode_table::<gb_scoring_rules::GbScoringRules>(gb_scoring_rules::GbScoringRulesTable::NAME)?)?));
        tables.insert(gb_settlement_rules::GbSettlementRulesTable::NAME, Box::new(gb_settlement_rules::GbSettlementRulesTable::from_rows(source.decode_table::<gb_settlement_rules::GbSettlementRules>(gb_settlement_rules::GbSettlementRulesTable::NAME)?)?));
        tables.insert(gb_mechanic_rules::GbMechanicRulesTable::NAME, Box::new(gb_mechanic_rules::GbMechanicRulesTable::from_rows(source.decode_table::<gb_mechanic_rules::GbMechanicRules>(gb_mechanic_rules::GbMechanicRulesTable::NAME)?)?));
        tables.insert(gb_sources::GbSourcesTable::NAME, Box::new(gb_sources::GbSourcesTable::from_rows(source.decode_table::<gb_sources::GbSources>(gb_sources::GbSourcesTable::NAME)?)?));
        tables.insert(gb_approximations::GbApproximationsTable::NAME, Box::new(gb_approximations::GbApproximationsTable::from_rows(source.decode_table::<gb_approximations::GbApproximations>(gb_approximations::GbApproximationsTable::NAME)?)?));
        tables.insert(gb_reconciliation::GbReconciliationTable::NAME, Box::new(gb_reconciliation::GbReconciliationTable::from_rows(source.decode_table::<gb_reconciliation::GbReconciliation>(gb_reconciliation::GbReconciliationTable::NAME)?)?));
        tables.insert(gb_coverage::GbCoverageTable::NAME, Box::new(gb_coverage::GbCoverageTable::from_rows(source.decode_table::<gb_coverage::GbCoverage>(gb_coverage::GbCoverageTable::NAME)?)?));
        tables.insert(gb_research_gaps::GbResearchGapsTable::NAME, Box::new(gb_research_gaps::GbResearchGapsTable::from_rows(source.decode_table::<gb_research_gaps::GbResearchGaps>(gb_research_gaps::GbResearchGapsTable::NAME)?)?));
        tables.insert(gb_review_fixtures::GbReviewFixturesTable::NAME, Box::new(gb_review_fixtures::GbReviewFixturesTable::from_rows(source.decode_table::<gb_review_fixtures::GbReviewFixtures>(gb_review_fixtures::GbReviewFixturesTable::NAME)?)?));
        tables.insert(gb_manifest::GbManifestTable::NAME, Box::new(gb_manifest::GbManifestTable::from_rows(source.decode_table::<gb_manifest::GbManifest>(gb_manifest::GbManifestTable::NAME)?)?));
        tables.insert(gb_pack_index::GbPackIndexTable::NAME, Box::new(gb_pack_index::GbPackIndexTable::from_rows(source.decode_table::<gb_pack_index::GbPackIndex>(gb_pack_index::GbPackIndexTable::NAME)?)?));
        Ok(Self { tables })
    }

    fn table<T: ErasedSoraTable + 'static>(&self, name: &'static str) -> &T {
        self.tables
            .get(name)
            .and_then(|table| {
                let table: &dyn std::any::Any = table.as_ref();
                table.downcast_ref::<T>()
            })
            .unwrap_or_else(|| {
                panic!(
                    "generated SoraConfig is missing table `{}` or has an unexpected table type",
                    name
                )
            })
    }

    pub fn tables(&self) -> impl Iterator<Item = &dyn ErasedSoraTable> {
        self.tables.values().map(Box::as_ref)
    }

    pub fn gb_profiles(&self) -> &gb_profiles::GbProfilesTable {
        self.table(gb_profiles::GbProfilesTable::NAME)
    }

    pub fn gb_release_boundaries(&self) -> &gb_release_boundaries::GbReleaseBoundariesTable {
        self.table(gb_release_boundaries::GbReleaseBoundariesTable::NAME)
    }

    pub fn gb_stages(&self) -> &gb_stages::GbStagesTable {
        self.table(gb_stages::GbStagesTable::NAME)
    }

    pub fn gb_stage_periods(&self) -> &gb_stage_periods::GbStagePeriodsTable {
        self.table(gb_stage_periods::GbStagePeriodsTable::NAME)
    }

    pub fn gb_level_thresholds(&self) -> &gb_level_thresholds::GbLevelThresholdsTable {
        self.table(gb_level_thresholds::GbLevelThresholdsTable::NAME)
    }

    pub fn gb_candidate_pools(&self) -> &gb_candidate_pools::GbCandidatePoolsTable {
        self.table(gb_candidate_pools::GbCandidatePoolsTable::NAME)
    }

    pub fn gb_candidate_policies(&self) -> &gb_candidate_policies::GbCandidatePoliciesTable {
        self.table(gb_candidate_policies::GbCandidatePoliciesTable::NAME)
    }

    pub fn gb_inventory_slots(&self) -> &gb_inventory_slots::GbInventorySlotsTable {
        self.table(gb_inventory_slots::GbInventorySlotsTable::NAME)
    }

    pub fn gb_inventory_operations(&self) -> &gb_inventory_operations::GbInventoryOperationsTable {
        self.table(gb_inventory_operations::GbInventoryOperationsTable::NAME)
    }

    pub fn gb_profile_differences(&self) -> &gb_profile_differences::GbProfileDifferencesTable {
        self.table(gb_profile_differences::GbProfileDifferencesTable::NAME)
    }

    pub fn gb_adventure_strategies(&self) -> &gb_adventure_strategies::GbAdventureStrategiesTable {
        self.table(gb_adventure_strategies::GbAdventureStrategiesTable::NAME)
    }

    pub fn gb_progression(&self) -> &gb_progression::GbProgressionTable {
        self.table(gb_progression::GbProgressionTable::NAME)
    }

    pub fn gb_currencies(&self) -> &gb_currencies::GbCurrenciesTable {
        self.table(gb_currencies::GbCurrenciesTable::NAME)
    }

    pub fn gb_shop_upgrades(&self) -> &gb_shop_upgrades::GbShopUpgradesTable {
        self.table(gb_shop_upgrades::GbShopUpgradesTable::NAME)
    }

    pub fn gb_unlocks(&self) -> &gb_unlocks::GbUnlocksTable {
        self.table(gb_unlocks::GbUnlocksTable::NAME)
    }

    pub fn gb_weapons(&self) -> &gb_weapons::GbWeaponsTable {
        self.table(gb_weapons::GbWeaponsTable::NAME)
    }

    pub fn gb_weapon_levels(&self) -> &gb_weapon_levels::GbWeaponLevelsTable {
        self.table(gb_weapon_levels::GbWeaponLevelsTable::NAME)
    }

    pub fn gb_weapon_triggers(&self) -> &gb_weapon_triggers::GbWeaponTriggersTable {
        self.table(gb_weapon_triggers::GbWeaponTriggersTable::NAME)
    }

    pub fn gb_accessories(&self) -> &gb_accessories::GbAccessoriesTable {
        self.table(gb_accessories::GbAccessoriesTable::NAME)
    }

    pub fn gb_accessory_levels(&self) -> &gb_accessory_levels::GbAccessoryLevelsTable {
        self.table(gb_accessory_levels::GbAccessoryLevelsTable::NAME)
    }

    pub fn gb_accessory_bindings(&self) -> &gb_accessory_bindings::GbAccessoryBindingsTable {
        self.table(gb_accessory_bindings::GbAccessoryBindingsTable::NAME)
    }

    pub fn gb_synthesis_recipes(&self) -> &gb_synthesis_recipes::GbSynthesisRecipesTable {
        self.table(gb_synthesis_recipes::GbSynthesisRecipesTable::NAME)
    }

    pub fn gb_synthesis_inputs(&self) -> &gb_synthesis_inputs::GbSynthesisInputsTable {
        self.table(gb_synthesis_inputs::GbSynthesisInputsTable::NAME)
    }

    pub fn gb_encounters(&self) -> &gb_encounters::GbEncountersTable {
        self.table(gb_encounters::GbEncountersTable::NAME)
    }

    pub fn gb_waves(&self) -> &gb_waves::GbWavesTable {
        self.table(gb_waves::GbWavesTable::NAME)
    }

    pub fn gb_enemy_slots(&self) -> &gb_enemy_slots::GbEnemySlotsTable {
        self.table(gb_enemy_slots::GbEnemySlotsTable::NAME)
    }

    pub fn gb_enemies(&self) -> &gb_enemies::GbEnemiesTable {
        self.table(gb_enemies::GbEnemiesTable::NAME)
    }

    pub fn gb_enemy_skills(&self) -> &gb_enemy_skills::GbEnemySkillsTable {
        self.table(gb_enemy_skills::GbEnemySkillsTable::NAME)
    }

    pub fn gb_enemy_statuses(&self) -> &gb_enemy_statuses::GbEnemyStatusesTable {
        self.table(gb_enemy_statuses::GbEnemyStatusesTable::NAME)
    }

    pub fn gb_scoring_rules(&self) -> &gb_scoring_rules::GbScoringRulesTable {
        self.table(gb_scoring_rules::GbScoringRulesTable::NAME)
    }

    pub fn gb_settlement_rules(&self) -> &gb_settlement_rules::GbSettlementRulesTable {
        self.table(gb_settlement_rules::GbSettlementRulesTable::NAME)
    }

    pub fn gb_mechanic_rules(&self) -> &gb_mechanic_rules::GbMechanicRulesTable {
        self.table(gb_mechanic_rules::GbMechanicRulesTable::NAME)
    }

    pub fn gb_sources(&self) -> &gb_sources::GbSourcesTable {
        self.table(gb_sources::GbSourcesTable::NAME)
    }

    pub fn gb_approximations(&self) -> &gb_approximations::GbApproximationsTable {
        self.table(gb_approximations::GbApproximationsTable::NAME)
    }

    pub fn gb_reconciliation(&self) -> &gb_reconciliation::GbReconciliationTable {
        self.table(gb_reconciliation::GbReconciliationTable::NAME)
    }

    pub fn gb_coverage(&self) -> &gb_coverage::GbCoverageTable {
        self.table(gb_coverage::GbCoverageTable::NAME)
    }

    pub fn gb_research_gaps(&self) -> &gb_research_gaps::GbResearchGapsTable {
        self.table(gb_research_gaps::GbResearchGapsTable::NAME)
    }

    pub fn gb_review_fixtures(&self) -> &gb_review_fixtures::GbReviewFixturesTable {
        self.table(gb_review_fixtures::GbReviewFixturesTable::NAME)
    }

    pub fn gb_manifest(&self) -> &gb_manifest::GbManifestTable {
        self.table(gb_manifest::GbManifestTable::NAME)
    }

    pub fn gb_pack_index(&self) -> &gb_pack_index::GbPackIndexTable {
        self.table(gb_pack_index::GbPackIndexTable::NAME)
    }
}

fn sora_map_with_capacity<K, V>(capacity: usize) -> SoraMap<K, V>
where
    K: std::cmp::Eq + std::hash::Hash,
{
    SoraMap::with_capacity(capacity)
}

fn decode_map_table<K, V>(rows: Vec<V>, key: impl Fn(&V) -> K) -> SoraMap<K, V>
where
    K: std::cmp::Eq + std::hash::Hash,
{
    rows.into_iter().map(|row| (key(&row), row)).collect()
}

fn build_unique_list_index<'a, K, V: 'a>(
    rows: impl Iterator<Item = &'a V>,
    key: impl Fn(&V) -> K,
) -> SoraMap<K, usize>
where
    K: std::cmp::Eq + std::hash::Hash,
{
    let mut index = sora_map_with_capacity(rows.size_hint().0);
    for (position, row) in rows.enumerate() {
        index.insert(key(row), position);
    }
    index
}

fn build_unique_map_index<'a, K, P, V: 'a>(
    rows: impl Iterator<Item = &'a V>,
    key: impl Fn(&V) -> K,
    primary_key: impl Fn(&V) -> P,
) -> SoraMap<K, P>
where
    K: std::cmp::Eq + std::hash::Hash,
    P: std::cmp::Eq + std::hash::Hash,
{
    let mut index = sora_map_with_capacity(rows.size_hint().0);
    for row in rows {
        index.insert(key(row), primary_key(row));
    }
    index
}
