[package]
name = "starclock-mode-currency-wars"
version.workspace = true
edition.workspace = true
publish.workspace = true
autotests = false

[lints]
workspace = true

[dependencies]
sha2.workspace = true
starclock-activity = { path = "../starclock-activity" }
starclock-build = { path = "../starclock-build" }
starclock-combat = { path = "../starclock-combat" }
