// This file was generated by Sora. Do not edit manually.

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct UniverseServiceParameter {
    #[serde(rename = "service_id")]
    pub service_id: i32,
    #[serde(rename = "sequence")]
    pub sequence: i32,
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "value")]
    pub value: String,
}

impl super::runtime::SoraDecode for UniverseServiceParameter {
    fn decode(
        reader: &mut super::runtime::SoraReader<'_>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            service_id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            sequence: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            key: <String as super::runtime::SoraDecode>::decode(reader)?,
            value: <String as super::runtime::SoraDecode>::decode(reader)?,
        })
    }
}

impl UniverseServiceParameter {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct UniverseServiceParameterTable {
    rows: Vec<UniverseServiceParameter>,
}

impl UniverseServiceParameterTable {
    pub const NAME: &'static str = "UniverseServiceParameter";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "UniverseServiceParameter",
        shape: super::SoraTableShape::List,
        primary_key: None,
        indexes: &[],
    };

    pub(super) fn from_rows(
        rows: Vec<UniverseServiceParameter>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self { rows })
    }
}

impl std::ops::Deref for UniverseServiceParameterTable {
    type Target = [UniverseServiceParameter];

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for UniverseServiceParameterTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraListTable for UniverseServiceParameterTable {
    type Row = UniverseServiceParameter;

    fn as_slice(&self) -> &[Self::Row] {
        &self.rows
    }
}
