// This file was generated by Sora. Do not edit manually.

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct UniverseBlessingPrerequisite {
    #[serde(rename = "blessing_id")]
    pub blessing_id: i32,
    #[serde(rename = "sequence")]
    pub sequence: i32,
    #[serde(rename = "prerequisite_stable_key")]
    pub prerequisite_stable_key: String,
}

impl super::runtime::SoraDecode for UniverseBlessingPrerequisite {
    fn decode(
        reader: &mut super::runtime::SoraReader<'_>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            blessing_id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            sequence: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            prerequisite_stable_key: <String as super::runtime::SoraDecode>::decode(reader)?,
        })
    }
}

impl UniverseBlessingPrerequisite {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct UniverseBlessingPrerequisiteTable {
    rows: Vec<UniverseBlessingPrerequisite>,
}

impl UniverseBlessingPrerequisiteTable {
    pub const NAME: &'static str = "UniverseBlessingPrerequisite";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "UniverseBlessingPrerequisite",
        shape: super::SoraTableShape::List,
        primary_key: None,
        indexes: &[],
    };

    pub(super) fn from_rows(
        rows: Vec<UniverseBlessingPrerequisite>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self { rows })
    }
}

impl std::ops::Deref for UniverseBlessingPrerequisiteTable {
    type Target = [UniverseBlessingPrerequisite];

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for UniverseBlessingPrerequisiteTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraListTable for UniverseBlessingPrerequisiteTable {
    type Row = UniverseBlessingPrerequisite;

    fn as_slice(&self) -> &[Self::Row] {
        &self.rows
    }
}
