// This file was generated by Sora. Do not edit manually.

#[repr(u32)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum UniverseDomainKind {
    CombatPrimary = 0,
    CombatSecondary = 1,
    Occurrence = 2,
    Encounter = 3,
    Respite = 4,
    Elite = 5,
    Boss = 6,
    Transaction = 7,
    Adventure = 8,
}

impl super::runtime::SoraDecode for UniverseDomainKind {
    fn decode(
        reader: &mut super::runtime::SoraReader<'_>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        match reader.read_var_u32()? {
            0 => Ok(Self::CombatPrimary),
            1 => Ok(Self::CombatSecondary),
            2 => Ok(Self::Occurrence),
            3 => Ok(Self::Encounter),
            4 => Ok(Self::Respite),
            5 => Ok(Self::Elite),
            6 => Ok(Self::Boss),
            7 => Ok(Self::Transaction),
            8 => Ok(Self::Adventure),
            value => Err(super::runtime::SoraReadError::new(format!(
                "invalid enum id {} for UniverseDomainKind",
                value
            ))),
        }
    }
}
