// This file was generated by Sora. Do not edit manually.

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct UniverseMapEdge {
    #[serde(rename = "source_node_id")]
    pub source_node_id: i32,
    #[serde(rename = "sequence")]
    pub sequence: i32,
    #[serde(rename = "target_node_id")]
    pub target_node_id: i32,
}

impl super::runtime::SoraDecode for UniverseMapEdge {
    fn decode(
        reader: &mut super::runtime::SoraReader<'_>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            source_node_id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            sequence: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            target_node_id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
        })
    }
}

impl UniverseMapEdge {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct UniverseMapEdgeTable {
    rows: Vec<UniverseMapEdge>,
}

impl UniverseMapEdgeTable {
    pub const NAME: &'static str = "UniverseMapEdge";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "UniverseMapEdge",
        shape: super::SoraTableShape::List,
        primary_key: None,
        indexes: &[],
    };

    pub(super) fn from_rows(
        rows: Vec<UniverseMapEdge>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self { rows })
    }
}

impl std::ops::Deref for UniverseMapEdgeTable {
    type Target = [UniverseMapEdge];

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for UniverseMapEdgeTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraListTable for UniverseMapEdgeTable {
    type Row = UniverseMapEdge;

    fn as_slice(&self) -> &[Self::Row] {
        &self.rows
    }
}
