// This file was generated by Sora. Do not edit manually.
use super::SoraMap;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct UniversePath {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "stable_key")]
    pub stable_key: String,
    #[serde(rename = "buff_type")]
    pub buff_type: String,
    #[serde(rename = "name_en")]
    pub name_en: String,
    #[serde(rename = "name_zh_cn")]
    pub name_zh_cn: String,
    #[serde(rename = "summary_en")]
    pub summary_en: String,
    #[serde(rename = "summary_zh_cn")]
    pub summary_zh_cn: String,
    #[serde(rename = "unlock_policy_stable_key")]
    pub unlock_policy_stable_key: String,
}

impl super::runtime::SoraDecode for UniversePath {
    fn decode(
        reader: &mut super::runtime::SoraReader<'_>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            stable_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            buff_type: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            unlock_policy_stable_key: <String as super::runtime::SoraDecode>::decode(reader)?,
        })
    }
}

impl UniversePath {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct UniversePathTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, UniversePath>,
    by_stable_key: SoraMap<String, i32>,
    by_buff_type: SoraMap<String, i32>,
}

impl UniversePathTable {
    pub const NAME: &'static str = "UniversePath";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "UniversePath",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[
            super::SoraIndexInfo {
                name: "by_stable_key",
                unique: true,
                fields: &["stable_key"],
            },
            super::SoraIndexInfo {
                name: "by_buff_type",
                unique: true,
                fields: &["buff_type"],
            },
        ],
    };

    pub(super) fn from_rows(
        rows: Vec<UniversePath>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        let by_stable_key =
            super::build_unique_map_index(rows.iter(), |row| row.stable_key.clone(), |row| row.id);
        let by_buff_type =
            super::build_unique_map_index(rows.iter(), |row| row.buff_type.clone(), |row| row.id);
        let rows = super::decode_map_table(rows, |row| row.id);
        Ok(Self {
            keys,
            rows,
            by_stable_key,
            by_buff_type,
        })
    }

    pub fn get(&self, key: &i32) -> Option<&UniversePath> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &UniversePath> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
    pub fn get_by_stable_key(&self, stable_key: &str) -> Option<&UniversePath> {
        self.by_stable_key
            .get(stable_key)
            .and_then(|key| self.rows.get(key))
    }
    pub fn get_by_buff_type(&self, buff_type: &str) -> Option<&UniversePath> {
        self.by_buff_type
            .get(buff_type)
            .and_then(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for UniversePathTable {
    type Target = SoraMap<i32, UniversePath>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for UniversePathTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for UniversePathTable {
    type Key = i32;
    type Row = UniversePath;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
