// This file was generated by Sora. Do not edit manually.
use super::SoraMap;
use super::universe_pool_kind::UniversePoolKind;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct UniverseContentPool {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "stable_key")]
    pub stable_key: String,
    #[serde(rename = "kind")]
    pub kind: UniversePoolKind,
    #[serde(rename = "ordering")]
    pub ordering: String,
    #[serde(rename = "replacement")]
    pub replacement: bool,
}

impl super::runtime::SoraDecode for UniverseContentPool {
    fn decode(
        reader: &mut super::runtime::SoraReader<'_>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            stable_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            kind: <UniversePoolKind as super::runtime::SoraDecode>::decode(reader)?,
            ordering: <String as super::runtime::SoraDecode>::decode(reader)?,
            replacement: <bool as super::runtime::SoraDecode>::decode(reader)?,
        })
    }
}

impl UniverseContentPool {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct UniverseContentPoolTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, UniverseContentPool>,
    by_stable_key: SoraMap<String, i32>,
}

impl UniverseContentPoolTable {
    pub const NAME: &'static str = "UniverseContentPool";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "UniverseContentPool",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[super::SoraIndexInfo {
            name: "by_stable_key",
            unique: true,
            fields: &["stable_key"],
        }],
    };

    pub(super) fn from_rows(
        rows: Vec<UniverseContentPool>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        let by_stable_key =
            super::build_unique_map_index(rows.iter(), |row| row.stable_key.clone(), |row| row.id);
        let rows = super::decode_map_table(rows, |row| row.id);
        Ok(Self {
            keys,
            rows,
            by_stable_key,
        })
    }

    pub fn get(&self, key: &i32) -> Option<&UniverseContentPool> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &UniverseContentPool> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
    pub fn get_by_stable_key(&self, stable_key: &str) -> Option<&UniverseContentPool> {
        self.by_stable_key
            .get(stable_key)
            .and_then(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for UniverseContentPoolTable {
    type Target = SoraMap<i32, UniverseContentPool>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for UniverseContentPoolTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for UniverseContentPoolTable {
    type Key = i32;
    type Row = UniverseContentPool;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
