// This file was generated by Sora. Do not edit manually.
use super::SoraMap;
use super::unknowable_coverage_state::UnknowableCoverageState;
use super::unknowable_evidence_quality::UnknowableEvidenceQuality;
use super::unknowable_ownership::UnknowableOwnership;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct UnknowableDomainSynthesisRule {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "stable_key")]
    pub stable_key: String,
    #[serde(rename = "schema_revision")]
    pub schema_revision: String,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "name_en")]
    pub name_en: String,
    #[serde(rename = "name_zh_cn")]
    pub name_zh_cn: String,
    #[serde(rename = "summary_en")]
    pub summary_en: String,
    #[serde(rename = "summary_zh_cn")]
    pub summary_zh_cn: String,
    #[serde(rename = "ownership")]
    pub ownership: UnknowableOwnership,
    #[serde(rename = "coverage_state")]
    pub coverage_state: UnknowableCoverageState,
    #[serde(rename = "evidence_quality")]
    pub evidence_quality: UnknowableEvidenceQuality,
    #[serde(rename = "source_refs")]
    pub source_refs: Option<Vec<String>>,
    #[serde(rename = "tags")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "source_id")]
    pub source_id: String,
    #[serde(rename = "function_type")]
    pub function_type: String,
    #[serde(rename = "input_count")]
    pub input_count: String,
    #[serde(rename = "input_eligibility_json")]
    pub input_eligibility_json: String,
    #[serde(rename = "input_level_relation")]
    pub input_level_relation: String,
    #[serde(rename = "output_pool")]
    pub output_pool: Option<Vec<String>>,
    #[serde(rename = "output_pool_resolution")]
    pub output_pool_resolution: String,
    #[serde(rename = "output_ordering")]
    pub output_ordering: String,
    #[serde(rename = "cost")]
    pub cost: String,
    #[serde(rename = "fallback")]
    pub fallback: String,
    #[serde(rename = "policy_id")]
    pub policy_id: String,
}

impl super::runtime::SoraDecode for UnknowableDomainSynthesisRule {
    fn decode(
        reader: &mut super::runtime::SoraReader<'_>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            stable_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            schema_revision: <String as super::runtime::SoraDecode>::decode(reader)?,
            kind: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            ownership: <UnknowableOwnership as super::runtime::SoraDecode>::decode(reader)?,
            coverage_state: <UnknowableCoverageState as super::runtime::SoraDecode>::decode(
                reader,
            )?,
            evidence_quality: <UnknowableEvidenceQuality as super::runtime::SoraDecode>::decode(
                reader,
            )?,
            source_refs: <Option<Vec<String>> as super::runtime::SoraDecode>::decode(reader)?,
            tags: <Option<Vec<String>> as super::runtime::SoraDecode>::decode(reader)?,
            source_id: <String as super::runtime::SoraDecode>::decode(reader)?,
            function_type: <String as super::runtime::SoraDecode>::decode(reader)?,
            input_count: <String as super::runtime::SoraDecode>::decode(reader)?,
            input_eligibility_json: <String as super::runtime::SoraDecode>::decode(reader)?,
            input_level_relation: <String as super::runtime::SoraDecode>::decode(reader)?,
            output_pool: <Option<Vec<String>> as super::runtime::SoraDecode>::decode(reader)?,
            output_pool_resolution: <String as super::runtime::SoraDecode>::decode(reader)?,
            output_ordering: <String as super::runtime::SoraDecode>::decode(reader)?,
            cost: <String as super::runtime::SoraDecode>::decode(reader)?,
            fallback: <String as super::runtime::SoraDecode>::decode(reader)?,
            policy_id: <String as super::runtime::SoraDecode>::decode(reader)?,
        })
    }
}

impl UnknowableDomainSynthesisRule {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct UnknowableDomainSynthesisRuleTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, UnknowableDomainSynthesisRule>,
    by_stable_key: SoraMap<String, i32>,
}

impl UnknowableDomainSynthesisRuleTable {
    pub const NAME: &'static str = "UnknowableDomainSynthesisRule";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "UnknowableDomainSynthesisRule",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[super::SoraIndexInfo {
            name: "by_stable_key",
            unique: true,
            fields: &["stable_key"],
        }],
    };

    pub(super) fn from_rows(
        rows: Vec<UnknowableDomainSynthesisRule>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        let by_stable_key =
            super::build_unique_map_index(rows.iter(), |row| row.stable_key.clone(), |row| row.id);
        let rows = super::decode_map_table(rows, |row| row.id);
        Ok(Self {
            keys,
            rows,
            by_stable_key,
        })
    }

    pub fn get(&self, key: &i32) -> Option<&UnknowableDomainSynthesisRule> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &UnknowableDomainSynthesisRule> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
    pub fn get_by_stable_key(&self, stable_key: &str) -> Option<&UnknowableDomainSynthesisRule> {
        self.by_stable_key
            .get(stable_key)
            .and_then(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for UnknowableDomainSynthesisRuleTable {
    type Target = SoraMap<i32, UnknowableDomainSynthesisRule>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for UnknowableDomainSynthesisRuleTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for UnknowableDomainSynthesisRuleTable {
    type Key = i32;
    type Row = UnknowableDomainSynthesisRule;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
