// This file was generated by Sora. Do not edit manually.
use super::SoraMap;
use super::unknowable_coverage_state::UnknowableCoverageState;
use super::unknowable_evidence_quality::UnknowableEvidenceQuality;
use super::unknowable_ownership::UnknowableOwnership;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct UnknowableDomainSlotLayout {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "stable_key")]
    pub stable_key: String,
    #[serde(rename = "schema_revision")]
    pub schema_revision: String,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "name_en")]
    pub name_en: String,
    #[serde(rename = "name_zh_cn")]
    pub name_zh_cn: String,
    #[serde(rename = "summary_en")]
    pub summary_en: String,
    #[serde(rename = "summary_zh_cn")]
    pub summary_zh_cn: String,
    #[serde(rename = "ownership")]
    pub ownership: UnknowableOwnership,
    #[serde(rename = "coverage_state")]
    pub coverage_state: UnknowableCoverageState,
    #[serde(rename = "evidence_quality")]
    pub evidence_quality: UnknowableEvidenceQuality,
    #[serde(rename = "source_refs")]
    pub source_refs: Option<Vec<String>>,
    #[serde(rename = "tags")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "source_id")]
    pub source_id: String,
    #[serde(rename = "active_count")]
    pub active_count: String,
    #[serde(rename = "attach_count")]
    pub attach_count: String,
    #[serde(rename = "passive_count")]
    pub passive_count: String,
    #[serde(rename = "total_count")]
    pub total_count: String,
    #[serde(rename = "slot_types")]
    pub slot_types: Vec<String>,
}

impl super::runtime::SoraDecode for UnknowableDomainSlotLayout {
    fn decode(
        reader: &mut super::runtime::SoraReader<'_>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        Ok(Self {
            id: <i32 as super::runtime::SoraDecode>::decode(reader)?,
            stable_key: <String as super::runtime::SoraDecode>::decode(reader)?,
            schema_revision: <String as super::runtime::SoraDecode>::decode(reader)?,
            kind: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            name_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_en: <String as super::runtime::SoraDecode>::decode(reader)?,
            summary_zh_cn: <String as super::runtime::SoraDecode>::decode(reader)?,
            ownership: <UnknowableOwnership as super::runtime::SoraDecode>::decode(reader)?,
            coverage_state: <UnknowableCoverageState as super::runtime::SoraDecode>::decode(
                reader,
            )?,
            evidence_quality: <UnknowableEvidenceQuality as super::runtime::SoraDecode>::decode(
                reader,
            )?,
            source_refs: <Option<Vec<String>> as super::runtime::SoraDecode>::decode(reader)?,
            tags: <Option<Vec<String>> as super::runtime::SoraDecode>::decode(reader)?,
            source_id: <String as super::runtime::SoraDecode>::decode(reader)?,
            active_count: <String as super::runtime::SoraDecode>::decode(reader)?,
            attach_count: <String as super::runtime::SoraDecode>::decode(reader)?,
            passive_count: <String as super::runtime::SoraDecode>::decode(reader)?,
            total_count: <String as super::runtime::SoraDecode>::decode(reader)?,
            slot_types: <Vec<String> as super::runtime::SoraDecode>::decode(reader)?,
        })
    }
}

impl UnknowableDomainSlotLayout {
    pub(super) fn collect_text_keys<'a>(&'a self, out: &mut Vec<&'a super::runtime::TextKey>) {
        let _ = &out;
    }
}

#[derive(Debug, Clone)]
pub struct UnknowableDomainSlotLayoutTable {
    keys: Vec<i32>,
    rows: SoraMap<i32, UnknowableDomainSlotLayout>,
    by_stable_key: SoraMap<String, i32>,
}

impl UnknowableDomainSlotLayoutTable {
    pub const NAME: &'static str = "UnknowableDomainSlotLayout";
    pub const INFO: super::SoraTableInfo = super::SoraTableInfo {
        name: Self::NAME,
        row_type: "UnknowableDomainSlotLayout",
        shape: super::SoraTableShape::Keyed,
        primary_key: Some(super::SoraKeyInfo {
            name: "id",
            ty: "i32",
        }),
        indexes: &[super::SoraIndexInfo {
            name: "by_stable_key",
            unique: true,
            fields: &["stable_key"],
        }],
    };

    pub(super) fn from_rows(
        rows: Vec<UnknowableDomainSlotLayout>,
    ) -> Result<Self, super::runtime::SoraReadError> {
        let keys = rows.iter().map(|row| row.id).collect::<Vec<_>>();
        let by_stable_key =
            super::build_unique_map_index(rows.iter(), |row| row.stable_key.clone(), |row| row.id);
        let rows = super::decode_map_table(rows, |row| row.id);
        Ok(Self {
            keys,
            rows,
            by_stable_key,
        })
    }

    pub fn get(&self, key: &i32) -> Option<&UnknowableDomainSlotLayout> {
        self.rows.get(key)
    }

    pub fn keys(&self) -> &[i32] {
        &self.keys
    }

    pub fn ordered_rows(&self) -> impl Iterator<Item = &UnknowableDomainSlotLayout> {
        self.keys.iter().filter_map(|key| self.rows.get(key))
    }
    pub fn get_by_stable_key(&self, stable_key: &str) -> Option<&UnknowableDomainSlotLayout> {
        self.by_stable_key
            .get(stable_key)
            .and_then(|key| self.rows.get(key))
    }
}

impl std::ops::Deref for UnknowableDomainSlotLayoutTable {
    type Target = SoraMap<i32, UnknowableDomainSlotLayout>;

    fn deref(&self) -> &Self::Target {
        &self.rows
    }
}

impl super::ErasedSoraTable for UnknowableDomainSlotLayoutTable {
    fn info(&self) -> &'static super::SoraTableInfo {
        &Self::INFO
    }

    fn len(&self) -> usize {
        self.rows.len()
    }
}

impl super::SoraKeyedTable for UnknowableDomainSlotLayoutTable {
    type Key = i32;
    type Row = UnknowableDomainSlotLayout;

    fn get(&self, key: &Self::Key) -> Option<&Self::Row> {
        self.rows.get(key)
    }

    fn keys(&self) -> &[Self::Key] {
        &self.keys
    }
}
